'use client';
import {Alert,Button,Field,Input} from '@factoryos/ui';import Link from 'next/link';import {useRouter,useSearchParams} from 'next/navigation';import {useEffect,useState,type FormEvent} from 'react';import {authClient} from '@/lib/auth-client';import {api} from '@/lib/api';
export function AuthEmailForm({mode}:{mode:'forgot'|'reset'|'verify'}){
 const router=useRouter(),params=useSearchParams(),token=params.get('token'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[ack,setAck]=useState(false),[available,setAvailable]=useState<boolean|null>(null);
 useEffect(()=>{let current=true;void api<{available:boolean}>('/email/availability').then(r=>{if(current)setAvailable(r.available);}).catch(()=>{if(current)setAvailable(false);});return ()=>{current=false;};},[]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setError(null);setBusy(true);try{
  if(mode==='forgot'){const result=await authClient.requestPasswordReset({email,redirectTo:new URL('/reset-password',window.location.origin).toString()});if(result.error)setError(result.error.status===429?'Too many requests. Try again later.':'Could not process the request. Try again later.');else setAck(true);}
  else if(mode==='reset'){if(password.length<10||password!==confirm){setError('Use at least 10 characters and matching passwords.');return;}if(!token){setError('This reset link is invalid or has expired. Request a new link.');return;}const result=await authClient.resetPassword({newPassword:password,token});if(result.error)setError(result.error.message??'This reset link is invalid or has expired. Request a new link.');else{setPassword('');setConfirm('');router.replace('/reset-password?success=1');}}
 }catch{setError('Could not process the request. Try again later.');}finally{setBusy(false);}};
 if(mode==='verify')return <><h1 className="text-2xl font-semibold">Email verification</h1><div className="mt-5"><Alert tone={params.has('error')?'danger':'info'}>{params.has('error')?'This verification link is invalid or has expired. Sign in to request a new link.':'Your email link has been processed. Sign in to check your verification status.'}</Alert></div><Link href="/sign-in" className="mt-5 block text-accent">Sign in</Link></>;
 const reset=mode==='reset',success=reset&&params.get('success')==='1',invalid=reset&&(!token||params.has('error'))&&!success;
 return <><h1 className="text-2xl font-semibold">{reset?'Reset password':'Forgot password'}</h1><p className="mt-2 text-sm text-muted">{reset?'Choose a new password for your account.':'Request a reset link using your work email.'}</p>
 {success?<div className="mt-5"><Alert tone="success">Your password has been reset. Sign in with your new password.</Alert></div>:invalid?<div className="mt-5"><Alert tone="danger">This reset link is invalid or has expired. Request a new link.</Alert><Link href="/forgot-password" className="mt-3 block text-accent">Request a new link</Link></div>:<form onSubmit={submit} className="mt-6 space-y-4">
 {error&&<Alert tone="danger">{error}</Alert>}{ack&&<Alert tone="info">If this email exists in our system, check your email for the reset link.</Alert>}
 {!reset&&available===false&&<Alert tone="warning">Email recovery is unavailable. Contact your organization administrator.</Alert>}
 {reset?<><Field label="New password">{p=><Input {...p} type="password" autoComplete="new-password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)} required/>}</Field><Field label="Confirm password">{p=><Input {...p} type="password" autoComplete="new-password" minLength={10} value={confirm} onChange={e=>setConfirm(e.target.value)} required/>}</Field></>:<Field label="Email">{p=><Input {...p} type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/>}</Field>}
 <Button type="submit" className="w-full" loading={busy} disabled={!reset&&available!==true}>{reset?'Save new password':'Request reset link'}</Button></form>}
 <Link href="/sign-in" className="mt-5 block text-center text-sm text-accent">Back to sign in</Link></>;
}
