import {claimOperation,completeOperation,recoverExpiredLease,gstSandboxMockRemote,gstRegistration,type Database,type LeasedOperation} from '@factoryos/db';
import {MockSandboxProvider,canonicalHash,evidenceMatches,actionSchema,snapshotSchema,transportSchema,type ProviderCommand,type ProviderEvidence,type ProviderOutcome,type MockScenario} from '@factoryos/gsp';
import {and,eq} from 'drizzle-orm';
function commandOf(op:LeasedOperation):ProviderCommand{const x=op.command;return {action:actionSchema.parse(x.action),snapshot:snapshotSchema.parse(x.snapshot),...(x.transport?{transport:transportSchema.parse(x.transport)}:{}),...(typeof x.externalId==='string'?{externalId:x.externalId}:{}),...(typeof x.irn==='string'?{irn:x.irn}:{}),...(typeof x.reason==='string'?{reason:x.reason}:{})}}
export async function runSandboxOnce(db:Database,workerId='sandbox-worker'):Promise<boolean>{await recoverExpiredLease(db);const op=await claimOperation(db,workerId);if(!op)return false;try{
 const c=commandOf(op);const [reg]=await db.select().from(gstRegistration).where(and(eq(gstRegistration.id,op.registrationId),eq(gstRegistration.tenantId,op.tenantId),eq(gstRegistration.entityId,op.entityId)));if(!reg)throw new Error('Registration unavailable');
 const provider=new MockSandboxProvider({get:async key=>{const [r]=await db.select().from(gstSandboxMockRemote).where(and(eq(gstSandboxMockRemote.key,key),eq(gstSandboxMockRemote.tenantId,op.tenantId),eq(gstSandboxMockRemote.entityId,op.entityId)));return r?r.evidence as unknown as ProviderEvidence:null},put:async(key,value)=>{await db.insert(gstSandboxMockRemote).values({key,tenantId:op.tenantId,entityId:op.entityId,evidence:{...value}}).onConflictDoUpdate({target:gstSandboxMockRemote.key,set:{evidence:{...value}}})}});
 const timeout=new Promise<ProviderOutcome>(resolve=>{const t=setTimeout(()=>resolve({kind:'unknown'}),20000);t.unref()});let outcome=await Promise.race([provider.execute(c,{scope:{tenantId:op.tenantId,entityId:op.entityId,registrationId:op.registrationId,gstin:reg.gstin,environment:'sandbox'},provider:'mock',scenario:op.scenario as MockScenario}),timeout]);
 if(outcome.kind==='confirmed'&&!evidenceMatches({gstin:c.snapshot.seller.gstin!,documentHash:canonicalHash(c.snapshot),documentNumber:c.snapshot.number,documentType:c.snapshot.documentType},outcome.evidence))outcome={kind:'unknown'};
 await completeOperation(db,op.leaseToken,outcome.kind==='confirmed'?{kind:'confirmed',evidence:{...outcome.evidence}}:outcome);
 }catch{await completeOperation(db,op.leaseToken,{kind:'unknown'})}return true;}
