'use client';
import {Alert,Button,Card,Field,Input,Table,Td,Th} from '@factoryos/ui';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Suspense,useEffect,useState} from 'react';
import Link from 'next/link';
import {useSearchParams} from 'next/navigation';
import {api} from '@/lib/api';
import {today} from '@/lib/format';
import {bankPath,downloadBank,isZero,useCurrentReview,type Report,type Period,type MatchState} from '@/lib/bank-reconciliation';
import {AccountingPage} from '../accounting-shared';
import {useWorkspace} from '../workspace';
import {Text} from './shared';
export default function BankReport({id}:{id:string}){const ws=useWorkspace(),cache=useQueryClient(),[date,setDate]=useState(today()),[checked,setChecked]=useState(false),[reason,setReason]=useState(''),[preview,setPreview]=useState<{key:string;value:Report}|null>(null),[downloadError,setDownloadError]=useState('');const prefix=['bank',ws.tenantId,ws.entityId,id];const periods=useQuery({queryKey:[...prefix,'periods'],queryFn:()=>api<Period[]>(`${bankPath(id)}/periods`,{scope:ws.scope})}),state=useQuery({queryKey:[...prefix,'matches'],queryFn:()=>api<MatchState>(`${bankPath(id)}/matches`,{scope:ws.scope})});const key=JSON.stringify({date,revision:state.data?.revision,periods:periods.data?.map(x=>[x.id,x.reopened])}),current=useCurrentReview(key);useEffect(()=>setChecked(false),[key]);const review=useMutation({mutationFn:({date:asOf}:{date:string;key:string})=>api<Report>(`${bankPath(id)}/report?asOf=${asOf}`,{scope:ws.scope}),onSuccess:(value,vars)=>{if(current(vars.key))setPreview({value,key:vars.key});}}),approve=useMutation({mutationFn:(report:Report)=>api(`${bankPath(id)}/periods/approve`,{method:'POST',body:{asOf:report.asOf,reviewedHash:report.previewHash,outstandingReviewed:true},scope:ws.scope}),onSuccess:()=>cache.invalidateQueries({queryKey:prefix})}),reopen=useMutation({mutationFn:(periodId:string)=>api(`${bankPath(id)}/periods/${periodId}/reopen`,{method:'POST',body:{reason},scope:ws.scope}),onSuccess:()=>cache.invalidateQueries({queryKey:prefix})});const report=preview?.key===key?preview.value:null;const exportCsv=async()=>{try{await downloadBank(`${bankPath(id)}/report/export?asOf=${date}`,ws.scope,'bank-reconciliation.csv');}catch(e){setDownloadError((e as Error).message);}};
 return <div className="space-y-4"><Card className="p-5 space-y-4"><h2 className="font-semibold">Dated reconciliation report</h2><div className="flex flex-wrap items-end gap-3"><Text label="Report date" value={date} type="date" onChange={setDate}/><Button disabled={review.isPending||state.isFetching||periods.isFetching||!state.data||!periods.data} onClick={()=>review.mutate({date,key})}>Review dated report</Button>{ws.can('accounts.bank_reconciliation.export')&&<Button variant="secondary" onClick={()=>void exportCsv()}>Export dated report</Button>}</div>{(review.error||approve.error||downloadError||periods.error)&&<Alert tone="danger">{review.error?.message??approve.error?.message??(downloadError||periods.error?.message)}</Alert>}{report&&<><Balances report={report}/><p>{report.coverageComplete?'Complete statement coverage':'Incomplete statement coverage'}</p><p className="text-sm text-muted">Coverage through {report.coverage.through}. Each allocation clears only after both dates; documented net groups clear together on their latest date.</p>{report.coverage.conflicts.map(x=><Alert tone="danger" key={x}>{x}</Alert>)}<Residuals report={report}/>{ws.can('accounts.bank_reconciliation.approve')&&<><Field label="I reviewed the remaining uncleared book items">{p=><Input {...p} type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>}</Field><Button disabled={!checked||approve.isPending||!report.coverageComplete||!isZero(report.difference)||report.statementResiduals.some(x=>!isZero(x.remaining))} onClick={()=>approve.mutate(report)}>Approve period</Button></>}</>}</Card><Card className="p-5 space-y-4"><h2 className="font-semibold">Approved report history</h2>{periods.data?.map(p=><div key={p.id} className="flex flex-wrap items-center gap-3 border-b border-line py-3"><p>{p.startDate} to {p.endDate} · {p.reopened?'Reopened':'Approved'}</p><Link className="text-accent" href={`/app/accounts/bank-reconciliation/reports/${p.id}/print?profile=${id}`}>Print approved report</Link><p className="break-all text-xs text-muted">Reviewer {p.createdBy} · {p.createdAt}</p>{p.reopening&&<p className="text-sm">Reopened: {p.reopening.reason}</p>}{!p.reopened&&ws.can('accounts.bank_reconciliation.approve')&&<Button variant="secondary" disabled={!reason.trim()||reopen.isPending} onClick={()=>reopen.mutate(p.id)}>Reopen period</Button>}</div>)}{ws.can('accounts.bank_reconciliation.approve')&&<Text label="Period reopening reason" value={reason} onChange={setReason}/>} {reopen.error&&<Alert tone="danger">{reopen.error.message}</Alert>}</Card></div>;
}
function Balances({report}:{report:Report}){return <div className="grid gap-3 sm:grid-cols-3">{[['Book balance',report.B],['Uncleared book items',report.U],['Bank-only exceptions',report.E],['Statement balance',report.S],['Difference',report.difference]].map(([label,value])=><div key={label} className="rounded-lg border border-line p-3"><p className="text-xs text-muted">{label}</p><p className="break-all font-mono">{value}</p></div>)}<p className="text-sm text-muted">Statement = Book − Uncleared + Exceptions</p></div>;}
function Residuals({report}:{report:Report}){return <div className="space-y-3"><h3 className="font-medium">Genuine uncleared book items and bank exceptions</h3><Table><thead><tr><Th>Kind</Th><Th>Original date</Th><Th>Reference</Th><Th>Signed amount</Th><Th>Remaining</Th></tr></thead><tbody>{[...report.bookResiduals.map(x=>({...x,side:x.kind})),...report.statementResiduals.map(x=>({...x,side:'bank'}))].map(x=><tr key={`${x.side}:${x.id}`}><Td>{x.side}</Td><Td>{x.date}</Td><Td>{x.reference}</Td><Td>{x.signedAmount}</Td><Td>{x.remaining}</Td></tr>)}</tbody></Table></div>;}
export function BankReportPrint({id}:{id:string}){return <AccountingPage title="Approved bank reconciliation" permission="accounts.bank_reconciliation.read"><Suspense fallback={<p>Loading stored report…</p>}><PrintLoad id={id}/></Suspense></AccountingPage>;}
function PrintLoad({id}:{id:string}){const ws=useWorkspace(),params=useSearchParams(),profileId=params.get('profile');const q=useQuery({queryKey:['bank',ws.tenantId,ws.entityId,profileId,'period',id],queryFn:()=>api<Period>(`${bankPath(profileId!)}/periods/${id}`,{scope:ws.scope}),enabled:!!profileId,retry:false});if(!profileId)return <Alert tone="danger">Choose an approved report from its bank history.</Alert>;if(q.error)return <Alert tone="danger">{q.error.message}</Alert>;if(!q.data)return <p>Loading stored report…</p>;const period=q.data;return <Card className="p-5 space-y-5"><div className="print:hidden"><Button onClick={()=>window.print()}>Print / save PDF</Button></div><p>{period.startDate} to {period.endDate} · INR · {period.reopened?'Historical approved revision — reopened':'Approved revision'}</p><p>Statement balance: {period.snapshot.report.S}</p><Balances report={period.snapshot.report}/><Residuals report={period.snapshot.report}/><p className="break-all text-xs">Reviewer {period.createdBy} · Approved {period.createdAt} · Evidence hash {period.previewHash}</p></Card>;}
