'use client';
import {Alert,Button,Card,Field,Select} from '@factoryos/ui';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Suspense,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import {api} from '@/lib/api';
import {bankPath,defaultMapping,useCurrentReview,type Context,type Mapping,type Profile} from '@/lib/bank-reconciliation';
import type {AccountGroup} from '@/lib/accounting';
import {AccountingPage,useAccounts} from '../accounting-shared';
import {useWorkspace} from '../workspace';
import {Text} from './shared';
export default function BankSettings(){return <AccountingPage title="Bank reconciliation settings" permission="accounts.bank_reconciliation.configure"><Suspense fallback={<p>Loading settings…</p>}><Load/></Suspense></AccountingPage>;}
function Load(){const ws=useWorkspace(),params=useSearchParams(),id=params.get('profile'),q=useQuery({queryKey:['bank',ws.tenantId,ws.entityId,id,'context'],queryFn:()=>api<Context>(bankPath(id!),{scope:ws.scope}),enabled:!!id});if(q.error)return <Alert tone="danger">{q.error.message}</Alert>;if(id&&!q.data)return <p>Loading mapping…</p>;return <Settings key={`${ws.tenantId}:${ws.entityId}:${id??'new'}:${q.data?.mapping?.revision??0}`} context={q.data}/>;}
function Settings({context}:{context?:Context}){const ws=useWorkspace(),router=useRouter(),cache=useQueryClient(),accounts=useAccounts();const groups=useQuery({queryKey:['account-groups',ws.tenantId,ws.entityId],queryFn:()=>api<AccountGroup[]>('/accounts/groups',{scope:ws.scope})});const profiles=useQuery({queryKey:['bank-profiles',ws.tenantId,ws.entityId],queryFn:()=>api<Profile[]>('/accounts/bank-reconciliation/profiles',{scope:ws.scope})});const [accountId,setAccount]=useState(context?.profile.accountId??''),[mask,setMask]=useState(context?.profile.maskedIdentifier??''),[window,setWindow]=useState(String(context?.profile.dateWindow??7)),[mapping,setMapping]=useState<Mapping>(context?.mapping?.mapping??defaultMapping);const key=JSON.stringify({accountId,mask,window,mapping}),current=useCurrentReview(key);
 const save=useMutation({mutationFn:({key:captured,...body}:{key:string;dateWindow:number;mapping:Mapping;accountId?:string;maskedIdentifier?:string;currency?:'INR'})=>api(context?bankPath(context.profile.id):'/accounts/bank-reconciliation/profiles',{method:context?'PUT':'POST',body,scope:ws.scope}),onSuccess:async(_,vars)=>{if(!current(vars.key))return;await cache.invalidateQueries({queryKey:['bank-profiles',ws.tenantId,ws.entityId]});await cache.invalidateQueries({queryKey:['bank',ws.tenantId,ws.entityId]});router.push('/app/accounts/bank-reconciliation');}});
 const bankGroup=(id:string)=>{const seen=new Set<string>();while(!seen.has(id)){seen.add(id);const g=groups.data?.find(x=>x.id===id);if(!g)return false;if(g.name==='Bank Accounts'&&g.root==='asset')return true;if(!g.parentId)return false;id=g.parentId;}return false;};const set=<K extends keyof Mapping>(k:K,v:Mapping[K])=>setMapping(old=>({...old,[k]:v}));
 return <div className="space-y-4"><p className="text-sm text-muted">Use UTF-8 CSV and the exact bank column headings. Submitted evidence keeps its original mapping. Bank account and currency remain fixed; changes create a new mapping revision.</p><Card className="grid gap-4 p-5 sm:grid-cols-2">
 <Field label="Bank account">{p=><Select {...p} value={accountId} disabled={!!context} onChange={e=>setAccount(e.target.value)}><option value="">Choose bank</option>{accounts.data?.filter(a=>a.id===context?.profile.accountId||(a.isActive&&bankGroup(a.groupId)&&!profiles.data?.some(x=>x.accountId===a.id))).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</Select>}</Field>
 <Text label="Masked bank identifier" value={mask} onChange={setMask} disabled={!!context} hint="Use masking characters and up to four trailing characters, for example ••1234."/>
 <Text label="Candidate date window (days)" value={window} onChange={setWindow} type="number"/>
 <Field label="Delimiter">{p=><Select {...p} value={mapping.delimiter} onChange={e=>set('delimiter',e.target.value)}><option value=",">Comma</option><option value=";">Semicolon</option><option value={'\t'}>Tab</option><option value="|">Pipe</option></Select>}</Field>
 <Text label="Rows before header" type="number" value={String(mapping.skipRows)} onChange={v=>set('skipRows',Number(v))}/>
 <Field label="Date format">{p=><Select {...p} value={mapping.dateFormat} onChange={e=>set('dateFormat',e.target.value as Mapping['dateFormat'])}>{['DD/MM/YYYY','MM/DD/YYYY','YYYY-MM-DD'].map(x=><option key={x}>{x}</option>)}</Select>}</Field>
 {(['dateColumn','referenceColumn','descriptionColumn','transactionIdColumn','runningBalanceColumn'] as const).map(k=><Text key={k} label={{dateColumn:'Date column',referenceColumn:'Reference column',descriptionColumn:'Description column',transactionIdColumn:'Stable transaction ID column',runningBalanceColumn:'Running balance column'}[k]} value={mapping[k]??''} onChange={v=>{if(k==='dateColumn')set(k,v);else set(k,v||undefined);}}/>)}
 <Field label="Amount mode">{p=><Select {...p} value={mapping.amount.mode} onChange={e=>set('amount',e.target.value==='split'?{mode:'split',debitColumn:'Debit',creditColumn:'Credit'}:{mode:'signed',column:'Amount',polarity:'credit-positive'})}><option value="split">Separate debit and credit</option><option value="signed">Signed amount</option></Select>}</Field>
 {mapping.amount.mode==='split'?<><Text label="Debit column" value={mapping.amount.debitColumn} onChange={v=>setMapping(old=>({...old,amount:{mode:'split',debitColumn:v,creditColumn:old.amount.mode==='split'?old.amount.creditColumn:'Credit'}}))}/><Text label="Credit column" value={mapping.amount.creditColumn} onChange={v=>setMapping(old=>({...old,amount:{mode:'split',creditColumn:v,debitColumn:old.amount.mode==='split'?old.amount.debitColumn:'Debit'}}))}/></>:<><Text label="Amount column" value={mapping.amount.column} onChange={v=>setMapping(old=>({...old,amount:{mode:'signed',column:v,polarity:old.amount.mode==='signed'?old.amount.polarity:'credit-positive'}}))}/><Field label="Signed amount polarity">{p=><Select {...p} value={mapping.amount.mode==='signed'?mapping.amount.polarity:''} onChange={e=>setMapping(old=>({...old,amount:{mode:'signed',column:old.amount.mode==='signed'?old.amount.column:'Amount',polarity:e.target.value as 'credit-positive'|'debit-positive'}}))}><option value="credit-positive">Credits increase bank balance</option><option value="debit-positive">Debits use positive values</option></Select>}</Field></>}
 <Field label="Decimal separator">{p=><Select {...p} value={mapping.decimalSeparator} onChange={e=>set('decimalSeparator',e.target.value as '.'|',')}><option value=".">Dot</option><option value=",">Comma</option></Select>}</Field>
 <Field label="Grouping separator">{p=><Select {...p} value={mapping.groupSeparator??''} onChange={e=>set('groupSeparator',(e.target.value||null) as Mapping['groupSeparator'])}><option value="">None</option><option value=",">Comma</option><option value=".">Dot</option><option value=" ">Space</option></Select>}</Field>
 <Field label="Statement row order">{p=><Select {...p} value={mapping.order} onChange={e=>set('order',e.target.value as Mapping['order'])}><option value="ascending">Oldest first</option><option value="descending">Newest first</option></Select>}</Field>
 <Text label="Balance-only marker column" value={mapping.balanceRow?.column??''} onChange={v=>set('balanceRow',v?{column:v,value:mapping.balanceRow?.value??''}:undefined)}/><Text label="Balance-only marker value" value={mapping.balanceRow?.value??''} onChange={v=>set('balanceRow',mapping.balanceRow?{...mapping.balanceRow,value:v}:undefined)}/>
 </Card>{(save.error||accounts.error||groups.error||profiles.error)&&<Alert tone="danger">{save.error?.message??accounts.error?.message??groups.error?.message??profiles.error?.message}</Alert>}<Button disabled={save.isPending||!accountId||!Number.isInteger(Number(window))||Number(window)<0||Number(window)>30} onClick={()=>save.mutate({key,dateWindow:Number(window),mapping,...context?{}:{accountId,maskedIdentifier:mask,currency:'INR' as const}})}>Save bank profile</Button></div>;
}
