'use client';
import {Alert,Button,Card,Field,Input,Select,Table,Td,Th} from '@factoryos/ui';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Suspense,useState} from 'react';
import Link from 'next/link';
import {useRouter,useSearchParams} from 'next/navigation';
import {api} from '@/lib/api';
import {today} from '@/lib/format';
import {bankPath,downloadBank,uploadBankCsv,useCurrentReview,type Context} from '@/lib/bank-reconciliation';
import {AccountingPage} from '../accounting-shared';
import {useWorkspace} from '../workspace';
import {Text} from './shared';
export function StatementUpload({id,context}:{id:string;context:Context}){const ws=useWorkspace(),router=useRouter(),[file,setFile]=useState<File|null>(null),[generation,setGeneration]=useState(0),[startDate,setStart]=useState(today()),[endDate,setEnd]=useState(today()),[openingBalance,setOpening]=useState(context.baseline?.bankBalance??'0'),[closingBalance,setClosing]=useState(context.baseline?.bankBalance??'0');const metadata={startDate,endDate,openingBalance,closingBalance,mappingId:context.mapping?.id},key=JSON.stringify({metadata,generation}),current=useCurrentReview(key);const stage=useMutation({mutationFn:({file:chosen,metadata:period}:{file:File;metadata:typeof metadata;key:string})=>uploadBankCsv(id,chosen,period,ws.scope),onSuccess:(batch,vars)=>{if(current(vars.key))router.push(`/app/accounts/bank-reconciliation/imports/${batch.id}?profile=${id}`);}});if(!ws.can('accounts.bank_reconciliation.create'))return null;return <Card className="p-5 space-y-4"><h2 className="font-semibold">Import a bank statement</h2><p className="text-sm text-muted">CSV up to 5 MiB. Credits increase the bank balance; debits reduce it. Review errors, signed rows and duplicate occurrences before submission.</p><div className="grid gap-4 sm:grid-cols-2"><Text label="Statement start" type="date" value={startDate} onChange={setStart}/><Text label="Statement end" type="date" value={endDate} onChange={setEnd}/><Text label="Import opening balance" value={openingBalance} onChange={setOpening}/><Text label="Import closing balance" value={closingBalance} onChange={setClosing}/><Field label="Statement CSV">{p=><Input {...p} type="file" accept=".csv,text/csv" onChange={e=>{setFile(e.target.files?.[0]??null);setGeneration(x=>x+1);}}/>}</Field></div>{file&&file.size>5*1024*1024&&<Alert tone="danger">Choose a CSV up to 5 MiB.</Alert>}{stage.error&&<Alert tone="danger">{stage.error.message}</Alert>}<Button disabled={!file||file.size>5*1024*1024||!context.mapping||stage.isPending} onClick={()=>stage.mutate({file:file!,metadata,key})}>Stage statement</Button></Card>;}
interface ImportReview {batch:{id:string;status:string;startDate:string;endDate:string;fileHash:string;mappingId:string};parsed:{rows:{ordinal:number;date:string;reference:string;description:string;signedAmount:string}[];errors:{ordinal?:number;message:string}[];netAmount:string};conflicts:{ordinal:number;message:string}[];ambiguities:{ordinal:number;candidateIds:string[]}[];linked:{ordinal:number;movementId:string}[];decisions:Decision[];previewHash:string}
interface Decision {ordinal:number;decision:'link'|'distinct';movementId?:string;reason:string}
export default function StatementReviewPage({id}:{id:string}){return <AccountingPage title="Bank statement review" permission="accounts.bank_reconciliation.read"><Suspense fallback={<p>Loading statement…</p>}><Load id={id}/></Suspense></AccountingPage>;}
function Load({id}:{id:string}){const ws=useWorkspace(),params=useSearchParams(),profileId=params.get('profile');if(!profileId)return <Alert tone="danger">Choose the statement from its bank workspace.</Alert>;return <Review key={`${ws.tenantId}:${ws.entityId}:${profileId}:${id}`} id={id} profileId={profileId}/>;}
function Review({id,profileId}:{id:string;profileId:string}){const ws=useWorkspace(),cache=useQueryClient(),[decisions,setDecisions]=useState<Decision[]>([]),[downloadError,setDownloadError]=useState('');const prefix=['bank',ws.tenantId,ws.entityId,profileId];const q=useQuery({queryKey:[...prefix,'review',id],queryFn:()=>api<ImportReview>(`${bankPath(profileId)}/imports/${id}/review`,{scope:ws.scope}),retry:false});const history=useQuery({queryKey:[...prefix,'imports'],queryFn:()=>api<{id:string;reversed:boolean}[]>(`${bankPath(profileId)}/imports`,{scope:ws.scope})});const key=JSON.stringify({hash:q.data?.previewHash,decisions}),current=useCurrentReview(key);const submit=useMutation({mutationFn:({key:captured,...body}:{key:string;reviewedHash:string;decisions:Decision[]})=>api(`${bankPath(profileId)}/imports/${id}/submit`,{method:'POST',body,scope:ws.scope}),onSuccess:async(_,vars)=>{if(current(vars.key))await cache.invalidateQueries({queryKey:prefix});}});const download=async(raw:boolean)=>{try{await downloadBank(`${bankPath(profileId)}/imports/${id}/${raw?'raw':'export'}`,ws.scope,raw?'statement-evidence.txt':'bank-movements.csv');}catch(e){setDownloadError((e as Error).message);}};
 if(q.error)return <Alert tone="danger">{q.error.message}</Alert>;if(!q.data)return <p>Loading statement rows…</p>;const review=q.data,reversed=history.data?.find(x=>x.id===id)?.reversed,submitted=review.batch.status==='submitted',finance=ws.can('accounts.bank_reconciliation.approve');const edit=(ordinal:number,change:Partial<Decision>)=>setDecisions(old=>{const prior=old.find(x=>x.ordinal===ordinal)??{ordinal,decision:'link' as const,movementId:review.ambiguities.find(x=>x.ordinal===ordinal)?.candidateIds[0],reason:''};return [...old.filter(x=>x.ordinal!==ordinal),{...prior,...change}];});const ready=review.ambiguities.every(a=>decisions.some(d=>d.ordinal===a.ordinal&&d.reason.trim()&&(d.decision==='distinct'||d.movementId)));
 return <div className="min-w-0 space-y-4"><Link className="text-accent" href="/app/accounts/bank-reconciliation">Return to reconciliation</Link><Card className="p-5 space-y-2"><h2 className="font-semibold">Original statement evidence</h2><p>{review.batch.startDate} to {review.batch.endDate} · Mapping {review.batch.mappingId}</p><p className="break-all text-xs text-muted">File SHA-256 {review.batch.fileHash}</p><p>Statement net: {review.parsed.netAmount}</p>{reversed?<Alert tone="danger">Statement reversed</Alert>:submitted?<Alert>Statement submitted</Alert>:<Alert>Draft statement: review every error and duplicate before submission.</Alert>}<div className="flex flex-wrap gap-3"><Button variant="secondary" onClick={()=>void download(true)}>Download original evidence</Button>{ws.can('accounts.bank_reconciliation.export')&&<Button variant="secondary" onClick={()=>void download(false)}>Export normalized movements</Button>}</div></Card>{[...review.parsed.errors,...review.conflicts].map((x,i)=><Alert key={i} tone="danger">Row {x.ordinal??'file'}: {x.message}</Alert>)}{(submit.error||downloadError)&&<Alert tone="danger">{submit.error?.message??downloadError}</Alert>}
 <Card><Table><thead><tr><Th>Original row</Th><Th>Date</Th><Th>Reference / description</Th><Th>Signed INR</Th><Th>Canonical identity</Th></tr></thead><tbody>{review.parsed.rows.map(row=><tr key={row.ordinal}><Td>{row.ordinal}</Td><Td>{row.date}</Td><Td><p className="break-words">{row.reference}</p><p className="break-words text-xs text-muted">{row.description}</p></Td><Td>{row.signedAmount}</Td><Td>{review.linked.find(x=>x.ordinal===row.ordinal)?.movementId??(review.ambiguities.some(x=>x.ordinal===row.ordinal)?'Finance decision required':'New occurrence')}</Td></tr>)}</tbody></Table></Card>
 {!submitted&&review.ambiguities.map(a=>{const decision=decisions.find(x=>x.ordinal===a.ordinal);return <Card key={a.ordinal} className="p-4 space-y-3"><h3 className="font-medium">Duplicate review · original row {a.ordinal}</h3>{finance?<><Field label={`Row ${a.ordinal} duplicate decision`}>{p=><Select {...p} value={decision?.decision??''} onChange={e=>edit(a.ordinal,{decision:e.target.value as Decision['decision'],movementId:e.target.value==='link'?a.candidateIds[0]:undefined})}><option value="">Choose explicitly</option><option value="link">Link an existing occurrence</option><option value="distinct">Confirm a different real occurrence</option></Select>}</Field>{decision?.decision==='link'&&<Field label={`Row ${a.ordinal} canonical occurrence`}>{p=><Select {...p} value={decision.movementId??''} onChange={e=>edit(a.ordinal,{movementId:e.target.value})}>{a.candidateIds.map(x=><option key={x}>{x}</option>)}</Select>}</Field>}<Text label={`Row ${a.ordinal} duplicate reason`} value={decision?.reason??''} onChange={v=>edit(a.ordinal,{reason:v})}/></>:<Alert>Finance must resolve ambiguous occurrences.</Alert>}</Card>;})}
 {submitted&&review.decisions.map(d=><p key={d.ordinal}>Original row {d.ordinal}: {d.decision} · {d.reason}</p>)}
 {!submitted&&!reversed&&ws.can('accounts.bank_reconciliation.submit')&&<Button disabled={submit.isPending||review.parsed.errors.length>0||review.conflicts.length>0||(!finance&&review.ambiguities.length>0)||!ready} onClick={()=>submit.mutate({key,reviewedHash:review.previewHash,decisions})}>Submit statement</Button>}</div>;
}
