'use client';
import {Alert,Card,Field,Select,Table,Td,Th,Button,buttonClass} from '@factoryos/ui';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import Link from 'next/link';
import {useState} from 'react';
import {api} from '@/lib/api';
import {bankPath,type Profile,type Context} from '@/lib/bank-reconciliation';
import {AccountingPage,useAccounts} from '../accounting-shared';
import {useWorkspace} from '../workspace';
import Baseline from './baseline';
import {StatementUpload} from './statement-import';
import MatchWorkspace from './match-workspace';
import BankReport from './report';
import {Text} from './shared';
export default function BankWorkspace(){const ws=useWorkspace();return <AccountingPage title="Bank reconciliation" permission="accounts.bank_reconciliation.read"><Workspace key={`${ws.tenantId}:${ws.entityId}`}/></AccountingPage>;}
function Workspace(){const ws=useWorkspace(),accounts=useAccounts(),[selected,setSelected]=useState('');const profiles=useQuery({queryKey:['bank-profiles',ws.tenantId,ws.entityId],queryFn:()=>api<Profile[]>('/accounts/bank-reconciliation/profiles',{scope:ws.scope})});const id=selected||profiles.data?.[0]?.id;return <div className="min-w-0 space-y-5">
 <div className="flex flex-wrap items-end gap-3"><div className="min-w-0 flex-1"><Field label="Reconciliation bank">{p=><Select {...p} value={id??''} onChange={e=>setSelected(e.target.value)}><option value="">Choose a bank profile</option>{profiles.data?.map(x=><option key={x.id} value={x.id}>{accounts.data?.find(a=>a.id===x.accountId)?.name??'Historical bank'} · {x.maskedIdentifier}</option>)}</Select>}</Field></div>{ws.can('accounts.bank_reconciliation.configure')&&<Link className={buttonClass('secondary')} href="/app/accounts/bank-reconciliation/settings">Configure bank</Link>}</div>
 {profiles.error&&<Alert tone="danger">{profiles.error.message}</Alert>}{!id&&<Card className="p-5">Finance can configure an INR bank and review its opening statement balance.</Card>}{id&&<AccountWorkspace key={`${ws.tenantId}:${ws.entityId}:${id}`} id={id}/>}</div>;}
function AccountWorkspace({id}:{id:string}){const ws=useWorkspace(),q=useQuery({queryKey:['bank',ws.tenantId,ws.entityId,id,'context'],queryFn:()=>api<Context>(bankPath(id),{scope:ws.scope})});if(q.error)return <Alert tone="danger">{q.error.message}</Alert>;if(!q.data)return <p>Loading bank evidence…</p>;return <div className="space-y-5"><div className="flex flex-wrap gap-3"><p>INR · {q.data.profile.maskedIdentifier} · Mapping revision {q.data.mapping?.revision}</p>{ws.can('accounts.bank_reconciliation.configure')&&<Link className="text-accent" href={`/app/accounts/bank-reconciliation/settings?profile=${id}`}>Edit mapping and date window</Link>}</div><Baseline id={id} context={q.data}/>{q.data.baseline&&<><StatementUpload id={id} context={q.data}/><Imports id={id}/><MatchWorkspace id={id}/><BankReport id={id}/></>}</div>;}
function Imports({id}:{id:string}){const ws=useWorkspace(),cache=useQueryClient(),[reason,setReason]=useState('');const q=useQuery({queryKey:['bank',ws.tenantId,ws.entityId,id,'imports'],queryFn:()=>api<{id:string;startDate:string;endDate:string;status:string;reversed:boolean}[]>(`${bankPath(id)}/imports`,{scope:ws.scope})});const reverse=useMutation({mutationFn:(importId:string)=>api(`${bankPath(id)}/imports/${importId}/reverse`,{method:'POST',body:{reason},scope:ws.scope}),onSuccess:()=>cache.invalidateQueries({queryKey:['bank',ws.tenantId,ws.entityId,id]})});return <Card><h2 className="p-4 font-semibold">Statement evidence</h2>{(q.error||reverse.error)&&<Alert tone="danger">{q.error?.message??reverse.error?.message}</Alert>}<Table><thead><tr><Th>Interval</Th><Th>Status</Th><Th>Review</Th><Th>Correction</Th></tr></thead><tbody>{q.data?.map(x=><tr key={x.id}><Td>{x.startDate} to {x.endDate}</Td><Td>{x.reversed?'reversed':x.status}</Td><Td><Link className="text-accent" href={`/app/accounts/bank-reconciliation/imports/${x.id}?profile=${id}`}>Review statement</Link></Td><Td>{ws.can('accounts.bank_reconciliation.cancel')&&x.status==='submitted'&&!x.reversed&&<Button variant="ghost" disabled={!reason.trim()||reverse.isPending} onClick={()=>reverse.mutate(x.id)}>Reverse import</Button>}</Td></tr>)}</tbody></Table>{ws.can('accounts.bank_reconciliation.cancel')&&<div className="p-4"><Text label="Import reversal reason" value={reason} onChange={setReason}/></div>}</Card>;}
