'use client';
import {Alert,Badge,Button,Card,Field as UiField,Input,Select,Table,Td,Th,buttonClass} from '@factoryos/ui';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {useParams,useRouter,useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {cloneElement,isValidElement,useEffect,useMemo,useRef,useState,type ReactNode} from 'react';
import {api} from '@/lib/api';
import type {SellingDocument} from '@/lib/selling';
import type {CustomerNote,NoteInput,NoteLineInput,NotePreview,NoteBill} from '@/lib/sales-notes';
import {EntityGate} from './entity-gate';
import {InvoiceBalance} from './invoice-balance';
import {useWorkspace} from './workspace';
function Field({label,children}:{label:string;children:ReactNode}){return <UiField label={label}>{props=>isValidElement<{id?:string}>(children)?cloneElement(children,props):children}</UiField>;}
const positive=(value:string|undefined)=>!!value&&/^\d+(?:\.\d{1,6})?$/.test(value)&&/[1-9]/.test(value);
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata'}).format(new Date());
function initialLines(n:CustomerNote):NoteLineInput[]{return n.lines.map(l=>({invoiceLineId:l.invoiceLineId,mode:l.mode,...(l.mode==='quantity'?{qty:l.qty}:{taxableAmount:l.taxableAmount}),...(positive(l.returnQty)?{returnQty:l.returnQty,warehouseId:l.warehouseId??undefined}:{})}));}
export function SalesNoteForm({fresh=false}:{fresh?:boolean}){
 const ws=useWorkspace(),router=useRouter(),params=useParams<{id:string}>(),search=useSearchParams(),qc=useQueryClient(),routeId=fresh?undefined:params.id;
 const [kind,setKind]=useState<'credit'|'debit'>((search.get('kind')==='debit')?'debit':'credit'),[treatment,setTreatment]=useState<'gst'|'commercial'>('gst'),[date,setDate]=useState(today),[due,setDue]=useState(''),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[lines,setLines]=useState<NoteLineInput[]>([]),[error,setError]=useState(''),[cancelOpen,setCancelOpen]=useState(false),[cancelReason,setCancelReason]=useState('');
 const hydrate=useRef(''),saved=useRef(''),rejected=useRef('');
 const note=useQuery({queryKey:['sales-note',ws.tenantId,ws.entityId,routeId],queryFn:()=>api<CustomerNote>(`/sales-notes/${routeId}`,{scope:ws.scope}),enabled:!!routeId&&!!ws.entityId&&ws.can('selling.sales_note.read'),staleTime:0,refetchOnMount:'always'});
 const invoiceId=note.data?.originalInvoiceId??search.get('invoiceId');
 const original=useQuery({queryKey:['note-invoice',ws.tenantId,ws.entityId,invoiceId],queryFn:()=>api<SellingDocument>(`/sales-invoices/${invoiceId}`,{scope:ws.scope}),enabled:!!invoiceId&&!!ws.entityId&&ws.can('selling.sales_invoice.read'),staleTime:0});
 const warehouses=useQuery({queryKey:['warehouses',ws.tenantId,ws.entityId],queryFn:()=>api<{id:string;name:string;isActive:boolean}[]>('/warehouses',{scope:ws.scope}),enabled:!!ws.entityId&&ws.can('inventory.warehouse.read')});
 const editable=!note.data||note.data.status==='draft',canEdit=editable&&ws.can(routeId?'selling.sales_note.update':'selling.sales_note.create');
 useEffect(()=>{if(note.data&&hydrate.current!==`${ws.entityId}:${note.data.id}`){const n=note.data;hydrate.current=`${ws.entityId}:${n.id}`;setKind(n.kind);setTreatment(n.taxTreatment);setDate(n.postingDate);setDue(n.dueDate??'');setReason(n.reason);setConfirmed(n.taxEligibilityConfirmed);setLines(initialLines(n));}},[note.data,ws.entityId]);
 useEffect(()=>{if(fresh&&original.data&&hydrate.current!==`${ws.entityId}:${original.data.id}`){hydrate.current=`${ws.entityId}:${original.data.id}`;setLines(original.data.lines.map(l=>({invoiceLineId:l.id,mode:'value',taxableAmount:''})));}},[original.data,fresh,ws.entityId]);
 const input=useMemo<NoteInput>(()=>({invoiceId:invoiceId??'',kind,taxTreatment:treatment,postingDate:date,...(kind==='debit'&&due?{dueDate:due}:{}),reason,taxEligibilityConfirmed:confirmed,lines:lines.filter(l=>l.mode==='quantity'?positive(l.qty):positive(l.taxableAmount))}),[invoiceId,kind,treatment,date,due,reason,confirmed,lines]);
 const body=JSON.stringify(input),bodyRef=useRef(body);bodyRef.current=body;
 const valid=!!invoiceId&&input.lines.length>0&&reason.trim().length>=5&&date.length===10&&(kind!=='credit'||treatment!=='gst'||confirmed);
 const [debounced,setDebounced]=useState(body);useEffect(()=>{const t=setTimeout(()=>setDebounced(body),300);return()=>clearTimeout(t);},[body]);
 const debouncedValid=(()=>{const x=JSON.parse(debounced) as NoteInput;return !!x.invoiceId&&x.lines.length>0&&x.reason.trim().length>=5&&(x.kind!=='credit'||x.taxTreatment!=='gst'||x.taxEligibilityConfirmed);})();
 const preview=useQuery({queryKey:['note-preview',ws.tenantId,ws.entityId,debounced],queryFn:()=>api<NotePreview>('/sales-notes/preview',{method:'POST',body:JSON.parse(debounced),scope:ws.scope}),enabled:editable&&canEdit&&debouncedValid&&!!ws.entityId,retry:false,staleTime:0});
 const invalidate=async()=>{for(const key of ['sales-note','sales-notes','invoice-balance','open-bills','outstanding','stock-balance','stock-ledger','credit','note-invoice'])await qc.invalidateQueries({queryKey:[key]});};
 const save=useMutation({mutationFn:async({submit,snapshot}:{submit:boolean;snapshot:string})=>{const payload=JSON.parse(snapshot) as NoteInput;let id=routeId;if(canEdit){const n=await api<CustomerNote>(id?`/sales-notes/${id}`:'/sales-notes',{method:id?'PUT':'POST',body:payload,scope:ws.scope});id=n.id;saved.current=snapshot;}if(!id)throw new Error('Save a complete draft first');if(submit)await api(`/sales-notes/${id}/submit`,{method:'POST',body:{},scope:ws.scope});return {id,submit,snapshot};},onSuccess:async x=>{setError('');rejected.current='';await invalidate();if(!routeId)router.replace(`/app/selling/notes/${x.id}`);},onError:(e,vars)=>{setError(e.message);rejected.current=vars.snapshot;}});
 useEffect(()=>{if(!routeId||!canEdit||!valid||save.isPending||body===saved.current||body===rejected.current||!hydrate.current)return;const t=setTimeout(()=>save.mutate({submit:false,snapshot:body}),1000);return()=>clearTimeout(t);},[routeId,canEdit,valid,body,save.isPending]);
 useEffect(()=>{if(note.data?.status==='draft'&&hydrate.current===`${ws.entityId}:${note.data.id}`&&!saved.current&&body===JSON.stringify({...input,lines:initialLines(note.data)}))saved.current=body;},[note.data,body,input,ws.entityId]);
 const cancel=useMutation({mutationFn:()=>api(`/sales-notes/${routeId}/cancel`,{method:'POST',body:{reason:cancelReason},scope:ws.scope}),onSuccess:async()=>{setCancelOpen(false);setError('');await invalidate();},onError:e=>setError(e.message)});
 const remove=useMutation({mutationFn:()=>api(`/sales-notes/${routeId}`,{method:'DELETE',scope:ws.scope}),onSuccess:async()=>{await invalidate();router.push('/app/selling/notes');},onError:e=>setError(e.message)});
 const updateLine=(id:string,patch:Partial<NoteLineInput>)=>setLines(old=>old.map(l=>l.invoiceLineId===id?{...l,...patch}:l));
 if(!fresh&&ws.can('selling.sales_note.read')&&note.isPending)return <EntityGate what="customer notes"><p>Loading customer note…</p></EntityGate>;
 if(!fresh&&note.error)return <EntityGate what="customer notes"><Alert tone="danger">{note.error.message}</Alert></EntityGate>;
 return <EntityGate what="customer notes"><div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-semibold">{kind==='credit'?'Credit note':'Debit note'} {note.data?.number??''}</h1><p className="text-muted text-sm">Original invoice {original.data?.number??note.data?.originalInvoiceNumber??'—'} · {original.data?.partyName??note.data?.customerName}</p>{note.data&&<Badge>{note.data.status}</Badge>}</div><div className="flex flex-wrap gap-2"><Link className={buttonClass('secondary','md')} href="/app/selling/notes">All notes</Link>{canEdit&&<Button variant="secondary" disabled={!valid||save.isPending} onClick={()=>save.mutate({submit:false,snapshot:body})}>Save draft</Button>}{editable&&ws.can('selling.sales_note.submit')&&<Button disabled={save.isPending||(!routeId&&!valid)} onClick={()=>save.mutate({submit:true,snapshot:body})}>Submit note</Button>}{note.data?.status==='draft'&&ws.can('selling.sales_note.update')&&<Button variant="ghost" disabled={remove.isPending||save.isPending} onClick={()=>remove.mutate()}>Delete draft</Button>}{note.data?.status==='submitted'&&<Link className={buttonClass('secondary','md')} href={`/app/selling/notes/${routeId}/print`}>Print / PDF</Link>}{note.data?.status==='submitted'&&ws.can('selling.sales_note.cancel')&&<Button variant="secondary" onClick={()=>setCancelOpen(true)}>Cancel note</Button>}</div></div>
 {!ws.can('selling.sales_note.read')&&<Alert>No permission to read notes.</Alert>}{(error||note.error||original.error)&&<Alert tone="danger">{error||note.error?.message||original.error?.message}</Alert>}{fresh&&!invoiceId&&<Alert>Choose a submitted sales invoice to create a note. <Link href="/app/selling/invoices">Open sales invoices</Link></Alert>}
 {invoiceId&&ws.can('selling.sales_invoice.read')&&<><Link className="text-accent" href={`/app/selling/invoices/${invoiceId}`}>View original invoice</Link><InvoiceBalance type="sales" id={invoiceId}/></>}
 {editable&&<><Card><div className="grid gap-4 p-5 md:grid-cols-3"><Field label="Note type"><Select aria-label="Note type" value={kind} disabled={!canEdit||save.isPending} onChange={e=>{setKind(e.target.value as 'credit'|'debit');setLines(old=>old.map(l=>({invoiceLineId:l.invoiceLineId,mode:'value',taxableAmount:''})));}}><option value="credit">Credit note</option><option value="debit">Debit note</option></Select></Field><Field label="Tax treatment"><Select aria-label="Tax treatment" value={treatment} disabled={!canEdit||save.isPending} onChange={e=>setTreatment(e.target.value as 'gst'|'commercial')}><option value="gst">GST-adjusting</option><option value="commercial">Commercial only (no GST reduction)</option></Select></Field><Field label="Note date"><Input aria-label="Note date" type="date" value={date} disabled={!canEdit||save.isPending} onChange={e=>setDate(e.target.value)}/></Field>{kind==='debit'&&<Field label="Due date"><Input aria-label="Due date" type="date" value={due} disabled={!canEdit||save.isPending} onChange={e=>setDue(e.target.value)}/></Field>}<Field label="Reason"><Input aria-label="Reason" value={reason} disabled={!canEdit||save.isPending} onChange={e=>setReason(e.target.value)}/></Field>{kind==='credit'&&treatment==='gst'&&<label className="flex items-start gap-2 text-sm"><input type="checkbox" aria-label="Confirm GST credit eligibility" checked={confirmed} disabled={!canEdit||save.isPending} onChange={e=>setConfirmed(e.target.checked)}/>Confirm this GST reduction is eligible, within its deadline, and the annual return has not been filed.</label>}</div></Card>
 <Card><div className="overflow-x-auto"><Table><thead><tr><Th>Original supply</Th><Th>Adjustment</Th><Th>Value / quantity</Th><Th>Physical return</Th></tr></thead><tbody>{lines.map(l=>{const source=original.data?.lines.find(x=>x.id===l.invoiceLineId),limit=preview.data?.limits.find(x=>x.invoiceLineId===l.invoiceLineId);return <tr key={l.invoiceLineId}><Td>{source?.itemName??note.data?.lines.find(x=>x.invoiceLineId===l.invoiceLineId)?.itemName}<p className="text-xs text-muted">Original: {source?.qty} × {source?.rate}{limit&&` · Value left ${limit.taxableValue}`}</p></Td><Td><Select aria-label="Adjustment mode" value={l.mode} disabled={!canEdit||save.isPending||kind==='debit'} onChange={e=>setLines(old=>old.map(x=>x.invoiceLineId===l.invoiceLineId?{invoiceLineId:x.invoiceLineId,mode:e.target.value as 'quantity'|'value',...(e.target.value==='quantity'?{qty:''}:{taxableAmount:''})}:x))}><option value="value">Value only</option><option value="quantity">Quantity credit</option></Select></Td><Td>{l.mode==='value'?<Input aria-label="Taxable adjustment" inputMode="decimal" value={l.taxableAmount??''} disabled={!canEdit||save.isPending} onChange={e=>updateLine(l.invoiceLineId,{taxableAmount:e.target.value})}/>:<Input aria-label="Credited quantity" inputMode="decimal" value={l.qty??''} disabled={!canEdit||save.isPending} onChange={e=>updateLine(l.invoiceLineId,{qty:e.target.value})}/>}</Td><Td>{kind==='credit'&&l.mode==='quantity'&&source?.isStockItem?<div className="space-y-2"><Input aria-label="Returned quantity" inputMode="decimal" value={l.returnQty??''} disabled={!canEdit||save.isPending} onChange={e=>{const value=e.target.value;setLines(old=>old.map(x=>x.invoiceLineId===l.invoiceLineId?{...x,returnQty:value||undefined,...(!value||!positive(value)?{warehouseId:undefined}:{})}:x));}}/><Select aria-label="Return warehouse" value={l.warehouseId??''} disabled={!canEdit||save.isPending} onChange={e=>updateLine(l.invoiceLineId,{warehouseId:e.target.value||undefined})}><option value="">Choose destination</option>{warehouses.data?.filter(w=>w.isActive).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</Select></div>:<span className="text-muted">No stock movement</span>}</Td></tr>;})}</tbody></Table></div></Card>
 {preview.error&&<Alert tone="danger">{preview.error.message}</Alert>}{preview.data&&debounced===body&&<Card><div className="grid gap-2 p-5 md:grid-cols-2"><p>Taxable value: {preview.data.currency} {preview.data.taxableValue}</p><p>CGST {preview.data.cgst} · SGST {preview.data.sgst} · IGST {preview.data.igst} · Cess {preview.data.cess}</p><p>Total: {preview.data.currency} {preview.data.grandTotal}</p><p>Original stock cost restored: INR {preview.data.returnValueInr}</p><p>Applied to original invoice: {preview.data.currency} {preview.data.applyAmount}</p><p>Unapplied customer credit: {preview.data.currency} {preview.data.unappliedCredit}</p></div></Card>}</>}
 {note.data&&(note.data.status!=='draft'||!canEdit)&&<Card><div className="space-y-2 p-5"><p>{note.data.taxTreatment==='commercial'?'Commercial-only adjustment':'GST-adjusting note'} · {note.data.reason}</p><p>Taxable value: {note.data.currency} {note.data.taxableValue}</p><p>CGST {note.data.cgst} · SGST {note.data.sgst} · IGST {note.data.igst} · Cess {note.data.cess}</p><p>Total: {note.data.currency} {note.data.grandTotal}</p>{note.data.creditBalance&&<p>{note.data.kind==='credit'?'Customer credit remaining':'Note bill remaining'}: {note.data.currency} {note.data.creditBalance.openAmount} · INR carrying {note.data.creditBalance.carryingInr}</p>}{note.data.stockEntryId&&<Link className="text-accent" href={`/app/inventory/entries/${note.data.stockEntryId}`}>Return stock movement</Link>}{note.data.voucherId&&<Link className="text-accent" href="/app/accounts/day-book">View posted journals</Link>}</div></Card>}
 {note.data?.status==='submitted'&&note.data.kind==='credit'&&note.data.creditBalance&&positive(note.data.creditBalance.openAmount)&&ws.can('accounts.settlement.submit')&&<NoteCreditApplication note={note.data} onChange={invalidate}/>}
 {note.data?.applications.map(a=><div className="flex flex-wrap items-center gap-3 text-sm" key={a.id}><span>Application {a.number} · {a.status}</span>{a.status==='submitted'&&ws.can('accounts.settlement.cancel')&&<Button variant="ghost" onClick={async()=>{const why=window.prompt('Reason to reverse this credit application');if(!why)return;try{await api(`/accounts/settlement-allocations/${a.id}/cancel`,{method:'POST',body:{reason:why},scope:ws.scope});await invalidate();}catch(e){setError(e instanceof Error?e.message:'Reversal failed');}}}>Reverse application</Button>}</div>)}
 {cancelOpen&&<div role="dialog" aria-modal="true" aria-label="Cancel note" className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><Card><div className="space-y-4 p-5"><h2 className="font-semibold">Cancel note</h2><Field label="Cancellation reason"><Input aria-label="Cancellation reason" value={cancelReason} onChange={e=>setCancelReason(e.target.value)}/></Field><p className="text-sm text-muted">This reverses the recorded stock, invoice application and journals. Later applications and used return stock must be reversed first.</p><div className="flex gap-2"><Button variant="secondary" onClick={()=>setCancelOpen(false)}>Keep note</Button><Button disabled={cancelReason.trim().length<5||cancel.isPending} onClick={()=>cancel.mutate()}>Confirm cancellation</Button></div></div></Card></div>}
 </div></EntityGate>;
}
function NoteCreditApplication({note,onChange}:{note:CustomerNote;onChange:()=>Promise<void>}){
 const ws=useWorkspace(),[billId,setBillId]=useState(''),[amount,setAmount]=useState(note.creditBalance?.openAmount??''),[date,setDate]=useState(today),[reason,setReason]=useState('Apply customer credit to invoice'),[preview,setPreview]=useState<{carryingInr:string;forexInr:string}|null>(null),[error,setError]=useState('');
 const bills=useQuery({queryKey:['note-target-bills',ws.tenantId,ws.entityId,note.id,note.creditBalance?.openAmount],queryFn:()=>api<NoteBill[]>(`/accounts/bills?partyId=${note.customerId}&side=receivable&currency=${note.currency}`,{scope:ws.scope}),staleTime:0,refetchOnMount:'always'});
 const body={creditNoteId:note.id,postingDate:date,reason,allocations:[{billId,amount}]},snapshot=JSON.stringify(body),approved=useRef('');
 useEffect(()=>{setPreview(null);approved.current='';},[snapshot]);
 const action=useMutation({mutationFn:async (submit:boolean)=>{const path=submit?'/accounts/settlement-allocations':'/accounts/settlement-allocations/preview';if(submit&&approved.current!==snapshot)throw new Error('Preview the current application first');return api<{carryingInr:string;forexInr:string}>(path,{method:'POST',body,scope:ws.scope});},onSuccess:async(data,submit)=>{setError('');if(submit){setPreview(null);approved.current='';await onChange();}else{approved.current=snapshot;setPreview(data);}},onError:e=>setError(e.message)});
 return <Card><div className="space-y-4 p-5"><h2 className="font-semibold">Apply remaining customer credit</h2><div className="grid gap-3 md:grid-cols-2"><Field label="Target bill"><Select aria-label="Target bill" value={billId} onChange={e=>setBillId(e.target.value)}><option value="">Choose an open invoice</option>{bills.data?.map(b=><option key={b.id} value={b.id}>{b.reference} · {b.currency} {b.openAmount}</option>)}</Select></Field><Field label="Amount to apply"><Input aria-label="Amount to apply" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></Field><Field label="Application date"><Input aria-label="Application date" type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="Application reason"><Input aria-label="Application reason" value={reason} onChange={e=>setReason(e.target.value)}/></Field></div>{error&&<Alert tone="danger">{error}</Alert>}{preview&&<p>Application carrying value: INR {preview.carryingInr} · FX loss/(gain): INR {preview.forexInr}</p>}<div className="flex gap-2"><Button variant="secondary" disabled={!billId||action.isPending} onClick={()=>action.mutate(false)}>Preview application</Button><Button disabled={!preview||action.isPending} onClick={()=>action.mutate(true)}>Apply credit</Button></div></div></Card>;
}
