'use client';
import {Alert,Button,Table,Td,Th} from '@factoryos/ui';
import {useQuery} from '@tanstack/react-query';
import {useParams} from 'next/navigation';
import Link from 'next/link';
import {api} from '@/lib/api';
import type {CustomerNote} from '@/lib/sales-notes';
import {useWorkspace} from './workspace';
import {EntityGate} from './entity-gate';
const money=(value:string)=>{const [whole,fraction='']=value.split('.');return `${whole}.${fraction.padEnd(2,'0').slice(0,2)}`;};
export function SalesNotePrint(){const ws=useWorkspace(),{id}=useParams<{id:string}>();const q=useQuery({queryKey:['sales-note',ws.tenantId,ws.entityId,id],queryFn:()=>api<CustomerNote>(`/sales-notes/${id}`,{scope:ws.scope}),enabled:!!ws.entityId&&ws.can('selling.sales_note.read'),staleTime:0});const n=q.data;return <EntityGate what="customer notes">{q.error&&<Alert tone="danger">{q.error.message}</Alert>}{n&&<><div className="mb-5 flex gap-3 print:hidden"><Link href={`/app/selling/notes/${id}`}>Back to note</Link><Button onClick={()=>window.print()}>Print / PDF</Button></div><article className="mx-auto max-w-[210mm] space-y-5 bg-surface p-8 text-sm print:p-0"><h1 className="text-2xl font-semibold">{n.kind==='credit'?'Credit note':'Debit note'}</h1>{n.status!=='submitted'&&<Alert>{n.status==='draft'?'DRAFT — not issued':'CANCELLED — retained for reference'}</Alert>}{n.taxTreatment==='commercial'&&<p className="font-semibold">Commercial-only note · No GST adjustment claimed</p>}<div className="grid grid-cols-2 gap-4"><div><strong>{n.entityName}</strong><p>GSTIN {n.ourGstin}</p><p>{n.ourAddress?.line1} {n.ourAddress?.city} {n.ourAddress?.pincode}</p></div><div><strong>{n.customerName}</strong><p>GSTIN {n.customerGstin??'Unregistered'}</p><p>{n.billingAddress?.line1} {n.billingAddress?.city} {n.billingAddress?.pincode}</p></div></div><dl className="grid grid-cols-2 gap-2"><div><dt>Note number</dt><dd>{n.number??'Draft'}</dd></div><div><dt>Note date</dt><dd>{n.postingDate}</dd></div><div><dt>Original invoice</dt><dd>{n.originalInvoiceNumber}</dd></div><div><dt>Original invoice date</dt><dd>{n.originalInvoiceDate}</dd></div><div><dt>Reason</dt><dd>{n.reason}</dd></div><div><dt>Currency / INR rate</dt><dd>{n.currency} / {n.exchangeRate}</dd></div></dl><Table><thead><tr><Th>Supply / HSN</Th><Th>Credited quantity</Th><Th>Taxable value</Th><Th>CGST</Th><Th>SGST</Th><Th>IGST</Th><Th>Cess</Th></tr></thead><tbody>{n.lines.map(l=><tr key={l.id}><Td>{l.description??l.itemName}<p>{l.hsnCode}</p></Td><Td>{l.qty}</Td><Td>{money(l.taxableValue)}</Td><Td>{money(l.cgst)}</Td><Td>{money(l.sgst)}</Td><Td>{money(l.igst)}</Td><Td>{money(l.cess)}</Td></tr>)}</tbody></Table><div className="text-right"><p>Taxable value {n.currency} {money(n.taxableValue)}</p><p>CGST {money(n.cgst)} · SGST {money(n.sgst)} · IGST {money(n.igst)} · Cess {money(n.cess)}</p><p className="text-lg font-semibold">Total {n.currency} {money(n.grandTotal)}</p></div>{n.lutArn&&<p>Supply meant for export under LUT without payment of IGST. LUT ARN {n.lutArn}.</p>}<p className="text-xs text-muted">This note adjusts the original invoice. Its physical return and customer-credit applications are recorded separately.</p></article></>}</EntityGate>;}
