'use client';
import {Alert,Button,Card,Input,Select} from '@factoryos/ui';
import {useMutation,useQuery} from '@tanstack/react-query';
import {useEffect,useRef,useState} from 'react';
import {api} from '@/lib/api';
import type {SupplierNote} from '@/lib/supplier-returns';
import {useWorkspace} from './workspace';
export function SupplierCreditApplication({note,onChange}:{note:SupplierNote;onChange:()=>Promise<void>}){
 const ws=useWorkspace(),[billId,setBill]=useState(''),[amount,setAmount]=useState(note.creditBalance?.openAmount??''),[date,setDate]=useState(()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata'}).format(new Date())),[reason,setReason]=useState('Apply remaining supplier credit'),[preview,setPreview]=useState<{carryingInr:string;forexInr:string}|null>(null),[error,setError]=useState(''),approved=useRef('');
 const q=useQuery({queryKey:['supplier-credit-bills',ws.tenantId,ws.entityId,note.id,note.creditBalance?.openAmount],queryFn:()=>api<{id:string;reference:string;openAmount:string}[]>(`/accounts/bills?partyId=${note.supplierId}&side=payable&currency=${note.currency}`,{scope:ws.scope}),staleTime:0});
 const body={supplierNoteId:note.id,postingDate:date,reason,allocations:[{billId,amount}]},snapshot=JSON.stringify(body);useEffect(()=>{setPreview(null);approved.current=''},[snapshot]);
 const action=useMutation({mutationFn:async(submit:boolean)=>{if(submit&&approved.current!==snapshot)throw new Error('Preview the current application first');return {...await api<{carryingInr:string;forexInr:string}>(`/accounts/settlement-allocations${submit?'':'/preview'}`,{method:'POST',body,scope:ws.scope}),inputSnapshot:snapshot}},onSuccess:async(data,submit)=>{setError('');if(submit){approved.current='';setPreview(null);await onChange()}else{approved.current=data.inputSnapshot;setPreview(data)}},onError:e=>setError(e.message)});
 return <Card><div className="space-y-4 p-5"><h2 className="font-semibold">Apply supplier credit</h2><div className="grid gap-3 md:grid-cols-2"><label>Target bill<Select aria-label="Target bill" value={billId} onChange={e=>setBill(e.target.value)}><option value="">Choose open supplier bill</option>{q.data?.map(b=><option key={b.id} value={b.id}>{b.reference} · {note.currency} {b.openAmount}</option>)}</Select></label><label>Amount to apply<Input aria-label="Amount to apply" value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal"/></label><label>Application date<Input aria-label="Application date" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Application reason<Input aria-label="Application reason" value={reason} onChange={e=>setReason(e.target.value)}/></label></div>{error&&<Alert tone="danger">{error}</Alert>}{preview&&approved.current===snapshot&&<p>Carrying value: INR {preview.carryingInr} · FX loss/(gain): INR {preview.forexInr}</p>}<div className="flex gap-2"><Button variant="secondary" disabled={!billId||action.isPending} onClick={()=>action.mutate(false)}>Preview application</Button><Button disabled={!preview||approved.current!==snapshot||action.isPending} onClick={()=>action.mutate(true)}>Apply credit</Button></div></div></Card>;
}
