// Object storage for certificates and attachments (decision 048): Cloudflare R2 through its S3 API in
// deployments, a local folder for development and tests only. Callers never see which driver runs.
import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { GetObjectCommand, PutObjectCommand, S3Client } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { Injectable, ServiceUnavailableException } from '@nestjs/common';

export const MAX_ATTACHMENT_BYTES = 25 * 1024 * 1024;
/** PDF, images, text/CSV and common CMM exports. */
export const ALLOWED_TYPES = new Set([
  'application/pdf',
  'image/png',
  'image/jpeg',
  'image/webp',
  'text/csv',
  'text/plain',
  'application/xml',
  'text/xml',
  'application/zip',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/octet-stream',
]);

export interface StoredObject {
  key: string;
  size: number;
  sha256: string;
}

type Driver = { kind: 's3'; client: S3Client; bucket: string } | { kind: 'local'; root: string } | { kind: 'disabled'; reason: string };

@Injectable()
export class StorageService {
  private readonly driver: Driver = configure();

  get enabled() {
    return this.driver.kind !== 'disabled';
  }

  get kind() {
    return this.driver.kind;
  }

  async put(key: string, body: Buffer, contentType: string): Promise<StoredObject> {
    const d = this.require();
    const sha256 = createHash('sha256').update(body).digest('hex');
    if (d.kind === 's3') await d.client.send(new PutObjectCommand({ Bucket: d.bucket, Key: key, Body: body, ContentType: contentType, ChecksumSHA256: Buffer.from(sha256, 'hex').toString('base64') }));
    else {
      const path = localPath(d.root, key);
      await mkdir(dirname(path), { recursive: true });
      await writeFile(path, body, { flag: 'wx' });
    }
    return { key, size: body.length, sha256 };
  }

  async get(key: string): Promise<Buffer> {
    const d = this.require();
    if (d.kind === 'local') return readFile(localPath(d.root, key));
    const out = await d.client.send(new GetObjectCommand({ Bucket: d.bucket, Key: key }));
    return Buffer.from(await out.Body!.transformToByteArray());
  }

  /** A five-minute download link (S3), or null when the API must stream the bytes itself (local). */
  async presign(key: string, fileName: string, contentType: string): Promise<string | null> {
    const d = this.require();
    if (d.kind === 'local') return null;
    const disposition = `attachment; filename*=UTF-8''${encodeURIComponent(fileName)}`;
    return getSignedUrl(d.client, new GetObjectCommand({ Bucket: d.bucket, Key: key, ResponseContentDisposition: disposition, ResponseContentType: contentType }), { expiresIn: 300 });
  }

  private require(): Exclude<Driver, { kind: 'disabled' }> {
    if (this.driver.kind === 'disabled') throw new ServiceUnavailableException(`File storage is not configured: ${this.driver.reason}`);
    return this.driver;
  }
}

function configure(): Driver {
  const kind = (process.env.STORAGE_DRIVER ?? '').trim();
  if (kind === 's3') {
    const missing = ['S3_ENDPOINT', 'S3_BUCKET', 'S3_ACCESS_KEY_ID', 'S3_SECRET_ACCESS_KEY'].filter((k) => !process.env[k]);
    if (missing.length) return { kind: 'disabled', reason: `set ${missing.join(', ')}` };
    return {
      kind: 's3',
      bucket: process.env.S3_BUCKET!,
      client: new S3Client({
        endpoint: process.env.S3_ENDPOINT,
        region: process.env.S3_REGION || 'auto',
        credentials: { accessKeyId: process.env.S3_ACCESS_KEY_ID!, secretAccessKey: process.env.S3_SECRET_ACCESS_KEY! },
        forcePathStyle: true,
      }),
    };
  }
  if (kind === 'local') {
    if (process.env.NODE_ENV === 'production') return { kind: 'disabled', reason: 'the local driver is for development only; use STORAGE_DRIVER=s3' };
    return { kind: 'local', root: resolve(process.env.STORAGE_LOCAL_DIR || '.storage') };
  }
  return { kind: 'disabled', reason: 'set STORAGE_DRIVER=s3 and the S3_* variables (Cloudflare R2)' };
}

/** Keys are generated by the API (tenant/entity/uuid), never by users; refuse anything that escapes the root. */
function localPath(root: string, key: string) {
  const path = resolve(join(root, key));
  if (!path.startsWith(root + '/')) throw new Error('Invalid object key');
  return path;
}
