import { describe, expect, it } from 'vitest';
import * as core from './index.js';
import type { CsvMapping, StatementParseInput } from './bank-reconciliation-types.js';
// Removing strict date/sign/precision parsing, quoted-field handling, occurrence ordinals or balance checks breaks these tests.
const mapping=(changes:Partial<CsvMapping>={}):CsvMapping=>({delimiter:',',skipRows:0,dateFormat:'DD/MM/YYYY',dateColumn:'Date',referenceColumn:'Ref',descriptionColumn:'Description',amount:{mode:'split',debitColumn:'Debit',creditColumn:'Credit'},decimalSeparator:'.',groupSeparator:null,order:'ascending',...changes});
const input=(csv:string,changes:Partial<StatementParseInput>={}):StatementParseInput=>({csv,startDate:'2026-10-01',endDate:'2026-10-31',openingBalance:'1000',closingBalance:'1090',...changes});
const parse=(csv:string,m:CsvMapping=mapping(),changes:Partial<StatementParseInput>={})=>{expect(core.parseBankStatement).toBeTypeOf('function');return core.parseBankStatement(input(csv,changes),m);};
const head='Date,Ref,Description,Debit,Credit\n';
describe('bank CSV normalization',()=>{
 it('retains explicitly mapped stable bank transaction identities',()=>{const r=parse('Date,Ref,Txn,Debit,Credit\n01/10/2026,R1,BANK-1,,90',mapping({descriptionColumn:undefined,transactionIdColumn:'Txn'}));expect(r.rows[0]).toMatchObject({transactionId:'BANK-1'});});
 it('csv_explicit_dates_and_signs',()=>{const r=parse(head+'01/10/2026,R1,Receipt,,100\n02/10/2026,F1,Fee,10,');expect(r.errors).toEqual([]);expect(r.rows.map(x=>[x.date,x.signedAmount])).toEqual([['2026-10-01','100.000000'],['2026-10-02','-10.000000']]);expect(r.netAmount).toBe('90.000000');});
 it('never guesses month-first dates',()=>{const r=parse(head+'10/01/2026,R1,Receipt,,90');expect(r.errors.some(x=>/interval/i.test(x.message))).toBe(true);});
 it('csv_quotes_bom_multiline',()=>{const r=parse('\uFEFF'+head+'01/10/2026,"R,1","line one\nline ""two""",,90\r\n');expect(r.errors).toEqual([]);expect(r.rows[0]).toMatchObject({reference:'R,1',description:'line one\nline "two"',ordinal:2});});
 it('reports malformed quotes and ambiguous headers',()=>{expect(parse(head+'01/10/2026,R1,"unfinished,,90').errors.length).toBeGreaterThan(0);expect(parse('Date,Date,Debit,Credit\n01/10/2026,01/10/2026,,90').errors.length).toBeGreaterThan(0);});
 it.each(['1e3','90.0000001','NaN','1,000'])('csv_precision_limits refuses %s',(amount)=>{expect(parse(head+`01/10/2026,R1,Receipt,,"${amount}"`).errors.length).toBeGreaterThan(0);});
 it('explicit decimal/group separators retain six places',()=>{const r=parse('Date;Ref;Amount\n01/10/2026;A;1.234,567890',mapping({delimiter:';',amount:{mode:'signed',column:'Amount',polarity:'credit-positive'},descriptionColumn:undefined,decimalSeparator:',',groupSeparator:'.'}),{closingBalance:'2234.567890'});expect(r.errors).toEqual([]);expect(r.rows[0]!.signedAmount).toBe('1234.567890');});
 it('signed debit-positive source reverses bank perspective',()=>{const r=parse('Date,Ref,Amount\n01/10/2026,F1,100',mapping({amount:{mode:'signed',column:'Amount',polarity:'debit-positive'},descriptionColumn:undefined}),{closingBalance:'900'});expect(r.errors).toEqual([]);expect(r.rows[0]!.signedAmount).toBe('-100.000000');});
 it('rejects two positive sides, zero and invalid calendar dates',()=>{for(const row of ['01/10/2026,R1,X,1,1','01/10/2026,R1,X,0,0','31/02/2026,R1,X,,90'])expect(parse(head+row).errors.length).toBeGreaterThan(0);});
 it('descending_running_balances use declared source order',()=>{const r=parse('Date,Ref,Debit,Credit,Balance\n02/10/2026,F1,10,,1090\n01/10/2026,R1,,100,1100',mapping({order:'descending',descriptionColumn:undefined,runningBalanceColumn:'Balance'}));expect(r.errors).toEqual([]);expect(r.rows.map(x=>x.ordinal)).toEqual([3,2]);expect(parse('Date,Ref,Debit,Credit,Balance\n01/10/2026,R1,,90,1089',mapping({descriptionColumn:undefined,runningBalanceColumn:'Balance'})).errors.length).toBeGreaterThan(0);});
 it('repeated_rows_keep_ordinals',()=>{const r=parse(head+'01/10/2026,R1,Identical,,45\n01/10/2026,R1,Identical,,45');expect(r.errors).toEqual([]);expect(r.rows.map(x=>x.ordinal)).toEqual([2,3]);expect(r.rows).toHaveLength(2);});
 it('quiet_period_and_overdraft',()=>{expect(parse(head,mapping(),{openingBalance:'-10',closingBalance:'-10'})).toMatchObject({rows:[],netAmount:'0.000000',errors:[]});expect(parse(head,mapping(),{openingBalance:'-10',closingBalance:'-9'}).errors.length).toBeGreaterThan(0);});
 it('balance-only rows require an explicit selector and are disclosed',()=>{const csv='Date,Ref,Type,Debit,Credit\n,,Opening,0,0\n01/10/2026,R1,Transaction,,90';const r=parse(csv,mapping({descriptionColumn:undefined,balanceRow:{column:'Type',value:'Opening'}}));expect(r.errors).toEqual([]);expect(r.ignoredOrdinals).toEqual([2]);expect(parse(csv,mapping({descriptionColumn:undefined})).errors.length).toBeGreaterThan(0);});
 it('refuses undeclared ordering and too many rows',()=>{expect(parse(head+'02/10/2026,R1,X,,45\n01/10/2026,R2,X,,45').errors.length).toBeGreaterThan(0);expect(parse(head+Array.from({length:10001},()=> '01/10/2026,R,X,,1').join('\n'),mapping(),{closingBalance:'11001'}).errors.some(x=>/10000/.test(x.message))).toBe(true);});
});
