import {z} from 'zod';
import {senderSchema,type EmailEnvelope} from './contracts.js';
export type EmailConfig={mode:'disabled';workerEnabled:false;sender?:EmailEnvelope['sender']}|{mode:'smtp';workerEnabled:boolean;smtp:{host:string;port:number;tls:'implicit-tls'|'starttls-required'|'plaintext-loopback-test';user?:string;password?:string};sender:EmailEnvelope['sender'];replyTo?:string;payloadKey:Buffer;authSecret:string;authBaseUrl:string;webOrigin:string};
const control=/[\x00-\x1f\x7f]/;
const schema=z.object({NODE_ENV:z.enum(['development','test','production']).default('development'),EMAIL_MODE:z.enum(['disabled','smtp']).default('disabled'),EMAIL_WORKER_ENABLED:z.enum(['true','false']).default('false'),SMTP_HOST:z.string().min(1).max(253).regex(/^(?:[A-Za-z0-9](?:[A-Za-z0-9.-]*[A-Za-z0-9])?|\[::1\]|::1)$/).optional(),SMTP_PORT:z.string().regex(/^\d+$/).transform(Number).pipe(z.number().int().min(1).max(65535)).optional(),SMTP_TLS:z.enum(['implicit-tls','starttls-required','plaintext-loopback-test']).optional(),SMTP_USER:z.string().min(1).max(200).refine(s=>!control.test(s)).optional(),SMTP_PASSWORD:z.string().min(1).refine(s=>!control.test(s)).optional(),EMAIL_FROM_ADDRESS:z.email().max(254).optional(),EMAIL_FROM_NAME:z.string().min(1).max(200).refine(s=>!control.test(s)).default('FactoryOS'),EMAIL_REPLY_TO:z.email().max(254).optional(),EMAIL_PAYLOAD_KEY_V1:z.string().optional(),BETTER_AUTH_SECRET:z.string().min(32).optional(),BETTER_AUTH_URL:z.url().optional(),WEB_ORIGIN:z.url().optional()});
export function loadEmailConfig(env:NodeJS.ProcessEnv):EmailConfig{
 const clean=Object.fromEntries(Object.entries(env).filter(([,v])=>v!==''&&v!==undefined));
 const parsed=schema.safeParse(clean);if(!parsed.success)throw new Error('Invalid email configuration');const c=parsed.data;
 if(c.EMAIL_MODE==='disabled'){if(c.EMAIL_WORKER_ENABLED==='true')throw new Error('Email worker cannot run in disabled mode');return {mode:'disabled',workerEnabled:false,...(c.EMAIL_FROM_ADDRESS?{sender:senderSchema.parse({address:c.EMAIL_FROM_ADDRESS,name:c.EMAIL_FROM_NAME})}:{})};}
 if(!c.SMTP_HOST||!c.SMTP_PORT||!c.SMTP_TLS||!c.EMAIL_FROM_ADDRESS||!c.EMAIL_PAYLOAD_KEY_V1||!c.BETTER_AUTH_SECRET||!c.BETTER_AUTH_URL||!c.WEB_ORIGIN)throw new Error('Incomplete email configuration');
 if(Boolean(c.SMTP_USER)!==Boolean(c.SMTP_PASSWORD))throw new Error('Email credentials must be complete');
 const payloadKey=Buffer.from(c.EMAIL_PAYLOAD_KEY_V1,'base64');if(payloadKey.length!==32||payloadKey.toString('base64')!==c.EMAIL_PAYLOAD_KEY_V1)throw new Error('Invalid email configuration encryption key');
 if(c.SMTP_TLS==='plaintext-loopback-test'&&(c.NODE_ENV==='production'||!['localhost','127.0.0.1','::1','[::1]'].includes(c.SMTP_HOST)))throw new Error('Plaintext email transport requires development/test loopback');
 for(const raw of [c.WEB_ORIGIN,c.BETTER_AUTH_URL]){const u=new URL(raw);if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.search||u.hash||(c.NODE_ENV==='production'&&u.protocol!=='https:'))throw new Error('Invalid email configuration public URL');}
 if(new URL(c.WEB_ORIGIN).pathname!=='/')throw new Error('Invalid email configuration web origin');
 return {mode:'smtp',workerEnabled:c.EMAIL_WORKER_ENABLED==='true',smtp:{host:c.SMTP_HOST,port:c.SMTP_PORT,tls:c.SMTP_TLS,...(c.SMTP_USER?{user:c.SMTP_USER,password:c.SMTP_PASSWORD!}:{})},sender:{address:c.EMAIL_FROM_ADDRESS,name:c.EMAIL_FROM_NAME},...(c.EMAIL_REPLY_TO?{replyTo:c.EMAIL_REPLY_TO}:{}),payloadKey,authSecret:c.BETTER_AUTH_SECRET,authBaseUrl:c.BETTER_AUTH_URL,webOrigin:c.WEB_ORIGIN};
}
