import {describe,it,expect} from 'vitest';
import {randomBytes} from 'node:crypto';
import * as mail from './index.js';
const key=Buffer.alloc(32,1);
const env={NODE_ENV:'test',EMAIL_MODE:'smtp',SMTP_HOST:'localhost',SMTP_PORT:'2525',SMTP_TLS:'plaintext-loopback-test',EMAIL_FROM_ADDRESS:'no-reply@example.com',EMAIL_FROM_NAME:'FactoryOS',EMAIL_PAYLOAD_KEY_V1:key.toString('base64'),BETTER_AUTH_SECRET:'test-only-secret-at-least-32-characters',BETTER_AUTH_URL:'https://factory.example',WEB_ORIGIN:'https://factory.example'};
const sender={address:'no-reply@example.com',name:'FactoryOS'};
const input={recipient:'person@example.com',sender,tenantName:'Azeonics <script> & नमस्ते',actionUrl:'https://factory.example/invite/fixture-token'};
const source={kind:'invitation' as const,tenantId:'11111111-1111-4111-8111-111111111111',invitationId:'22222222-2222-4222-8222-222222222222'};
describe('email configuration',()=>{
 it('disabled permits absent secrets and never enables a worker',()=>{expect(mail.loadEmailConfig({})).toEqual({mode:'disabled',workerEnabled:false});expect(()=>mail.loadEmailConfig({EMAIL_MODE:'disabled',EMAIL_WORKER_ENABLED:'true'})).toThrow(/worker/i);});
 it('configured loopback fixture loads key without exposing its value',()=>{const c=mail.loadEmailConfig(env);expect(c.mode).toBe('smtp');if(c.mode==='smtp'){expect(c.smtp.port).toBe(2525);expect(c.payloadKey.equals(key)).toBe(true);expect(c.workerEnabled).toBe(false);}});
 it('requires complete SMTP and auth configuration',()=>{for(const field of ['SMTP_HOST','SMTP_PORT','EMAIL_FROM_ADDRESS','EMAIL_PAYLOAD_KEY_V1','BETTER_AUTH_SECRET','WEB_ORIGIN']){expect(()=>mail.loadEmailConfig({...env,[field]:''})).toThrow(/configuration/i);}});
 it('partial credentials and invalid booleans refuse',()=>{expect(()=>mail.loadEmailConfig({...env,SMTP_USER:'secret-user'})).toThrow(/credentials/i);expect(()=>mail.loadEmailConfig({...env,EMAIL_WORKER_ENABLED:'yes'})).toThrow(/configuration/i);});
 it.each(['smtp.example.com','127.1','localhost.evil','0.0.0.0'])('plaintext refuses non-loopback host %s',host=>expect(()=>mail.loadEmailConfig({...env,SMTP_HOST:host})).toThrow(/loopback/i));
 it('plaintext is forbidden in production',()=>expect(()=>mail.loadEmailConfig({...env,NODE_ENV:'production'})).toThrow(/plaintext/i));
 it.each(['implicit-tls','starttls-required'])('allows verified production transport %s',tls=>expect(mail.loadEmailConfig({...env,NODE_ENV:'production',SMTP_HOST:'smtp.example.com',SMTP_TLS:tls})).toMatchObject({mode:'smtp'}));
 it('config error never includes supplied credentials',()=>{const secret='DO-NOT-LOG-THIS';try{mail.loadEmailConfig({...env,SMTP_PASSWORD:secret,EMAIL_PAYLOAD_KEY_V1:secret});throw new Error('should reject');}catch(e){expect(String(e)).not.toContain(secret);}});
 it('canonical key, bounded port and header control validation',()=>{for(const changes of [{EMAIL_PAYLOAD_KEY_V1:Buffer.alloc(31).toString('base64')},{SMTP_PORT:'65536'},{SMTP_PORT:'25.5'},{EMAIL_FROM_NAME:'Factory\r\nBcc: victim@example.com'},{SMTP_HOST:'smtp.example.com/path'}])expect(()=>mail.loadEmailConfig({...env,...changes})).toThrow(/configuration/i);});
});
describe('fixed templates and action URLs',()=>{
 it('Unicode remains intact and hostile HTML is escaped',()=>{const m=mail.renderEmail('member_invitation',input);expect(m.text).toContain('नमस्ते');expect(m.html).toContain('&lt;script&gt; &amp; नमस्ते');expect(m.html).not.toContain('<script>');expect(m.recipient).toBe(input.recipient);});
 it('reset and verification templates remain distinct',()=>{const reset=mail.renderEmail('password_reset',{...input,actionUrl:'https://factory.example/api/auth/reset-password/token'});const verify=mail.renderEmail('email_verification',{...input,actionUrl:'https://factory.example/api/auth/verify-email?token=fixture'});expect(reset.subject).toBe('Reset your FactoryOS password');expect(verify.subject).toBe('Verify your FactoryOS email');});
 it('header injection and unexpected recipient types refuse',()=>{expect(()=>mail.renderEmail('member_invitation',{...input,sender:{...sender,name:'X\nBcc: v@e.com'}})).toThrow(/Invalid email template/);expect(()=>mail.renderEmail('member_invitation',{...input,recipient:'person@example.com\r\nX: bad'})).toThrow(/Invalid email template/);});
 it('valid token-bearing links stay exact',()=>{for(const [purpose,url] of [['member_invitation',input.actionUrl],['password_reset','https://factory.example/api/auth/reset-password/TOKEN?callbackURL=https%3A%2F%2Ffactory.example%2Freset-password'],['email_verification','https://factory.example/api/auth/verify-email?token=JWT&callbackURL=https%3A%2F%2Ffactory.example%2Fverify-email']] as const){expect(mail.validateEmailActionUrl(purpose,url,env.BETTER_AUTH_URL,env.WEB_ORIGIN)).toBe(url);}});
 it.each(['https://evil.example/invite/token','javascript:alert(1)','https://factory.example/invite/token/more','https://person:secret@factory.example/invite/token'])('foreign or malformed invitation URL refuses %s',url=>expect(()=>mail.validateEmailActionUrl('member_invitation',url,env.BETTER_AUTH_URL,env.WEB_ORIGIN)).toThrow(/action URL/i));
 it('cross-purpose token paths and open redirects refuse',()=>{for(const url of ['https://factory.example/invite/token','https://factory.example/api/auth/reset-password/token?callbackURL=https%3A%2F%2Fevil.example%2Freset-password','https://factory.example/api/auth/reset-password/token?callbackURL=%2F%2Fevil.example'])expect(()=>mail.validateEmailActionUrl('password_reset',url,env.BETTER_AUTH_URL,env.WEB_ORIGIN)).toThrow(/action URL/i);});
});
describe('authenticated email envelopes',()=>{
 it('round-trips exactly and uses fresh IVs without revealing links',()=>{const m=mail.renderEmail('member_invitation',input),aad=mail.emailAad('member_invitation',source),cipher=mail.sealEmail(m,key,aad),other=mail.sealEmail(m,key,aad);expect(mail.openEmail(cipher,key,aad)).toEqual(m);expect(cipher.iv).not.toBe(other.iv);expect(JSON.stringify(cipher)).not.toContain('fixture-token');});
 it('wrong key, changed scope and altered ciphertext refuse',()=>{const aad=mail.emailAad('member_invitation',source),c=mail.sealEmail(mail.renderEmail('member_invitation',input),key,aad);expect(()=>mail.openEmail(c,randomBytes(32),aad)).toThrow(/envelope/i);expect(()=>mail.openEmail(c,key,mail.emailAad('owner_invitation',source))).toThrow(/envelope/i);expect(()=>mail.openEmail({...c,ciphertext:c.ciphertext.slice(0,-4)+'AAAA'},key,aad)).toThrow(/envelope/i);});
 it('rejects unknown key version and oversize payload in bytes',()=>{const aad=mail.emailAad('member_invitation',source),m=mail.renderEmail('member_invitation',input),c=mail.sealEmail(m,key,aad);expect(()=>mail.openEmail({...c,keyVersion:'v2'} as unknown as mail.CipherEnvelope,key,aad)).toThrow(/envelope/i);expect(()=>mail.sealEmail({...m,text:'अ'.repeat(24000)},key,aad)).toThrow(/64KiB/i);});
 it('scope identity cannot be swapped while retaining valid AAD',()=>{expect(mail.emailAad('member_invitation',source)).not.toBe(mail.emailAad('member_invitation',{...source,tenantId:'33333333-3333-4333-8333-333333333333'}));});
 it('outcomes retain only allowlisted redacted codes',()=>{expect(mail.redactEmailOutcome({kind:'permanent',code:'auth_refused',message:'fixture-token person@example.com'})).toEqual({kind:'permanent',code:'auth_refused'});expect(mail.redactEmailOutcome({kind:'unknown',code:'raw server reply including person@example.com'})).toEqual({kind:'unknown',code:'transport_unknown'});});
});
