import {closeEmailDatabase} from '../../api/scripts/email-test-helpers.mjs';
import {spawn} from 'node:child_process';import net from 'node:net';import {randomUUID,randomBytes} from 'node:crypto';import {mkdir,cp} from 'node:fs/promises';
import {createDb} from '../../../packages/db/dist/index.js';import {runMigrations} from '../../../packages/db/dist/migrate.js';import {loadEmailConfig,runEmailOnce,createSmtpTransport} from '../../../packages/email/dist/index.js';import {localSmtp} from '../../api/scripts/local-smtp.mjs';
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
export async function emailBrowserFixture(){
 const api=process.env.API??'http://localhost:4000',web=process.env.WEB_URL??'http://localhost:3000';
 for(const address of [api,web]){const target=new URL(address);if(target.protocol!=='http:'||!['localhost','127.0.0.1','[::1]'].includes(target.hostname))throw new Error('Email fixture requires loopback HTTP');const probe=net.createServer();await new Promise((resolve,reject)=>{probe.once('error',reject);probe.listen(Number(target.port)||80,'127.0.0.1',resolve);});await new Promise(resolve=>probe.close(resolve));}
 const admin=createDb(process.env.DATABASE_URL),databaseName='email_browser_'+randomUUID().replaceAll('-','');await admin.$client.query(`create database ${databaseName}`);const url=new URL(process.env.DATABASE_URL);url.pathname='/'+databaseName;await runMigrations(url.toString());const db=createDb(url.toString()),smtp=await localSmtp(),children=[];
 const env={...process.env,DATABASE_URL:url.toString(),NODE_ENV:'test',BETTER_AUTH_URL:web,WEB_ORIGIN:web,BETTER_AUTH_SECRET:'synthetic-browser-email-signing-secret-32',EMAIL_MODE:'smtp',EMAIL_WORKER_ENABLED:'true',SMTP_HOST:smtp.host,SMTP_PORT:String(smtp.port),SMTP_TLS:'plaintext-loopback-test',SMTP_USER:'',SMTP_PASSWORD:'',EMAIL_FROM_ADDRESS:'sender@example.test',EMAIL_FROM_NAME:'FactoryOS',EMAIL_REPLY_TO:'',EMAIL_PAYLOAD_KEY_V1:randomBytes(32).toString('base64'),EMAIL_RESET_MAX_PER_HOUR:'5',EMAIL_ORIGIN_MAX_PER_10_MIN:'1000',EMAIL_VERIFICATION_MAX_PER_HOUR:'5',EMAIL_VERIFICATION_COOLDOWN_SECONDS:'60',MIGRATE_ON_START:'false',BOOTSTRAP_SUPERADMIN_EMAIL:'',ALLOW_SELF_SERVE_TENANTS:'true'};
 const launch=(cwd,args,overrides)=>{const child=spawn(process.execPath,args,{cwd:new URL(cwd,import.meta.url).pathname,env:{...env,...overrides},stdio:['ignore','ignore','ignore']});children.push(child);child.on('error',()=>{});return child;};
 const close=async()=>{for(const child of children)if(child.exitCode===null)child.kill('SIGTERM');await delay(200);for(const child of children)if(child.exitCode===null)child.kill('SIGKILL');await smtp.close();await db.$client.end();await closeEmailDatabase(admin,databaseName);await admin.$client.end();};
 try{
  await mkdir(new URL('../.next/standalone/apps/web/.next',import.meta.url),{recursive:true});await cp(new URL('../.next/static',import.meta.url),new URL('../.next/standalone/apps/web/.next/static',import.meta.url),{recursive:true});
  launch('../../api/',['dist/main.js'],{PORT:new URL(api).port||'4000'});launch('../',['.next/standalone/apps/web/server.js'],{NODE_ENV:'production',API_INTERNAL_URL:api,PORT:new URL(web).port||'3000',HOSTNAME:'127.0.0.1'});
  for(const endpoint of [api+'/api/health',web+'/sign-in']){let ready=false;for(let i=0;i<450;i++){try{if((await fetch(endpoint)).status===200){ready=true;break;}}catch{}await delay(100);}if(!ready)throw new Error('Isolated email browser runtime did not become ready');}
  const config=loadEmailConfig(env),transport=createSmtpTransport(config);return {api,web,db,smtp,config,async drain(){for(let i=0;i<30&&await runEmailOnce(db,config,transport);i++){}},close};
 }catch(error){await close();throw error;}
}
