import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {chromium} from 'playwright';import {emailBrowserFixture} from './email-fixture.mjs';
const fixture=await emailBrowserFixture(),browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH??'/usr/bin/chromium'});
try{
 const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),email=randomUUID()+'@example.test';
 const response=await page.goto(fixture.web+'/forgot-password');assert.equal(response.status(),200);assert.equal(response.headers()['referrer-policy'],'no-referrer');await page.getByRole('heading',{name:'Forgot password'}).waitFor();
 const signup=await context.request.post(fixture.web+'/api/auth/sign-up/email',{data:{email,password:'Synthetic-password-123',name:'Email browser'},headers:{origin:fixture.web}});assert.equal(signup.status(),200);const user=(await signup.json()).user;
 await page.getByLabel('Email',{exact:true}).fill(email);await page.getByRole('button',{name:'Request reset link'}).click();await page.getByText('If this email exists in our system, check your email for the reset link.').waitFor();
 await fixture.drain();const delivery=(await fixture.db.$client.query("select id,source from email_delivery where purpose='password_reset' and source_user_id=$1",[user.id])).rows[0];assert.ok(delivery);const verification=(await fixture.db.$client.query('select identifier from verification where id=$1',[delivery.source.verificationId])).rows[0],token=verification.identifier.slice('reset-password:'.length);
 await page.goto(fixture.web+'/reset-password?token='+token+'&next=https://evil.example');await page.getByRole('heading',{name:'Reset password',exact:true}).waitFor();await page.getByLabel('New password',{exact:true}).fill('Replacement-password-123');await page.getByLabel('Confirm password',{exact:true}).fill('Replacement-password-123');await page.getByRole('button',{name:'Save new password'}).click();await page.getByText('Your password has been reset. Sign in with your new password.').waitFor();assert.equal(new URL(page.url()).searchParams.has('token'),false);assert.equal(await (await context.request.get(fixture.web+'/api/auth/get-session')).json(),null);assert.equal(new URL(page.url()).origin,fixture.web);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.goto(fixture.web+'/reset-password?token='+token);await page.getByLabel('New password',{exact:true}).fill('Another-password-123');await page.getByLabel('Confirm password',{exact:true}).fill('Another-password-123');await page.getByRole('button',{name:'Save new password'}).click();await page.getByRole('alert').waitFor();await page.goto(fixture.web+'/reset-password?error=INVALID_TOKEN');await page.getByText('This reset link is invalid or has expired. Request a new link.').waitFor();
 await page.goto(fixture.web+'/sign-in?next=%2F%2Fevil.example');assert.equal(await page.getByRole('button',{name:/Continue with (Google|Microsoft)/}).count(),0);await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill('Replacement-password-123');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL('**/onboarding');assert.equal(new URL(page.url()).origin,fixture.web);
 const plaintext=fixture.smtp.messages.map(message=>{const part=message.split('\r\n--').find(p=>p.includes('Content-Type: text/plain'))??message;const body=part.slice(part.indexOf('\r\n\r\n')+4);return part.includes('Content-Transfer-Encoding: base64')?Buffer.from(body.replace(/\s/g,''),'base64').toString():body.replace(/=\r?\n/g,'').replace(/=([A-F0-9]{2})/g,(_,hex)=>String.fromCharCode(parseInt(hex,16)));});const jwt=plaintext.map(s=>s.match(/https?:[^\s"<>]+\/api\/auth\/verify-email\?[^\s"<>]+/)).find(Boolean);assert.ok(jwt);const link=jwt[0].replaceAll('&amp;','&');await page.goto(link);await page.getByRole('heading',{name:'Email verification'}).waitFor();assert.equal((await fixture.db.$client.query('select email_verified from "user" where id=$1',[user.id])).rows[0].email_verified,true);assert.equal(new URL(page.url()).searchParams.has('token'),false);
 const status=await context.request.get(fixture.web+'/api/auth/get-session');assert.equal((await status.json()).user.emailVerified,true);await page.goto(fixture.web+'/verify-email?error=INVALID_TOKEN');await page.getByText('This verification link is invalid or has expired. Sign in to request a new link.').waitFor();
 const tenantResponse=await context.request.post(fixture.web+'/api/tenants',{data:{name:'Email scope tenant',entity:{legalName:'Email fixture company',shortName:'Email',code:'EM'}},headers:{origin:fixture.web}});assert.equal(tenantResponse.status(),201);const tenant=(await tenantResponse.json()).tenant;await fixture.db.$client.query('update "user" set email_verified=false where id=$1',[user.id]);await page.goto(fixture.web+'/app/settings/security');await page.getByRole('button',{name:'Send verification email'}).waitFor();
 let release,entered;const gate=new Promise(resolve=>{release=resolve;}),held=new Promise(resolve=>{entered=resolve;});await page.route('**/api/auth/send-verification-email',async route=>{const result=await route.fetch();entered();await gate;await route.fulfill({response:result});});await page.getByRole('button',{name:'Send verification email'}).click();await held;
 const secondContext=await browser.newContext(),secondEmail=randomUUID()+'@example.test',second=await secondContext.request.post(fixture.web+'/api/auth/sign-up/email',{data:{email:secondEmail,name:'Second account',password:'Synthetic-password-123'},headers:{origin:fixture.web}});assert.equal(second.status(),200);const secondUser=(await second.json()).user;await fixture.db.$client.query('insert into membership (tenant_id,user_id) values ($1,$2)',[tenant.id,secondUser.id]);await context.addCookies(await secondContext.cookies());await page.getByRole('button',{name:'Refresh verification status'}).click();await page.getByText(secondEmail,{exact:true}).waitFor();release();await page.waitForTimeout(100);assert.equal(await page.getByText('If verification is needed, check your email for a verification link.').count(),0);await secondContext.close();
 console.log('Email auth browser: mobile generic reset, consumed/invalid tokens, safe next, framework verification and no-referrer PASS');
}finally{await browser.close();await fixture.close();}
