import assert from 'node:assert/strict';
import {createHmac,createHash,randomUUID} from 'node:crypto';
import {chromium,request as standaloneRequest} from 'playwright';
import {passkeysBrowserFixture} from '../../api/scripts/passkeys-browser-api.mjs';
const f=await passkeysBrowserFixture(),browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH??'/usr/bin/chromium'});let cases=0;
async function test(name,fn){await fn();cases++;console.log('PASS '+name);}
function totp(secret){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits='';for(const c of secret.replace(/=+$/,''))bits+=alphabet.indexOf(c).toString(2).padStart(5,'0');const key=Buffer.from(bits.match(/.{8}/g).map(b=>parseInt(b,2))),counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const h=createHmac('sha1',key).update(counter).digest(),offset=h.at(-1)&15;return ((h.readUInt32BE(offset)&0x7fffffff)%1000000).toString().padStart(6,'0');}
try{
 const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();page.setDefaultTimeout(20000);
 const cdp=await context.newCDPSession(page);await cdp.send('WebAuthn.enable');const {authenticatorId}=await cdp.send('WebAuthn.addVirtualAuthenticator',{options:{protocol:'ctap2',transport:'usb',hasResidentKey:true,hasUserVerification:true,isUserVerified:true,automaticPresenceSimulation:true}});
 const signup=await context.request.post(f.web+'/api/auth/sign-up/email',{data:{name:'Passkey browser owner',email:'passkey-owner@example.test',password:'Synthetic-password-123'},headers:{origin:f.web}});assert.equal(signup.status(),200);const owner=(await signup.json()).user;
 const created=await context.request.post(f.web+'/api/tenants',{data:{name:'Passkey browser tenant',entity:{legalName:'Passkey synthetic entity',shortName:'Passkeys',code:'PK'}},headers:{origin:f.web}});assert.equal(created.status(),201);const tenant=(await created.json()).tenant;
 const wire=[];page.on('request',req=>{if(req.url().includes('/api/auth/passkey/'))wire.push(req);});let keyId,secret;
 await test('personal_passkeys_mobile_and_current_account: real virtual-authenticator enrollment with exact GET/POST nonce',async()=>{await page.goto(f.web+'/app/settings/security');await page.getByRole('heading',{name:'My security',exact:true}).waitFor();await page.getByRole('button',{name:'Add a passkey',exact:true}).click();await page.getByLabel('Passkey name',{exact:true}).fill('Personal phone');await page.getByLabel('Password for passkeys',{exact:true}).fill('Synthetic-password-123');const grantResponse=page.waitForResponse(r=>r.url().endsWith('/api/passkeys/actions')&&r.request().method()==='POST'),optionsResponse=page.waitForResponse(r=>r.url().includes('/passkey/generate-register-options'));await page.getByRole('button',{name:'Register passkey',exact:true}).click();const grant=await (await grantResponse).json(),optionReply=await optionsResponse,options=await optionReply.json();assert.equal(optionReply.status(),200,JSON.stringify({status:optionReply.status(),origin:await optionReply.request().headerValue('origin'),site:await optionReply.request().headerValue('sec-fetch-site'),referrerOrigin:new URL(await optionReply.request().headerValue('referer')??f.web).origin,error:options.code}));assert.equal(options.authenticatorSelection.residentKey,'required');assert.equal(options.authenticatorSelection.userVerification,'required');await page.getByRole('button',{name:'Remove Personal phone',exact:true}).waitFor();for(const suffix of ['generate-register-options','verify-registration']){const req=wire.find(req=>new URL(req.url()).pathname.endsWith(suffix));assert(req);assert.equal(await req.headerValue('x-factoryos-passkey-action'),grant.nonce);}const body=wire.find(req=>req.url().endsWith('/verify-registration')).postDataJSON();assert.deepEqual(Object.keys(body).sort(),['name','response']);const rows=(await f.db.$client.query('select id,user_id from passkey')).rows;assert.equal(rows.length,1);keyId=rows[0].id;assert.equal(rows[0].user_id,owner.id);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);});
 await test('rename markup stays inert and native key metadata remains private',async()=>{await page.getByRole('button',{name:'Rename Personal phone',exact:true}).click();await page.getByLabel('Passkey name',{exact:true}).fill('<img src=x onerror=alert(1)>');await page.getByLabel('Password for passkeys',{exact:true}).fill('Synthetic-password-123');await page.getByRole('button',{name:'Save passkey name',exact:true}).click();await page.getByRole('button',{name:'Remove <img src=x onerror=alert(1)>',exact:true}).waitFor();assert.equal(await page.locator('img[src="x"]').count(),0);const methods=await (await context.request.get(f.web+'/api/passkeys/methods')).json();for(const field of ['publicKey','credentialID','userHandle','passkeyCredentialId'])assert(!JSON.stringify(methods).includes('"'+field+'"'));await page.getByRole('button',{name:'Rename <img src=x onerror=alert(1)>',exact:true}).click();await page.getByLabel('Passkey name',{exact:true}).fill('Personal phone');await page.getByLabel('Password for passkeys',{exact:true}).fill('Synthetic-password-123');await page.getByRole('button',{name:'Save passkey name',exact:true}).click();await page.getByRole('button',{name:'Remove Personal phone',exact:true}).waitFor();});
 await test('real virtual-authenticator primary sign-in retains native TOTP and invitation return',async()=>{const enabled=await context.request.post(f.web+'/api/auth/two-factor/enable',{data:{password:'Synthetic-password-123'},headers:{origin:f.web}});assert.equal(enabled.status(),200);secret=new URL((await enabled.json()).totpURI).searchParams.get('secret');assert.equal((await context.request.post(f.web+'/api/auth/two-factor/verify-totp',{data:{code:totp(secret)},headers:{origin:f.web}})).status(),200);const invited=(await f.db.$client.query('insert into tenant(name,slug) values($1,$2) returning id',['Passkey invitation',randomUUID()])).rows[0].id,token=randomUUID(),role=(await f.db.$client.query("insert into role(tenant_id,name,permissions) values($1,'Passkey invited member','[]') returning id",[invited])).rows[0].id;await f.db.$client.query("insert into invitation(tenant_id,email,token_hash,roles,invited_by,expires_at) values($1,$2,$3,$4,$5,clock_timestamp()+interval '1 day')",[invited,owner.email,createHash('sha256').update(token).digest('hex'),JSON.stringify([{roleId:role,entityIds:null}]),owner.id]);await context.request.post(f.web+'/api/auth/sign-out',{data:{},headers:{origin:f.web}});await page.goto(f.web+'/sign-in?next='+encodeURIComponent('/invite/'+token));const optionsResponse=page.waitForResponse(r=>r.url().includes('/passkey/generate-authenticate-options'));await page.getByRole('button',{name:'Sign in with a passkey',exact:true}).click();assert.equal((await (await optionsResponse).json()).userVerification,'required');await page.waitForURL('**/sign-in/two-factor?**');assert.equal(await (await context.request.get(f.web+'/api/auth/get-session')).json(),null);await page.getByLabel('Authentication code').fill(totp(secret));await page.getByRole('button',{name:'Verify',exact:true}).click();await page.waitForURL('**/invite/'+token);await page.getByRole('button',{name:'Accept invitation',exact:true}).click();await page.waitForURL('**/app');assert.equal((await f.db.$client.query('select count(*)::int n from membership where tenant_id=$1 and user_id=$2',[invited,owner.id])).rows[0].n,1);await page.goto(f.web+'/app/settings/security');await page.getByRole('button',{name:'Remove Personal phone',exact:true}).waitFor();});
 await test('disabled configuration keeps owned management visible and hides enrollment/sign-in',async()=>{f.setEnabled(false);await page.reload();await page.getByRole('button',{name:'Remove Personal phone',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Add a passkey',exact:true}).count(),0);f.setEnabled(true);await page.reload();await page.getByRole('button',{name:'Add a passkey',exact:true}).waitFor();});
 await test('held action results cannot cross the current user or session',async()=>{const originalCookies=await context.cookies(),secondContext=await browser.newContext(),other=await secondContext.request.post(f.web+'/api/auth/sign-up/email',{data:{name:'Second passkey account',email:'second-passkey@example.test',password:'Synthetic-password-123'},headers:{origin:f.web}});assert.equal(other.status(),200);const second=(await other.json()).user;await f.db.$client.query('insert into membership(tenant_id,user_id) values($1,$2)',[tenant.id,second.id]);let entered,release;const held=new Promise(r=>entered=r),gate=new Promise(r=>release=r);await page.route('**/api/passkeys/actions',async route=>{const response=await route.fetch();entered();await gate;await route.fulfill({response}).catch(()=>{});});await page.getByRole('button',{name:'Rename Personal phone',exact:true}).click();await page.getByLabel('Passkey name',{exact:true}).fill('Never cross account');await page.getByLabel('Password for passkeys',{exact:true}).fill('Synthetic-password-123');await page.getByRole('button',{name:'Save passkey name',exact:true}).click();await held;await context.addCookies(await secondContext.cookies());await page.getByRole('button',{name:'Refresh verification status'}).click();await page.getByText(second.email,{exact:true}).waitFor();release();await page.waitForTimeout(150);assert.equal((await page.evaluate(()=>fetch('/api/auth/get-session',{credentials:'include'}).then(r=>r.json()))).user.id,second.id);assert.equal(await page.getByText('Never cross account',{exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Remove Personal phone',exact:true}).count(),0);assert.equal((await f.db.$client.query('select name from passkey where id=$1',[keyId])).rows[0].name,'Personal phone');await page.unroute('**/api/passkeys/actions');await context.addCookies(originalCookies);await page.getByRole('button',{name:'Refresh verification status'}).click();await page.getByRole('button',{name:'Remove Personal phone',exact:true}).waitFor();await secondContext.close();});
 await test('held list and enrollment ceremony responses cannot cross accounts',async()=>{
  const originalCookies=await context.cookies(),secondContext=await browser.newContext();
  await secondContext.request.post(f.web+'/api/auth/sign-in/email',{data:{email:'second-passkey@example.test',password:'Synthetic-password-123'},headers:{origin:f.web}});
  const second=(await (await secondContext.request.get(f.web+'/api/auth/get-session')).json()).user;
  for(const stage of ['list','ceremony']){
   const isolated=await standaloneRequest.newContext();let entered,release,heldResponse;
   const held=new Promise(r=>entered=r),gate=new Promise(r=>release=r),pattern=stage==='list'?'**/api/passkeys/methods':'**/api/auth/passkey/generate-register-options';
   await page.route(pattern,async route=>{const req=route.request(),response=await isolated.get(req.url(),{headers:{...await req.allHeaders(),origin:f.web}});heldResponse={stage,status:response.status(),origin:(await req.allHeaders()).origin,site:(await req.allHeaders())['sec-fetch-site'],referrerOrigin:new URL((await req.allHeaders()).referer??f.web).origin,body:await response.json()};entered();await gate;await route.fulfill({response}).catch(()=>{});});
   if(stage==='list')await page.reload({waitUntil:'domcontentloaded'});
   else{await page.getByRole('button',{name:'Add a passkey',exact:true}).click();await page.getByLabel('Passkey name',{exact:true}).fill('Never cross ceremony');await page.getByLabel('Password for passkeys',{exact:true}).fill('Synthetic-password-123');await page.getByRole('button',{name:'Register passkey',exact:true}).click();}
   await held;if(heldResponse.status!==200){release();assert.fail(JSON.stringify(heldResponse));}await context.addCookies(await secondContext.cookies());await page.getByRole('button',{name:'Refresh verification status'}).click();await page.getByText(second.email,{exact:true}).waitFor();release();await page.waitForTimeout(200);
   const current=await page.evaluate(()=>fetch('/api/auth/get-session',{credentials:'include'}).then(r=>r.json()));assert.equal(current.user.id,second.id);assert.equal(await page.getByRole('button',{name:'Remove Personal phone',exact:true}).count(),0);assert.equal(await page.getByText('Never cross ceremony',{exact:true}).count(),0);assert.equal((await f.db.$client.query('select count(*)::int n from passkey')).rows[0].n,1);
   await page.unroute(pattern);await isolated.dispose();await context.addCookies(originalCookies);await page.getByRole('button',{name:'Refresh verification status'}).click();await page.getByRole('button',{name:'Remove Personal phone',exact:true}).waitFor();
  }await secondContext.close();
 });
 await test('maximum passkey label fits a mobile viewport',async()=>{const longName='P'.repeat(80);await page.getByRole('button',{name:'Rename Personal phone',exact:true}).click();await page.getByLabel('Passkey name',{exact:true}).fill(longName);await page.getByLabel('Password for passkeys',{exact:true}).fill('Synthetic-password-123');await page.getByRole('button',{name:'Save passkey name',exact:true}).click();await page.getByRole('button',{name:'Remove '+longName,exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.getByRole('button',{name:'Rename '+longName,exact:true}).click();await page.getByLabel('Passkey name',{exact:true}).fill('Personal phone');await page.getByLabel('Password for passkeys',{exact:true}).fill('Synthetic-password-123');await page.getByRole('button',{name:'Save passkey name',exact:true}).click();await page.getByRole('button',{name:'Remove Personal phone',exact:true}).waitFor();});
 await test('last-key removal clears current passkey session and keeps native local password/TOTP recovery',async()=>{await page.getByRole('button',{name:'Remove Personal phone',exact:true}).click();await page.getByLabel('Password for passkeys',{exact:true}).fill('Synthetic-password-123');await page.getByRole('button',{name:'Remove this passkey',exact:true}).click();await page.waitForURL('**/sign-in');assert.equal(await (await context.request.get(f.web+'/api/auth/get-session')).json(),null);assert.equal((await f.db.$client.query('select count(*)::int n from passkey where user_id=$1',[owner.id])).rows[0].n,0);await page.getByLabel('Email',{exact:true}).fill(owner.email);await page.getByLabel('Password',{exact:true}).fill('Synthetic-password-123');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL('**/sign-in/two-factor**');await page.getByLabel('Authentication code').fill(totp(secret));await page.getByRole('button',{name:'Verify',exact:true}).click();await page.waitForURL('**/app');});
 await test('unsupported browser and dismissed authenticator leave password controls usable',async()=>{await context.request.post(f.web+'/api/auth/sign-out',{data:{},headers:{origin:f.web}});await page.goto(f.web+'/sign-in');await cdp.send('WebAuthn.removeVirtualAuthenticator',{authenticatorId});await page.getByRole('button',{name:'Sign in with a passkey',exact:true}).click();await page.getByRole('button',{name:'Cancel passkey request',exact:true}).click();await page.getByLabel('Password',{exact:true}).fill('Synthetic-password-123');assert.equal(await page.getByRole('button',{name:'Sign in',exact:true}).isEnabled(),true);const unsupported=await browser.newContext();await unsupported.addInitScript(()=>Object.defineProperty(window,'PublicKeyCredential',{value:undefined,configurable:true}));const other=await unsupported.newPage();await other.goto(f.web+'/sign-in');await other.getByRole('heading',{name:'Sign in',exact:true}).waitFor();assert.equal(await other.getByRole('button',{name:'Sign in with a passkey',exact:true}).count(),0);assert.equal(await other.getByLabel('Password',{exact:true}).count(),1);await unsupported.close();});
 console.log('Passkeys production mobile browser '+cases+' cases PASS; genuine native WebAuthn/MFA/ownership/recovery');
}finally{await browser.close();await f.close();}
