import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {fixture} from '../../api/scripts/sales-notes-test-helpers.mjs';
const {c,inv,input,customer,invoice}=await fixture('Customer notes browser');
const B=process.env.WEB_URL??'http://localhost:3000';
const bill=(await c.req('GET',`/accounts/bills?partyId=${customer.id}&side=receivable`)).find(b=>b.sourceId===inv.id);
const receipt=await c.req('POST','/accounts/settlements',{direction:'receipt',partyId:customer.id,postingDate:c.settings.cutoverDate,currency:'INR',exchangeRate:'1',accountId:c.account('bank'),amount:'70',allocations:[{billId:bill.id,amount:'70'}]},201);
await c.req('POST',`/accounts/settlements/${receipt.id}/submit`,{});
const target=await invoice('20');
const browser=await chromium.launch(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),ctx=await browser.newContext();
await ctx.addCookies(c.cookie.split('; ').map(cookie=>{const i=cookie.indexOf('=');return {name:cookie.slice(0,i),value:cookie.slice(i+1),url:B};}));
await ctx.addInitScript(({tenantId,entityId})=>{localStorage.setItem('fos.tenant',tenantId);localStorage.setItem(`fos.entity.${tenantId}`,entityId);},{tenantId:c.tenantId,entityId:c.entityId});
const page=await ctx.newPage(),errors=[];page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto(`${B}/app/selling/notes/new?invoiceId=${inv.id}`);
 await page.getByLabel('Reason').fill('Correct customer billing after review');
 await page.getByLabel('Taxable adjustment').first().fill('40');
 await page.getByLabel('Confirm GST credit eligibility').check();
 await page.getByText(/Applied to original invoice: INR 30\.000000/).waitFor();
 await page.getByRole('button',{name:'Submit note',exact:true}).click();
 await page.waitForURL('**/selling/notes/*');
 await page.getByText(/Customer credit remaining: INR 10\.000000/).waitFor();
 await page.getByLabel('Target bill').selectOption({label:`${target.number} · INR 20.000000`});
 await page.getByLabel('Amount to apply').fill('10');
 await page.getByRole('button',{name:'Preview application',exact:true}).click();
 await page.getByText(/Application carrying value: INR 10\.000000/).waitFor();
 await page.getByRole('button',{name:'Apply credit',exact:true}).click();
 await page.getByText(/Customer credit remaining: INR 0\.000000/).waitFor();
 const noteId=page.url().split('/').at(-1),note=await c.req('GET',`/sales-notes/${noteId}`);
 await page.goto(`${B}/app/selling/notes/${noteId}/print`);
 await page.getByText('Credit note',{exact:true}).waitFor();await page.getByText(inv.number,{exact:true}).waitFor();
 await c.req('POST',`/accounts/settlement-allocations/${note.applications[0].id}/cancel`,{reason:'Release application for browser reversal'},200);
 await page.goto(`${B}/app/selling/notes/${noteId}`);
 await page.getByRole('button',{name:'Cancel note',exact:true}).click();
 await page.getByRole('dialog').getByLabel('Cancellation reason').fill('Reverse browser credit note');
 await page.getByRole('dialog').getByRole('button',{name:'Confirm cancellation',exact:true}).click();
 await page.getByText(/Remaining bill balance: INR 30\.000000/).waitFor();
 await page.setViewportSize({width:390,height:844});
 assert.deepEqual(errors,[]);console.log('PASS customer note UI, application, print and exact reversal');
}catch(e){await page.screenshot({path:'/tmp/sales-notes-browser-failure.png',fullPage:true});throw e;}finally{await browser.close();}
