import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { Client, gstin } from '../../api/scripts/accounting-test-helpers.mjs';
const B = process.env.WEB_URL ?? 'http://localhost:3001';
const c = await new Client().init('Settlement browser');
const customer = await c.req('POST', '/parties', { code: 'CUS', name: 'Browser customer', isCustomer: true, gstTreatment: 'unregistered' }, 201);
await c.activate([{ ...c.line('debtors', '8000'), partyId: customer.id, billReference: 'BROWSER-USD' }, c.line('equity', '0', '8000')], [], [{ partyId: customer.id, reference: 'BROWSER-USD', side: 'debit', amount: '8000', currency: 'USD', exchangeRate: '80', originalAmount: '100' }]);
const browser = await chromium.launch(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {});
const context = await browser.newContext({ viewport: { width: 1400, height: 900 } });
await context.addCookies(c.cookie.split('; ').map(cookie => { const i = cookie.indexOf('='); return { name: cookie.slice(0,i), value: cookie.slice(i+1), url: B }; }));
await context.addInitScript(({ tenantId, entityId }) => { if (!localStorage.getItem('fos.tenant')) localStorage.setItem('fos.tenant', tenantId); if (!localStorage.getItem(`fos.entity.${tenantId}`)) localStorage.setItem(`fos.entity.${tenantId}`, entityId); }, { tenantId: c.tenantId, entityId: c.entityId });
const page = await context.newPage(), errors = [];
page.setDefaultTimeout(15000);
page.on('pageerror', e => errors.push(e.message));
const L = name => page.getByLabel(name, { exact: true });
try {
  await page.goto(`${B}/app/accounts/settlements/new`);
  await L('Party').selectOption(customer.id);
  await L('Currency').fill('USD');
  await L('Exchange rate').fill('83');
  await L('Cash / bank').selectOption(c.account('bank'));
  await L('Amount').fill('40');
  await L('Narration').fill('Browser partial foreign receipt');
  await L('Allocate BROWSER-USD').fill('40');
  await page.getByRole('button', { name: 'Preview posting', exact: true }).click();
  await page.getByTestId('settlement-forex').getByText('-120.000000', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Save draft', exact: true }).click();
  await page.waitForURL(/\/accounts\/settlements\/[0-9a-f-]{36}$/);
  await page.getByRole('button', { name: 'Submit settlement', exact: true }).click();
  await page.getByText('Submitted', { exact: true }).waitFor();
  const receiptId = page.url().split('/').at(-1);
  assert.equal((await c.req('GET', '/accounts/bills'))[0].openAmount, '60.000000');
  await page.goto(`${B}/app/accounts/settlements/new`);
  await L('Party').selectOption(customer.id);
  await L('Currency').fill('USD'); await L('Exchange rate').fill('83');
  await L('Cash / bank').selectOption(c.account('bank'));
  await L('Amount').fill('60'); await L('Narration').fill('Browser unapplied receipt');
  await page.getByRole('button', { name: 'Save draft', exact: true }).click();
  await page.waitForURL(/\/accounts\/settlements\/[0-9a-f-]{36}$/);
  await page.getByRole('button', { name: 'Submit settlement', exact: true }).click();
  await page.getByText('Submitted', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Allocate on-account money', exact: true }).click();
  await L('Allocation reason').fill('Browser allocation against remaining bill');
  await L('Allocate BROWSER-USD').fill('60');
  await page.getByRole('button', { name: 'Preview allocation', exact: true }).click();
  await page.getByTestId('allocation-forex').getByText('-180.000000', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Save allocation', exact: true }).click();
  await page.getByRole('button', { name: 'Submit allocation', exact: true }).click();
  await page.getByText('Allocation submitted', { exact: true }).waitFor();
  assert.equal((await c.req('GET', '/accounts/bills')).length, 0);
  await page.getByRole('button', { name: 'Cancel settlement', exact: true }).click();
  await L('Cancellation reason').fill('Must first reverse later allocation');
  await page.getByRole('button', { name: 'Confirm cancellation', exact: true }).click();
  await page.getByText(/Reverse later allocations/).waitFor();
  await page.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.getByRole('button', { name: 'Reverse allocation', exact: true }).click();
  await L('Cancellation reason').fill('Reopen browser allocation');
  await page.getByRole('button', { name: 'Confirm cancellation', exact: true }).click();
  await page.getByText('Allocation cancelled', { exact: true }).waitFor();
  await page.goto(`${B}/app/accounts/outstanding`);
  await page.getByRole('heading', { name: 'Outstanding & ageing', exact: true }).waitFor();
  await page.getByRole('row').filter({ hasText: 'BROWSER-USD' }).first().waitFor();
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export exact balances', exact: true }).click();
  assert.match((await download).suggestedFilename(), /outstanding.*json/);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.reload();
  await page.getByRole('heading', { name: 'Outstanding & ageing', exact: true }).waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 2), false, 'mobile page should contain its table overflow');
  await page.setViewportSize({ width: 1400, height: 900 });
  const supplier = await c.req('POST', '/parties', { code: 'SUP', name: 'Browser supplier', isSupplier: true, gstTreatment: 'unregistered' }, 201);
  await page.goto(`${B}/app/accounts/journals/new`);
  await L('Narration').fill('Browser payable bill');
  await L('Account 1').selectOption(c.account('creditors'));
  await L('Party 1').selectOption(supplier.id);
  await L('Credit 1').fill('100');
  await L('Bill treatment 1').selectOption('new');
  await L('Bill reference 1').fill('BROWSER-PAYABLE');
  await L('Account 2').selectOption(c.account('equity'));
  await L('Debit 2').fill('100');
  await page.getByRole('button', { name: 'Save draft', exact: true }).click();
  await page.waitForURL(/\/accounts\/journals\/[0-9a-f-]{36}$/);
  await page.getByRole('button', { name: 'Submit journal', exact: true }).click();
  await page.getByText('submitted', { exact: true }).waitFor();
  await page.goto(`${B}/app/accounts/settlements/new`);
  await L('Direction').selectOption('payment');
  await L('Party').selectOption(supplier.id);
  await L('Cash / bank').selectOption(c.account('bank'));
  await L('Amount').fill('40');
  await L('Narration').fill('Browser partial supplier payment');
  await L('Allocate BROWSER-PAYABLE').fill('40');
  await page.getByRole('button', { name: 'Save draft', exact: true }).click();
  await page.waitForURL(/\/accounts\/settlements\/[0-9a-f-]{36}$/);
  await page.getByRole('button', { name: 'Submit settlement', exact: true }).click();
  await page.getByText('Submitted', { exact: true }).waitFor();
  const paymentUrl = page.url();
  assert.equal((await c.req('GET', '/accounts/bills?side=payable'))[0].openAmount, '60.000000');
  await page.emulateMedia({ media: 'print' });
  assert.equal(await page.getByRole('button', { name: 'Print', exact: true }).isVisible(), false);
  await page.getByTestId('settlement-forex').waitFor();
  await page.emulateMedia({ media: 'screen' });
  const role = await c.req('POST', '/roles', { name: 'Settlement browser observer', permissions: ['accounts.settlement.read'] }, 201);
  const viewer = new Client(), email = `settlement-browser-${Date.now()}@example.com`;
  const invite = await c.req('POST', '/invitations', { email, roles: [{ roleId: role.id, entityIds: [c.entityId] }] }, 201);
  await viewer.req('POST', '/auth/sign-up/email', { name: 'Settlement observer', email, password: 'Sup3r-secret-pw' });
  await viewer.req('POST', '/invitations/accept', { token: invite.inviteUrl.split('/').at(-1) }, 201);
  const readonly = await browser.newContext();
  await readonly.addCookies(viewer.cookie.split('; ').map(cookie => { const i = cookie.indexOf('='); return { name: cookie.slice(0,i), value: cookie.slice(i+1), url: B }; }));
  await readonly.addInitScript(({ tenantId, entityId }) => { if (!localStorage.getItem('fos.tenant')) localStorage.setItem('fos.tenant', tenantId); if (!localStorage.getItem(`fos.entity.${tenantId}`)) localStorage.setItem(`fos.entity.${tenantId}`, entityId); }, { tenantId: c.tenantId, entityId: c.entityId });
  const vp = await readonly.newPage();
  await vp.goto(paymentUrl);
  await vp.getByText('Submitted', { exact: true }).waitFor();
  assert.equal(await vp.getByLabel('Amount', { exact: true }).isDisabled(), true);
  for (const name of ['Save draft', 'Submit settlement', 'Cancel settlement', 'Export settlement']) assert.equal(await vp.getByRole('button', { name, exact: true }).count(), 0);
  await readonly.close();
  const reg = await c.req('POST', `/entities/${c.entityId}/gst-registrations`, { gstin: gstin('27AAACA1234B1Z') }, 201);
  const uom = (await c.req('GET', '/uoms')).find(u => u.code === 'NOS');
  await c.req('POST', '/hsn-codes', { code: '9983', kind: 'sac', description: 'Browser services', gstRate: '0', effectiveFrom: '2025-04-01' }, 201);
  const item = await c.req('POST', '/items', { code: 'SVC', name: 'Browser service', type: 'service', stockUomId: uom.id, hsnCode: '9983' }, 201);
  for (const type of ['purchase', 'sales']) {
    const input = type === 'purchase' ? { supplierId: supplier.id, gstRegistrationId: reg.id, supplierInvoiceNo: 'BROWSER-SERVICE', supplierInvoiceDate: c.settings.cutoverDate, postingDate: c.settings.cutoverDate } : { customerId: customer.id, gstRegistrationId: reg.id, invoiceDate: c.settings.cutoverDate, placeOfSupplyStateCode: '27' };
    const invoice = await c.req('POST', `/${type}-invoices`, { ...input, lines: [{ itemId: item.id, qty: '1', rate: '100', gstRate: '0' }] }, 201);
    await c.req('POST', `/${type}-invoices/${invoice.id}/submit`, {}, 201);
    await page.goto(`${B}/app/${type === 'purchase' ? 'buying' : 'selling'}/invoices/${invoice.id}`);
    await page.getByText(/Remaining bill balance:.*INR 100\.000000/).waitFor();
    await page.getByRole('button', { name: 'Cancel invoice', exact: true }).click();
    await page.getByRole('dialog').getByRole('textbox').fill('Reverse browser service invoice');
    await page.getByRole('dialog').getByRole('button', { name: 'Cancel invoice', exact: true }).click();
    await page.getByText(/Remaining bill balance:.*INR 0\.000000/).waitFor();
  }
  await page.goto(paymentUrl);
  await c.req('POST', '/entities', { legalName: 'Other browser entity', shortName: 'Other browser', code: 'OTHER' }, 201);
  await page.reload();
  await page.getByText('Submitted', { exact: true }).waitFor();
  await page.locator('button[aria-haspopup="listbox"]').click();
  await page.getByRole('listbox').getByText('Other browser', { exact: true }).click();
  await page.getByText(/Settlement not found/).waitFor();
  assert.equal(await page.getByRole('button', { name: 'Cancel settlement', exact: true }).count(), 0);
  await page.goto(`${B}/app/accounts/settlements/new`);
  await page.getByText('Accounting inactive. Activate accounting before recording settlements.', { exact: true }).waitFor();
  assert.deepEqual(errors, []);
  console.log('PASS production receipt/payment, structured journal bill, foreign preview, on-account allocation/reversal, outstanding export, print, read-only and mobile', receiptId);
} catch (error) {
  await page.screenshot({ path: '/tmp/settlements-browser-failure.png', fullPage: true });
  throw error;
} finally { await browser.close(); }
