import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {createHmac,createHash,randomUUID} from 'node:crypto';
import {ssoBrowserFixture} from './sso-fixture.mjs';
const f=await ssoBrowserFixture(),browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH??'/usr/bin/chromium'});
function totp(secret){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits='';for(const char of secret.replace(/=+$/,''))bits+=alphabet.indexOf(char).toString(2).padStart(5,'0');const key=Buffer.from(bits.match(/.{8}/g).map(b=>parseInt(b,2))),counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const digest=createHmac('sha1',key).update(counter).digest(),offset=digest.at(-1)&15;return ((digest.readUInt32BE(offset)&0x7fffffff)%1000000).toString().padStart(6,'0');}
try{
 const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();page.setDefaultTimeout(15000);await f.routeProviders(page);
 await page.goto(f.web+'/sign-in');await page.getByRole('heading',{name:'Sign in',exact:true}).waitFor();await page.getByRole('button',{name:'Continue with Google'}).waitFor();assert.equal(await page.getByRole('button',{name:'Continue with Google'}).count(),1,'optional Google provider button');assert.equal(await page.getByRole('button',{name:'Continue with Microsoft'}).count(),1);
 assert.equal(await page.getByLabel('Password',{exact:true}).count(),1);await page.goto(f.web+'/sign-up');assert.equal(await page.getByRole('button',{name:'Continue with Google'}).count(),0);
 const signup=await context.request.post(f.web+'/api/auth/sign-up/email',{data:{name:'Local browser',email:'owner@example.test',password:'Synthetic-password-123'},headers:{origin:f.web}});assert.equal(signup.status(),200);const owner=(await signup.json()).user;await f.db.$client.query('update "user" set email_verified=true where id=$1',[owner.id]);
 const tenant=await context.request.post(f.web+'/api/tenants',{data:{name:'SSO browser tenant',entity:{legalName:'SSO synthetic entity',shortName:'SSO',code:'SS'}},headers:{origin:f.web}});assert.equal(tenant.status(),201);
 for(const provider of ['Google','Microsoft']){await page.goto(f.web+'/app/settings/security');await page.getByRole('heading',{name:'My security'}).waitFor();await page.getByRole('button',{name:'Connect '+provider,exact:true}).click();await page.getByLabel('Password for connected accounts').fill('Synthetic-password-123');await page.getByRole('button',{name:'Confirm connection',exact:true}).click();await page.waitForURL('**/app/settings/security');await page.getByRole('button',{name:'Disconnect '+provider,exact:true}).waitFor();}
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 const enabled=await context.request.post(f.web+'/api/auth/two-factor/enable',{data:{password:'Synthetic-password-123'},headers:{origin:f.web}});assert.equal(enabled.status(),200);const secret=new URL((await enabled.json()).totpURI).searchParams.get('secret');assert.equal((await context.request.post(f.web+'/api/auth/two-factor/verify-totp',{data:{code:totp(secret)},headers:{origin:f.web}})).status(),200);
 for(const provider of ['Google','Microsoft']){await context.request.post(f.web+'/api/auth/sign-out',{data:{},headers:{origin:f.web}});await page.goto(f.web+'/sign-in?next=%2Fapp%2Fsettings%2Fsecurity');await page.getByRole('button',{name:'Continue with '+provider}).click();await page.waitForURL('**/sign-in/two-factor?**');assert.equal(await (await context.request.get(f.web+'/api/auth/get-session')).json(),null);await page.getByLabel('Authentication code').fill(totp(secret));await page.getByRole('button',{name:'Verify',exact:true}).click();await page.waitForURL('**/app/settings/security');assert.equal((await (await context.request.get(f.web+'/api/auth/get-session')).json()).user.id,owner.id);}
 const inviteTenant=(await f.db.$client.query('insert into tenant(name,slug) values ($1,$2) returning id',['SSO invitation',randomUUID()])).rows[0].id,inviteToken=randomUUID(),inviteRole=(await f.db.$client.query("insert into role(tenant_id,name,permissions) values($1,'SSO invited member','[]') returning id",[inviteTenant])).rows[0].id;await f.db.$client.query("insert into invitation(tenant_id,email,token_hash,roles,invited_by,expires_at) values($1,$2,$3,$5,$4,clock_timestamp()+interval '1 day')",[inviteTenant,owner.email,createHash('sha256').update(inviteToken).digest('hex'),owner.id,JSON.stringify([{roleId:inviteRole,entityIds:null}])]);
 await context.request.post(f.web+'/api/auth/sign-out',{data:{},headers:{origin:f.web}});await page.goto(f.web+'/sign-in?next='+encodeURIComponent('/invite/'+inviteToken));await page.getByRole('button',{name:'Continue with Microsoft'}).click();await page.waitForURL('**/sign-in/two-factor?**');assert.equal((await f.db.$client.query('select count(*)::int n from membership where tenant_id=$1 and user_id=$2',[inviteTenant,owner.id])).rows[0].n,0);await page.getByLabel('Authentication code').fill(totp(secret));await page.getByRole('button',{name:'Verify',exact:true}).click();await page.waitForURL('**/invite/'+inviteToken);await page.getByRole('button',{name:'Accept invitation'}).click();await page.waitForURL('**/app');assert.equal((await f.db.$client.query('select count(*)::int n from membership where tenant_id=$1 and user_id=$2',[inviteTenant,owner.id])).rows[0].n,1);await page.goto(f.web+'/app/settings/security');
 await page.getByRole('button',{name:'Disconnect Google',exact:true}).click();await page.getByLabel('Password for connected accounts').fill('Synthetic-password-123');await page.getByRole('button',{name:'Confirm disconnection',exact:true}).click();await page.getByRole('button',{name:'Connect Google',exact:true}).waitFor();
 f.choice.email='wrong@example.test';await page.getByRole('button',{name:'Connect Google',exact:true}).click();await page.getByLabel('Password for connected accounts').fill('Synthetic-password-123');await page.getByRole('button',{name:'Confirm connection',exact:true}).click();await page.waitForURL('**/sso/error');await page.getByText('Could not complete sign-in or connection. Try again or use your password.').waitFor();assert.equal(new URL(page.url()).search,'');
 f.choice.denied=true;await page.goto(f.web+'/sign-in');await page.getByRole('button',{name:'Continue with Microsoft'}).click();await page.waitForURL('**/sso/error');assert.equal(await page.getByText('never-render-this').count(),0);
 const headers=await context.request.get(f.web+'/sso/error?error_description=canary');assert.equal(headers.headers()['referrer-policy'],'no-referrer');assert(headers.headers()['cache-control'].includes('no-store'));
 f.choice.denied=false;f.choice.email=owner.email;await page.goto(f.web+'/app/settings/security');f.beforeCallback=async()=>{await f.db.$client.query("update auth_sso_action set created_at=clock_timestamp()-interval '2 minutes',expires_at=clock_timestamp()-interval '1 minute' where user_id=$1 and consumed_at is null",[owner.id]);};await page.getByRole('button',{name:'Connect Google',exact:true}).click();await page.getByLabel('Password for connected accounts').fill('Synthetic-password-123');await page.getByRole('button',{name:'Confirm connection',exact:true}).click();await page.waitForURL('**/sso/error');f.beforeCallback=null;
 const ownerCookies=await context.cookies(),secondContext=await browser.newContext(),otherEmail='other-browser@example.test',otherSignup=await secondContext.request.post(f.web+'/api/auth/sign-up/email',{data:{name:'Other browser',email:otherEmail,password:'Synthetic-password-123'},headers:{origin:f.web}});assert.equal(otherSignup.status(),200);const other=(await otherSignup.json()).user;await f.db.$client.query('update "user" set email_verified=true where id=$1',[other.id]);await f.db.$client.query('insert into membership(tenant_id,user_id) values ($1,$2)',[inviteTenant,other.id]);
 let enter,release;const entered=new Promise(resolve=>enter=resolve),gate=new Promise(resolve=>release=resolve);f.beforeCallback=async()=>{enter();await gate;};await page.goto(f.web+'/app/settings/security');await page.getByRole('button',{name:'Connect Google',exact:true}).click();await page.getByLabel('Password for connected accounts').fill('Synthetic-password-123');await page.getByRole('button',{name:'Confirm connection',exact:true}).click();await entered;await context.addCookies(await secondContext.cookies());release();await page.waitForURL('**/sso/error');f.beforeCallback=null;assert.equal((await f.db.$client.query("select count(*)::int n from account where user_id=$1 and provider_id='google'",[other.id])).rows[0].n,0);
 await page.goto(f.web+'/app/settings/security');await page.getByText(otherEmail,{exact:true}).waitFor();let actionEnter,actionRelease;const actionEntered=new Promise(resolve=>actionEnter=resolve),actionGate=new Promise(resolve=>actionRelease=resolve);await page.route('**/api/sso/actions',async route=>{const result=await route.fetch();actionEnter();await actionGate;await route.fulfill({response:result});});await page.getByRole('button',{name:'Connect Google',exact:true}).click();await page.getByLabel('Password for connected accounts').fill('Synthetic-password-123');await page.getByRole('button',{name:'Confirm connection',exact:true}).click();await actionEntered;await context.addCookies(ownerCookies);await page.getByRole('button',{name:'Refresh verification status'}).click();await page.getByText(owner.email,{exact:true}).waitFor();actionRelease();await page.waitForTimeout(200);assert.equal(await page.getByLabel('Password for connected accounts').count(),0);assert.equal(new URL(page.url()).pathname,'/app/settings/security');await secondContext.close();
 console.log('SSO production mobile browser: both real callbacks/link/disconnect/TOTP, optional buttons, no signup, mismatched email, denial, safe returns and private landings PASS');
}finally{await browser.close();await f.close();}
