import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {Client} from '../../api/scripts/accounting-test-helpers.mjs';
import {fixture} from '../../api/scripts/supplier-returns-test-helpers.mjs';
const {c,inv,item,reg,date,supplier:sourceSupplier}=await fixture('Supplier notes browser');
const B=process.env.WEB_URL??'http://localhost:3000';
const browser=await chromium.launch(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),context=await browser.newContext();
await context.addCookies(c.cookie.split('; ').map(cookie=>{const i=cookie.indexOf('=');return {name:cookie.slice(0,i),value:cookie.slice(i+1),url:B};}));
await context.addInitScript(({tenantId,entityId})=>{localStorage.setItem('fos.tenant',tenantId);localStorage.setItem(`fos.entity.${tenantId}`,entityId);},{tenantId:c.tenantId,entityId:c.entityId});
const page=await context.newPage(),errors=[];page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
try {
 await page.goto(`${B}/app/buying/supplier-notes/new?invoiceId=${inv.id}`);
 await page.getByRole('heading',{name:'Supplier note',exact:true}).waitFor();
 await page.getByLabel('Supplier note number').fill('BROWSER-CN');
 await page.getByLabel('Reason',{exact:true}).fill('Supplier confirms billing correction');
 await page.getByLabel('Taxable adjustment').first().fill('40');
 await page.getByLabel('Confirm documented GST eligibility').check();
 await page.getByRole('button',{name:'Preview note',exact:true}).click();
 await page.getByText('Total: INR 47.20',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Submit note',exact:true}).click();
 await page.waitForURL('**/supplier-notes/*');
 await page.getByText(/Supplier credit remaining: INR 0\.000000/).waitFor();
 const id=page.url().split('/').at(-1);
 await c.req('PATCH',`/parties/${sourceSupplier.id}`,{name:'Supplier renamed after posting'});
 await page.goto(`${B}/app/buying/supplier-notes/${id}/print`);
 await page.getByText('Supplier credit note',{exact:true}).waitFor();await page.getByText('BROWSER-CN',{exact:true}).waitFor();await page.getByText(/Return supplier · GSTIN/).waitFor();assert.equal(await page.getByText(/Supplier renamed after posting/).count(),0);
 await page.goto(`${B}/app/settings/supplier-returns`);
 await page.getByLabel('Credit application').selectOption('manual');
 await page.getByRole('button',{name:'Save policies',exact:true}).click();await page.getByText('Policies saved',{exact:true}).waitFor();
 assert.equal((await c.req('GET','/buying/return-policy')).creditApplication,'manual');
 const input={invoiceId:inv.id,kind:'credit',taxTreatment:'commercial',supplierNoteNo:'READ-CN',supplierNoteDate:inv.postingDate,postingDate:inv.postingDate,reason:'Read only Finance approval',lines:[{invoiceLineId:inv.lines[0].id,mode:'value',taxableAmount:'10'}]};const draft=await c.req('POST','/buying/supplier-notes',input,201);
 const role=await c.req('POST','/roles',{name:'Supplier note approver',permissions:['buying.supplier_note.read','buying.supplier_note.submit']},201);const viewer=new Client(),email=`supplier-approver${Date.now()}@example.com`;const invite=await c.req('POST','/invitations',{email,roles:[{roleId:role.id,entityIds:[c.entityId]}]},201);await viewer.req('POST','/auth/sign-up/email',{name:'Supplier approver',email,password:'Sup3r-secret-pw'});await viewer.req('POST','/invitations/accept',{token:invite.inviteUrl.split('/').at(-1)},201);
 const readContext=await browser.newContext();await readContext.addCookies(viewer.cookie.split('; ').map(cookie=>{const i=cookie.indexOf('=');return {name:cookie.slice(0,i),value:cookie.slice(i+1),url:B}}));await readContext.addInitScript(({tenantId,entityId})=>{localStorage.setItem('fos.tenant',tenantId);localStorage.setItem(`fos.entity.${tenantId}`,entityId)},{tenantId:c.tenantId,entityId:c.entityId});const readPage=await readContext.newPage();await readPage.goto(`${B}/app/buying/supplier-notes/${draft.id}`);await readPage.getByText('Total: INR 10.000000',{exact:true}).waitFor();assert.equal(await readPage.getByRole('button',{name:'Save draft',exact:true}).count(),0);assert.equal(await readPage.getByLabel('Taxable adjustment').isDisabled(),true);await readPage.getByRole('button',{name:'Submit note',exact:true}).click();await readPage.getByText(/Supplier credit remaining: INR 10.000000/).waitFor();await readContext.close();
 await page.goto(`${B}/app/buying/supplier-notes/${draft.id}`);await page.getByLabel('Target bill').selectOption({index:1});const applicationResponse=page.waitForResponse(r=>r.url().endsWith('/accounts/settlement-allocations/preview'));await page.getByRole('button',{name:'Preview application',exact:true}).click();assert.equal((await applicationResponse).status(),200);await page.getByText('Carrying value: INR 10.000000 · FX loss/(gain): INR 0.000000',{exact:true}).waitFor();await page.getByRole('button',{name:'Apply credit',exact:true}).click();await page.getByText(/Supplier credit remaining: INR 0\.000000/).waitFor();
 await page.goto(`${B}/app/settings/supplier-returns`);
 await page.getByLabel('Credit application').selectOption('automatic');await page.getByRole('button',{name:'Save policies',exact:true}).click();await page.getByText('Policies saved',{exact:true}).waitFor();
 const supplier=await c.req('POST','/parties',{code:'BROWSER_FOREIGN',name:'Foreign supplier',isSupplier:true,gstTreatment:'overseas'},201);const foreignDraft=await c.req('POST','/purchase-invoices',{supplierId:supplier.id,gstRegistrationId:reg.id,supplierInvoiceNo:'BROWSER-USD',supplierInvoiceDate:date,postingDate:date,currency:'USD',exchangeRate:'80',lines:[{itemId:item.id,qty:'1',rate:'100',gstRate:'0'}]},201);await c.req('POST',`/purchase-invoices/${foreignDraft.id}/submit`,{},201);const foreign=await c.req('GET',`/purchase-invoices/${foreignDraft.id}`),bill=(await c.req('GET',`/accounts/bills?partyId=${supplier.id}&side=payable&currency=USD`)).find(x=>x.sourceId===foreign.id);const payment=await c.req('POST','/accounts/settlements',{direction:'payment',partyId:supplier.id,postingDate:date,currency:'USD',exchangeRate:'80',accountId:c.account('bank'),amount:'70',allocations:[{billId:bill.id,amount:'70'}]},201);await c.req('POST',`/accounts/settlements/${payment.id}/submit`,{},200);
 await page.goto(`${B}/app/buying/supplier-notes/new?invoiceId=${foreign.id}`);await page.getByLabel('Supplier note number').fill('FOREIGN-BROWSER');await page.getByLabel('Reason',{exact:true}).fill('Foreign supplier confirms adjustment');await page.getByLabel('Tax treatment').selectOption('commercial');await page.getByLabel('Taxable adjustment').fill('40');await page.getByRole('button',{name:'Preview note',exact:true}).click();await page.getByText('Total: USD 40.00',{exact:true}).waitFor();await page.getByRole('button',{name:'Submit note',exact:true}).click();await page.getByText(/Supplier credit remaining: USD 10\.000000 · INR carrying 800\.000000/).waitFor();
 await page.setViewportSize({width:390,height:844});assert.deepEqual(errors,[]);
 console.log('PASS supplier note editor, server preview, recognition, print, manual policies read-only Finance approval and foreign residual credit');
} catch(e){await page.screenshot({path:'/tmp/supplier-notes-browser-failure.png',fullPage:true});throw e;}finally{await browser.close();}
