import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {Client} from '../../api/scripts/accounting-test-helpers.mjs';
import {stockFixture} from '../../api/scripts/supplier-returns-test-helpers.mjs';
const {c,claim:baseClaim,inv,date,receipt}=await stockFixture('Supplier return browser');
const landed=await c.req('POST','/landed-costs',{postingDate:date,receiptIds:[receipt.id],charges:[{chargeType:'freight',amount:'200',basis:'value'}]},201);await c.req('POST',`/landed-costs/${landed.id}/submit`,{},201);
let claim=baseClaim;
const B=process.env.WEB_URL??'http://localhost:3000';
const browser=await chromium.launch(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),context=await browser.newContext();
await context.addCookies(c.cookie.split('; ').map(cookie=>{const i=cookie.indexOf('=');return {name:cookie.slice(0,i),value:cookie.slice(i+1),url:B}}));
await context.addInitScript(({tenantId,entityId})=>{localStorage.setItem('fos.tenant',tenantId);localStorage.setItem(`fos.entity.${tenantId}`,entityId)},{tenantId:c.tenantId,entityId:c.entityId});
async function rolePage(name,permissions){await new Promise(resolve=>setTimeout(resolve,11000)); // Respect the existing three-signup rolling limit.
const role=await c.req('POST','/roles',{name,permissions},201),viewer=new Client(),email=`supplier-${name.replaceAll(' ','')}-${Date.now()}@example.com`;const invite=await c.req('POST','/invitations',{email,roles:[{roleId:role.id,entityIds:[c.entityId]}]},201);await viewer.req('POST','/auth/sign-up/email',{name,email,password:'Sup3r-secret-pw'});await viewer.req('POST','/invitations/accept',{token:invite.inviteUrl.split('/').at(-1)},201);viewer.tenantId=c.tenantId;viewer.entityId=c.entityId;const ctx=await browser.newContext();await ctx.addCookies(viewer.cookie.split('; ').map(cookie=>{const i=cookie.indexOf('=');return {name:cookie.slice(0,i),value:cookie.slice(i+1),url:B}}));await ctx.addInitScript(({tenantId,entityId})=>{localStorage.setItem('fos.tenant',tenantId);localStorage.setItem(`fos.entity.${tenantId}`,entityId)},{tenantId:c.tenantId,entityId:c.entityId});const page=await ctx.newPage();page.setDefaultTimeout(15000);return {page,viewer};}
const errors=[];let page=await context.newPage();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
try{
 const buying=await rolePage('Buying claim preparer',['buying.return_claim.read','buying.return_claim.create','buying.return_claim.update','buying.return_claim.submit','buying.purchase_invoice.read']);page=buying.page;page.on('pageerror',e=>errors.push(e.message));await page.goto(`${B}/app/buying/return-claims/new?invoiceId=${inv.id}`);await page.getByLabel('Requested quantity').fill('4');await page.getByLabel('Requested taxable value').fill('240');await page.getByLabel('Claim reason').fill('Prepare rejected purchase material claim');await page.getByRole('button',{name:'Submit claim',exact:true}).click();await page.waitForURL(/return-claims\/[0-9a-f-]{36}$/);claim=await c.req('GET',`/buying/return-claims/${page.url().split('/').at(-1)}`);assert.equal(claim.approvedBy,null);
 const finance=await rolePage('Finance return approver',['buying.return_claim.read','buying.return_claim.approve','buying.return_policy.read','buying.return_policy.update']);page=finance.page;page.on('pageerror',e=>errors.push(e.message));await page.goto(`${B}/app/buying/return-claims/${claim.id}`);await page.getByLabel('Action reason').fill('Finance approves physical return claim');await page.getByRole('button',{name:'Approve claim',exact:true}).click();await page.getByText('Approved',{exact:true}).waitFor();
 const stores=await rolePage('Stores return operator',['buying.return_claim.read','buying.return_movement.read','buying.return_movement.create','inventory.warehouse.read']);
 await stores.viewer.req('POST',`/buying/return-claims/${claim.id}/approve`,{reason:'Stores cannot approve Finance claims'},403);
 page=stores.page;page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`${B}/app/buying/return-claims/${claim.id}`);await page.getByRole('heading',{name:'Purchase return claim',exact:true}).waitFor();
 await page.getByLabel('Action reason').fill('Dispatch pending supplier acceptance');await page.getByLabel('Action quantity').fill('4');
 const receipt=page.getByLabel('Original receipt');await receipt.locator('option').nth(1).waitFor({state:'attached'});await receipt.selectOption({index:1});
 await page.getByRole('button',{name:'Preview dispatch',exact:true}).click();await page.getByText('Dispatch carrying value: INR 320.000000',{exact:true}).waitFor();await page.getByRole('button',{name:'Dispatch goods',exact:true}).click();await page.getByRole('cell',{name:'320.000000',exact:true}).waitFor();
 const draft=await c.req('POST','/buying/supplier-notes',{invoiceId:inv.id,kind:'credit',taxTreatment:'commercial',supplierNoteNo:'PART-BROWSER',supplierNoteDate:date,postingDate:date,reason:'Partial supplier acceptance',lines:[{invoiceLineId:inv.lines[0].id,claimLineId:claim.lines[0].id,mode:'quantity',qty:'2',taxableAmount:'120'}]},201);await c.req('POST',`/buying/supplier-notes/${draft.id}/submit`,{},201);
 await page.reload();await page.getByRole('cell',{name:'160.000000',exact:true}).waitFor();
 page=finance.page;await page.reload();
 await page.getByLabel('Action reason').fill('Supplier rejects remaining goods');await page.getByLabel('Action quantity').fill('2');await page.getByLabel('Rejected taxable value').fill('120');await page.getByRole('button',{name:'Record supplier rejection',exact:true}).click();await page.getByText(/Suggested next action: keep open/).waitFor();
 page=stores.page;await page.reload();await page.getByLabel('Action reason').fill('Supplier returned rejected goods');await page.getByLabel('Action quantity').fill('2');
 await page.setViewportSize({width:390,height:844});await page.getByLabel('Original dispatch to resolve').selectOption({index:1});await page.getByLabel('Warehouse').selectOption({index:1});await page.getByRole('button',{name:'Confirm goods received back',exact:true}).click();await page.getByText(/receive back · 2/).waitFor();await page.getByRole('cell',{name:'0.000000',exact:true}).first().waitFor();
 await page.goto(`${B}/app/buying/return-claims/${claim.id}/print`);await page.getByText('Purchase return claim',{exact:true}).waitFor();await page.getByText(/not a supplier-issued tax credit note/).waitFor();await page.getByText(/Original invoice: GOODS-001/).waitFor();assert.deepEqual(errors,[]);
 console.log('PASS purchase return dispatch, partial acceptance, rejection, received-back, claim print and mobile');
}catch(e){await page.screenshot({path:'/tmp/supplier-returns-browser-failure.png',fullPage:true});throw e}finally{await browser.close()}
