'use client';
import {Alert,Button,Card,CardHeader,Field,Input} from '@factoryos/ui';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {useRouter} from 'next/navigation';
import {z} from 'zod';
import {currentPasskeyIdentity,enrollPasskey,notifyPasskeyAuthChanged,passkeyRequest,passkeySummarySchema,passkeySupported,samePasskeyIdentity,type PasskeySummary} from '@/lib/passkeys';
type Selection={kind:'register'}|{kind:'rename'|'remove';method:PasskeySummary};
export function PasskeyCard({user,sessionId}:{user:{id:string;email:string};sessionId:string}){
 const router=useRouter(),[methods,setMethods]=useState<PasskeySummary[]>([]),[enabled,setEnabled]=useState(false),[supported,setSupported]=useState(false),[selection,setSelection]=useState<Selection|null>(null),[name,setName]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState<string|null>(null),life=useRef<AbortController|null>(null),request=useRef<AbortController|null>(null);
 const expected={userId:user.id,sessionId};
 const current=async(signal?:AbortSignal)=>!life.current?.signal.aborted&&samePasskeyIdentity(expected,await currentPasskeyIdentity(signal));
 const refresh=async(signal?:AbortSignal)=>{const rows=z.array(passkeySummarySchema).max(20).parse(await passkeyRequest('/api/passkeys/methods',undefined,signal));if(await current(signal))setMethods(rows);};
 useEffect(()=>{const controller=new AbortController();life.current=controller;setSupported(passkeySupported());void Promise.all([passkeyRequest('/api/passkeys/availability',undefined,controller.signal),passkeyRequest('/api/passkeys/methods',undefined,controller.signal)]).then(async([available,rows])=>{const configuration=z.object({enabled:z.boolean(),rpName:z.literal('FactoryOS')}).strict().parse(available),owned=z.array(passkeySummarySchema).max(20).parse(rows);if(await current(controller.signal)){setEnabled(configuration.enabled);setMethods(owned);}}).catch(()=>{});return()=>{controller.abort();request.current?.abort();};},[user.id,sessionId]);
 const choose=(action:Selection)=>{setSelection(action);setName(action.kind==='register'?'Personal passkey':action.method.name);setPassword('');setNotice(null);};
 const submit=async(event:FormEvent)=>{event.preventDefault();if(!selection||request.current)return;const action=selection,controller=new AbortController(),proofPassword=password;request.current=controller;setPassword('');setBusy(true);setNotice(null);const stop=()=>controller.abort();life.current?.signal.addEventListener('abort',stop,{once:true});
  try{if(!await current(controller.signal))return;const proof=z.object({nonce:z.string().regex(/^[A-Za-z0-9_-]{43}$/),expiresAt:z.iso.datetime()}).strict().parse(await passkeyRequest('/api/passkeys/actions',{kind:action.kind,...(action.kind==='register'?{}:{targetId:action.method.id}),password:proofPassword},controller.signal));if(!await current(controller.signal))return;
   if(action.kind==='register')await enrollPasskey(name,proof.nonce,controller.signal);
   else if(action.kind==='rename')passkeySummarySchema.parse(await passkeyRequest('/api/passkeys/methods/'+encodeURIComponent(action.method.id)+'/rename',{nonce:proof.nonce,name},controller.signal));
   else{const removed=z.object({status:z.literal(true),reauthenticate:z.boolean()}).strict().parse(await passkeyRequest('/api/passkeys/methods/'+encodeURIComponent(action.method.id)+'/remove',{nonce:proof.nonce},controller.signal));if(removed.reauthenticate){if(!controller.signal.aborted){notifyPasskeyAuthChanged();router.replace('/sign-in');}return;}}
   if(await current(controller.signal)){setSelection(null);setNotice(action.kind==='register'?'Passkey added.':action.kind==='rename'?'Passkey name saved.':'Passkey removed.');await refresh(controller.signal);if(action.kind==='remove')notifyPasskeyAuthChanged();}
  }catch{if(!controller.signal.aborted&&await current(controller.signal).catch(()=>false))setNotice('Could not change this passkey. Sign in within five minutes and confirm your password, then try again.');}
  finally{life.current?.signal.removeEventListener('abort',stop);if(request.current===controller){request.current=null;if(!life.current?.signal.aborted)setBusy(false);}}
 };
 return <Card className="mb-6 max-w-2xl"><CardHeader title="Passkeys" description={`Personal sign-in methods for ${user.email}. Your password and verification code stay available.`}/><div className="space-y-4 px-5 py-5">{notice&&<Alert tone="info">{notice}</Alert>}<p className="text-[13px] text-muted">On a shared computer, use your own phone or security key. Sign in within five minutes and confirm your password to add, rename or remove a passkey.</p>{!enabled&&<p className="text-[13px] text-muted">New passkeys and passkey sign-in are unavailable. You can still rename or remove your saved methods.</p>}{enabled&&!supported&&<p className="text-[13px] text-muted">This browser cannot use passkeys. Your password remains available.</p>}{methods.map(method=><div key={method.id} className="flex flex-wrap items-center gap-3 rounded border border-line p-3"><div className="min-w-0 flex-1"><p className="break-words text-sm font-medium">{method.name}</p><p className="text-[12px] text-muted">Added {new Date(method.createdAt).toLocaleDateString('en-IN')}. {method.lastUsedAt?`Last used ${new Date(method.lastUsedAt).toLocaleDateString('en-IN')}.`:'Not used yet.'} {method.backedUp?'Backed up.':''}</p></div><Button variant="secondary" size="sm" disabled={busy} aria-label={`Rename ${method.name}`} onClick={()=>choose({kind:'rename',method})}>Rename</Button><Button variant="secondary" size="sm" disabled={busy} aria-label={`Remove ${method.name}`} onClick={()=>choose({kind:'remove',method})}>Remove</Button></div>)}{!methods.length&&<p className="text-sm text-muted">No saved passkeys.</p>}{enabled&&supported&&<Button variant="secondary" disabled={busy} onClick={()=>choose({kind:'register'})}>Add a passkey</Button>}{selection&&<form onSubmit={submit} className="space-y-3">{selection.kind!=='remove'&&<Field label="Passkey name">{p=><Input {...p} value={name} maxLength={80} onChange={e=>setName(e.target.value)} required/>}</Field>}{selection.kind==='remove'&&<p className="break-words text-sm">Remove {selection.method.name}? Sessions signed in with this passkey will end, including this session if it used this method. Your password and backup-code recovery remain available.</p>}<Field label="Password for passkeys">{p=><Input {...p} type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/>}</Field><div className="flex flex-wrap gap-3"><Button type="submit" loading={busy}>{selection.kind==='register'?'Register passkey':selection.kind==='rename'?'Save passkey name':'Remove this passkey'}</Button><Button type="button" variant="secondary" onClick={()=>{request.current?.abort();setSelection(null);setPassword('');setNotice(null);}}>{busy?'Cancel passkey request':'Cancel'}</Button></div></form>}<p className="text-[12px] text-muted">Lost a passkey? Sign in with your password and verification code, then remove it here. Resetting your password keeps your passkeys.</p></div></Card>;
}
