import {Inject,Injectable,BadRequestException,ConflictException,NotFoundException,ForbiddenException} from '@nestjs/common';
import {gstSandboxConnection,gstSandboxSnapshot as snap,gstSandboxOperation as op,gstSandboxEvent,auditEvent,salesInvoice,salesNote,stockEntry,gstRegistration,supplierReturnEffect,purchaseInvoiceLine,purchaseInvoice,type Database} from '@factoryos/db';
import {canonicalHash,validateSnapshot,type ProviderCommand,transportSchema,transportIssues} from '@factoryos/gsp';
import {and,eq,asc,desc,inArray,isNull,sql} from 'drizzle-orm';import type {z} from 'zod';
import {DB} from '../../common/tokens.js';import {AuditService} from '../../common/audit.service.js';import type {TenantRequestContext} from '../../common/access.js';import {lockAccounting,type Tx} from '../accounting/accounting-lock.js';
import {SandboxConnectionsService,scopeOf,scopeWhere} from './connections.service.js';import {SandboxSourceService} from './source-snapshot.service.js';import {preparationInput,enqueueInput,actionInput} from './contracts.js';
const requirePerm=(ctx:TenantRequestContext,p:string)=>{if(!ctx.tenant.permissions.has(p))throw new ForbiddenException('Permission required: '+p)};
@Injectable()
export class SandboxOperationsService{
 constructor(@Inject(DB)private readonly db:Database,private readonly connections:SandboxConnectionsService,private readonly source:SandboxSourceService,private readonly audit:AuditService){}
 private async run<T>(ctx:TenantRequestContext,fn:(tx:Tx)=>Promise<T>){return this.db.transaction(async tx=>{await lockAccounting(tx,scopeOf(ctx).entityId);return fn(tx)})}

 async registrations(ctx:TenantRequestContext){return this.db.select({id:gstRegistration.id,gstin:gstRegistration.gstin,tradeName:gstRegistration.tradeName,stateCode:gstRegistration.stateCode,address:gstRegistration.address}).from(gstRegistration).where(scopeWhere(gstRegistration,scopeOf(ctx)))}
 async sources(ctx:TenantRequestContext,kind:string,registrationId:string){const s=scopeOf(ctx);if(kind==='sales_invoice'){requirePerm(ctx,'selling.sales_invoice.read');return this.db.select({id:salesInvoice.id,number:salesInvoice.number}).from(salesInvoice).where(and(scopeWhere(salesInvoice,s),eq(salesInvoice.gstRegistrationId,registrationId),eq(salesInvoice.status,'submitted'))).limit(100)}if(kind==='sales_note'){requirePerm(ctx,'selling.sales_note.read');return this.db.select({id:salesNote.id,number:salesNote.number}).from(salesNote).where(and(scopeWhere(salesNote,s),eq(salesNote.gstRegistrationId,registrationId),eq(salesNote.taxTreatment,'gst'),eq(salesNote.status,'submitted'))).limit(100)}requirePerm(ctx,'buying.return_claim.read');return this.db.selectDistinct({id:stockEntry.id,number:stockEntry.number}).from(stockEntry).innerJoin(supplierReturnEffect,eq(supplierReturnEffect.stockEntryId,stockEntry.id)).innerJoin(purchaseInvoiceLine,eq(purchaseInvoiceLine.id,supplierReturnEffect.invoiceLineId)).innerJoin(purchaseInvoice,eq(purchaseInvoice.id,purchaseInvoiceLine.invoiceId)).where(and(scopeWhere(stockEntry,s),eq(stockEntry.purpose,'purchase_return'),eq(stockEntry.status,'submitted'),eq(purchaseInvoice.gstRegistrationId,registrationId))).limit(100)}
 async prepare(ctx:TenantRequestContext,input:z.infer<typeof preparationInput>){return this.run(ctx,async tx=>{const con=await this.connections.getIn(tx,ctx,input.connectionId);requirePerm(ctx,con.capability==='irn'?'compliance.sandbox_irn.create':ctx.tenant.permissions.has('compliance.sandbox_ewb.create')?'compliance.sandbox_ewb.create':'compliance.sandbox_partb.create');if(con.capability==='irn'&&input.sourceKind==='purchase_return')throw new BadRequestException('Purchase returns are EWB sources only');const snapshot=await this.source.prepareIn(tx,ctx,con.registrationId,input);if(input.transport&&con.capability!=='ewb')throw new BadRequestException('Transport belongs to EWB');const payload={snapshot,...(input.transport?{transport:input.transport}:{})},hash=canonicalHash(payload),s=scopeOf(ctx);const [row]=await tx.insert(snap).values({...s,registrationId:con.registrationId,sourceKind:input.sourceKind,sourceId:input.sourceId??null,documentType:snapshot.documentType,documentNumber:snapshot.number,fy:snapshot.fy,payload,hash,createdBy:ctx.user.id}).returning();await this.audit.record(ctx,{...s,action:'gst_sandbox.snapshot.prepare',targetType:'gst_sandbox_snapshot',targetId:row!.id,after:{hash,sourceKind:input.sourceKind}},tx);if(input.sourceKind==='sample'&&ctx.tenant.permissions.has('compliance.sandbox_valuation.approve'))await this.approveIn(tx,ctx,row!.id);return {id:row!.id,hash,payload,issues:validateSnapshot(snapshot)};})}
 private async approveIn(tx:Tx,ctx:TenantRequestContext,id:string){const s=scopeOf(ctx);await this.audit.record(ctx,{...s,action:'gst_sandbox.snapshot.approve',targetType:'gst_sandbox_snapshot',targetId:id,after:{approved:true}},tx)}
 async approve(ctx:TenantRequestContext,id:string){return this.run(ctx,async tx=>{const s=scopeOf(ctx);const [row]=await tx.select().from(snap).where(and(scopeWhere(snap,s),eq(snap.id,id)));if(!row)throw new NotFoundException('Snapshot not found');await this.approveIn(tx,ctx,id);return {id,approved:true}})}
 private async assertLive(tx:Tx,ctx:TenantRequestContext,row:typeof snap.$inferSelect){if(row.sourceKind==='sample')return;const t=row.sourceKind==='sales_invoice'?salesInvoice:row.sourceKind==='sales_note'?salesNote:stockEntry;const s=scopeOf(ctx);const [r]=await tx.select({status:t.status}).from(t).where(and(eq(t.id,row.sourceId!),eq(t.tenantId,s.tenantId),eq(t.entityId,s.entityId)));if(!r||r.status!=='submitted')throw new ConflictException('Source is no longer submitted')}
 async enqueue(ctx:TenantRequestContext,input:z.infer<typeof enqueueInput>){return this.run(ctx,async tx=>{const s=scopeOf(ctx),con=await this.connections.getIn(tx,ctx,input.connectionId);requirePerm(ctx,con.capability==='irn'?'compliance.sandbox_irn.submit':'compliance.sandbox_ewb.submit');if(con.provider!=='mock')throw new ConflictException('NIC protocol verification is blocked; use mock sandbox');const [sn]=await tx.select().from(snap).where(and(scopeWhere(snap,s),eq(snap.id,input.snapshotId),eq(snap.registrationId,con.registrationId)));if(!sn)throw new NotFoundException('Snapshot not found');if(con.capability==='irn'&&sn.sourceKind==='purchase_return')throw new BadRequestException('Purchase returns are EWB sources only');if(sn.hash!==input.hash)throw new ConflictException('Preview changed; prepare again');await this.assertLive(tx,ctx,sn);
 if(sn.sourceKind==='sample'){const [approved]=await tx.select({id:auditEvent.seq}).from(auditEvent).where(and(eq(auditEvent.tenantId,s.tenantId),eq(auditEvent.entityId,s.entityId),eq(auditEvent.targetId,sn.id),eq(auditEvent.action,'gst_sandbox.snapshot.approve'))).limit(1);if(!approved)throw new ConflictException('Finance must approve this sample snapshot')}
 const doc=sn.payload.snapshot as ProviderCommand['snapshot'];if(validateSnapshot(doc).length)throw new BadRequestException('Invalid stored snapshot');if(con.capability==='irn'&&doc.supplyType==='regular'&&!doc.buyer.gstin)throw new BadRequestException('B2C invoices are not IRN sources');let command:ProviderCommand={action:con.capability==='irn'?'irn.generate':'ewb.generate',snapshot:doc};if(con.capability==='ewb'){const transport=transportSchema.parse(sn.payload.transport);if(doc.lines.every(l=>l.isService))throw new BadRequestException('Services do not require EWB');if(transportIssues(transport).length)throw new BadRequestException(transportIssues(transport).join('; '));command={...command,transport};if(input.irnOperationId){const irn=await this.getIn(tx,ctx,input.irnOperationId);if(irn.status!=='succeeded'||irn.action!=='irn.generate'||irn.registrationId!==con.registrationId)throw new ConflictException('Confirmed matching IRN required');const evidence=irn.result?.evidence as {externalId?:string;documentHash?:string}|undefined;if(evidence?.documentHash!==canonicalHash(doc)||!evidence.externalId)throw new ConflictException('IRN document differs from EWB snapshot');command={...command,action:'ewb.from_irn',irn:evidence.externalId}}}
 const generationKey=canonicalHash({type:sn.documentType,number:sn.documentNumber,fy:sn.fy,family:con.capability}),hash=canonicalHash(command);const [existing]=await tx.select().from(op).where(and(scopeWhere(op,s),eq(op.registrationId,con.registrationId),eq(op.generationKey,generationKey)));if(existing){if(existing.commandHash!==hash)throw new ConflictException('Document identity already used with different payload');return existing}
 const [sameKey]=await tx.select().from(op).where(and(scopeWhere(op,s),eq(op.idempotencyKey,input.idempotencyKey)));if(sameKey)throw new ConflictException('Idempotency key belongs to another operation');const [r]=await tx.insert(op).values({...s,registrationId:con.registrationId,connectionId:con.id,snapshotId:sn.id,action:command.action,command:{...command},commandHash:hash,generationKey,idempotencyKey:input.idempotencyKey,connectionRevision:con.revision,provider:con.provider,scenario:con.scenario,createdBy:ctx.user.id}).returning();await this.eventIn(tx,ctx,r!,'queued');return r!;})}
 private async eventIn(tx:Tx,ctx:TenantRequestContext,r:typeof op.$inferSelect,kind:string,evidence:Record<string,unknown>={}){const s=scopeOf(ctx);await tx.insert(gstSandboxEvent).values({...s,registrationId:r.registrationId,operationId:r.id,kind,actorId:ctx.user.id,evidence});await this.audit.record(ctx,{...s,action:'gst_sandbox.operation.'+kind,targetType:'gst_sandbox_operation',targetId:r.id,after:{action:r.action,...evidence}},tx)}
 async getIn(tx:Tx,ctx:TenantRequestContext,id:string){const [r]=await tx.select().from(op).where(and(scopeWhere(op,scopeOf(ctx)),eq(op.id,id)));if(!r)throw new NotFoundException('Operation not found');return r}
 async list(ctx:TenantRequestContext){return this.db.select().from(op).where(scopeWhere(op,scopeOf(ctx))).orderBy(desc(op.createdAt)).limit(200)}
 async get(ctx:TenantRequestContext,id:string){return this.db.transaction(async tx=>{const r=await this.getIn(tx,ctx,id),s=scopeOf(ctx);const [snapshot]=await tx.select().from(snap).where(and(scopeWhere(snap,s),eq(snap.id,r.snapshotId)));const events=await tx.select().from(gstSandboxEvent).where(and(scopeWhere(gstSandboxEvent,s),eq(gstSandboxEvent.operationId,r.id))).orderBy(asc(gstSandboxEvent.createdAt));return {...r,snapshot,events}})}
 async action(ctx:TenantRequestContext,id:string,input:z.infer<typeof actionInput>){return this.run(ctx,async tx=>{const s=scopeOf(ctx);let parent=await this.getIn(tx,ctx,id);const lookup=input.action.endsWith('lookup');if(parent.detachedAt||(parent.parentId&&(!lookup||parent.status!=='unknown')))throw new ConflictException('Use live original generation operation or reconcile unknown child');const family=parent.action.startsWith('irn.')?'irn':'ewb';if(!input.action.startsWith(family+'.')||['irn.generate','ewb.generate','ewb.from_irn'].includes(input.action))throw new BadRequestException('Action must reference this original resource');const permission=input.action.endsWith('lookup')?`compliance.sandbox_${family}.update`:input.action.endsWith('cancel')?`compliance.sandbox_${family}.cancel`:input.action==='ewb.update_partb'?'compliance.sandbox_partb.update':'compliance.sandbox_extension.update';requirePerm(ctx,permission);
 if(lookup){for(let depth=0;depth<100;depth++){const [pending]=await tx.select().from(op).where(and(scopeWhere(op,s),eq(op.parentId,parent.id),inArray(op.status,['queued','sending','unknown']))).limit(1);if(!pending)break;if(pending.status!=='unknown')throw new ConflictException('Wait for current resource action');parent=pending;if(depth===99)throw new ConflictException('Recovery chain too deep')}}
 const command:ProviderCommand={action:input.action,...(!lookup?{mutationId:input.idempotencyKey}:{}),snapshot:parent.command.snapshot as ProviderCommand['snapshot'],...(input.reason?{reason:input.reason}:{}),...(input.transport?{transport:input.transport}:{}),...(parent.result?.evidence?{externalId:(parent.result.evidence as {externalId:string}).externalId}:typeof parent.command.externalId==='string'?{externalId:parent.command.externalId}:{})};const hash=canonicalHash(command);const [repeat]=await tx.select().from(op).where(and(scopeWhere(op,s),eq(op.idempotencyKey,input.idempotencyKey)));if(repeat){if(repeat.parentId!==parent.id||repeat.commandHash!==hash)throw new ConflictException('Idempotency key changed');return repeat}
 const [busy]=await tx.select().from(op).where(and(scopeWhere(op,s),eq(op.parentId,parent.id),inArray(op.status,['queued','sending','unknown']))).limit(1);if(busy)throw new ConflictException('Resolve current resource action first');if(input.action.endsWith('lookup')){if(!['unknown','succeeded','cancelled'].includes(parent.status))throw new ConflictException('Wait for attempt before lookup')}else{if(parent.status!=='succeeded')throw new ConflictException('Confirmed active resource required');if(input.action.endsWith('cancel')&&!input.reason)throw new BadRequestException('Cancellation reason required');if(!input.action.endsWith('cancel')&&!input.transport)throw new BadRequestException('Transport details required');if(input.transport&&transportIssues(input.transport).length)throw new BadRequestException(transportIssues(input.transport).join('; '))}
 const [r]=await tx.insert(op).values({...s,registrationId:parent.registrationId,connectionId:parent.connectionId,snapshotId:parent.snapshotId,action:input.action,parentId:parent.id,idempotencyKey:input.idempotencyKey,command:{...command},commandHash:hash,connectionRevision:parent.connectionRevision,provider:parent.provider,scenario:parent.scenario,createdBy:ctx.user.id}).returning();await this.eventIn(tx,ctx,r!,'queued',{parentId:parent.id});return r!;})}
 async detach(ctx:TenantRequestContext,id:string,reason:string){return this.run(ctx,async tx=>{const r=await this.getIn(tx,ctx,id);if(r.parentId||!['succeeded','cancelled','rejected'].includes(r.status))throw new ConflictException('Resolve uncertain/pending operation before detachment');const [busy]=await tx.select().from(op).where(and(scopeWhere(op,scopeOf(ctx)),eq(op.parentId,id),inArray(op.status,['queued','sending','unknown']))).limit(1);if(busy)throw new ConflictException('Resolve pending action first');await tx.update(op).set({detachedAt:new Date()}).where(eq(op.id,r.id));await this.eventIn(tx,ctx,r,'detached',{reason});return {id,detached:true}})}
}
