import {Injectable,BadRequestException,NotFoundException,ConflictException,ForbiddenException} from '@nestjs/common';
import {gstRegistration,legalEntity,party,item,uom,salesInvoice,salesInvoiceLine,salesNote,salesNoteLine,stockEntry,supplierReturnEffect,purchaseInvoice,purchaseInvoiceLine} from '@factoryos/db';
import {and,eq,asc,isNull} from 'drizzle-orm';import {Dec} from '@factoryos/core';
import {snapshotSchema,toInrSnapshot,validateSnapshot,proportionalInrAmount,type DocumentSnapshot} from '@factoryos/gsp';
import type {z} from 'zod';import type {TenantRequestContext} from '../../common/access.js';import type {Tx} from '../accounting/accounting-lock.js';
import {scopeOf} from './connections.service.js';import {preparationInput} from './contracts.js';
// Existing printed fields are authoritative; explicit preparation only fills missing values.
function capturedAddress(base:Partial<DocumentSnapshot['buyer']>,input:DocumentSnapshot['buyer']|undefined):DocumentSnapshot['buyer']{
 const result={...base};for(const key of ['name','gstin','stateCode','address','city','pincode'] as const){
  const value=base[key],provided=input?.[key];
  if(value!==undefined&&(key==='gstin'||value!=='')){if(provided!==undefined&&provided!==value)throw new BadRequestException('Cannot change authoritative source '+key)}
  else if(provided!==undefined)Object.assign(result,{[key]:provided});
 }
 return result as DocumentSnapshot['buyer'];
}
const fy=(date:string)=>{const y=+date.slice(0,4)-(+date.slice(5,7)<4?1:0);return `${String(y).slice(-2)}-${String(y+1).slice(-2)}`};
@Injectable()
export class SandboxSourceService{
 async prepareIn(tx:Tx,ctx:TenantRequestContext,registrationId:string,input:z.infer<typeof preparationInput>):Promise<DocumentSnapshot>{
 const s=scopeOf(ctx);const [reg]=await tx.select().from(gstRegistration).where(and(eq(gstRegistration.id,registrationId),eq(gstRegistration.tenantId,s.tenantId),eq(gstRegistration.entityId,s.entityId)));if(!reg)throw new NotFoundException('Registration not found');
 if(input.sourceKind==='sample'){if(!input.snapshot||input.snapshot.provenance.kind!=='sample'||input.snapshot.provenance.sourceId||input.sourceId)throw new BadRequestException('Provide an explicit sample snapshot without source ID');if(input.snapshot.seller.gstin!==reg.gstin)throw new BadRequestException('Sample seller must match selected registration');const issues=validateSnapshot(input.snapshot);if(issues.length)throw new BadRequestException({message:'Snapshot validation failed',issues});return toInrSnapshot(input.snapshot)}
 if(input.snapshot)throw new BadRequestException('Source documents derive financial components from stored evidence');if(!input.sourceId)throw new BadRequestException('Source ID required');
 const required=input.sourceKind==='sales_invoice'?'selling.sales_invoice.read':input.sourceKind==='sales_note'?'selling.sales_note.read':'buying.return_claim.read';if(!ctx.tenant.permissions.has(required))throw new ForbiddenException('Source read permission required');
 const [entity]=await tx.select().from(legalEntity).where(and(eq(legalEntity.id,s.entityId),eq(legalEntity.tenantId,s.tenantId)));
 let sellerBase:Partial<DocumentSnapshot['seller']>={name:reg.tradeName??entity!.legalName,gstin:reg.gstin,stateCode:reg.stateCode,address:reg.address?.line1??'',city:reg.address?.city??'',pincode:reg.address?.pincode??''};
 type Line=DocumentSnapshot['lines'][number];let lines:Line[]=[],number='',date='',currency='INR',rate='1',supplyType='regular',total='0',customerId='';let storedBuyer:Partial<DocumentSnapshot['buyer']>|undefined;
 const lineOf=async(l:{itemId:string;description?:string|null;hsnCode?:string|null;qty:string;taxableValue?:string|null;cgst?:string|null;sgst?:string|null;igst?:string|null;cess?:string|null}):Promise<Line>=>{const [it]=await tx.select({i:item,u:uom}).from(item).innerJoin(uom,eq(uom.id,item.stockUomId)).where(and(eq(item.id,l.itemId),eq(item.tenantId,s.tenantId)));if(!it)throw new NotFoundException('Source item unavailable');return {description:l.description??it.i.name,hsn:l.hsnCode??it.i.hsnCode??'',uqc:input.uqc[l.itemId]??it.u.code,isService:it.i.type==='service',qty:l.qty,taxable:l.taxableValue??'0',cgst:l.cgst??'0',sgst:l.sgst??'0',igst:l.igst??'0',cess:l.cess??'0'}};
 if(input.sourceKind==='sales_invoice'){
  const [inv]=await tx.select().from(salesInvoice).where(and(eq(salesInvoice.id,input.sourceId),eq(salesInvoice.tenantId,s.tenantId),eq(salesInvoice.entityId,s.entityId)));if(!inv)throw new NotFoundException('Sales invoice not found');if(inv.status!=='submitted'||inv.gstRegistrationId!==reg.id)throw new ConflictException('Choose submitted source in selected registration');number=inv.number!;date=inv.invoiceDate;currency=inv.currency;rate=inv.exchangeRate;supplyType=inv.supplyType;total=inv.grandTotal!;customerId=inv.customerId;storedBuyer={name:inv.customerName??'',gstin:inv.customerGstin,stateCode:inv.billingAddress?.stateCode??'',address:inv.billingAddress?.line1??'',city:inv.billingAddress?.city??'',pincode:inv.billingAddress?.pincode??''};for(const l of await tx.select().from(salesInvoiceLine).where(eq(salesInvoiceLine.invoiceId,inv.id)).orderBy(asc(salesInvoiceLine.lineNo)))lines.push(await lineOf(l));
 }else if(input.sourceKind==='sales_note'){
  const [n]=await tx.select().from(salesNote).where(and(eq(salesNote.id,input.sourceId),eq(salesNote.tenantId,s.tenantId),eq(salesNote.entityId,s.entityId)));if(!n)throw new NotFoundException('Sales note not found');if(n.status!=='submitted'||n.taxTreatment!=='gst'||n.gstRegistrationId!==reg.id)throw new ConflictException('Choose submitted outward GST note in selected registration');number=n.number!;date=n.postingDate;currency=n.currency;rate=n.exchangeRate;supplyType=n.supplyType;total=n.grandTotal;customerId=n.customerId;storedBuyer={name:n.customerName??'',gstin:n.customerGstin,stateCode:n.billingAddress?.stateCode??'',address:n.billingAddress?.line1??'',city:n.billingAddress?.city??'',pincode:n.billingAddress?.pincode??''};sellerBase={name:n.sellerName??'',gstin:n.sellerGstin??reg.gstin,stateCode:n.sellerAddress?.stateCode??reg.stateCode,address:n.sellerAddress?.line1??'',city:n.sellerAddress?.city??'',pincode:n.sellerAddress?.pincode??''};
  for(const l of await tx.select({l:salesNoteLine,original:salesInvoiceLine}).from(salesNoteLine).innerJoin(salesInvoiceLine,eq(salesInvoiceLine.id,salesNoteLine.invoiceLineId)).where(eq(salesNoteLine.noteId,n.id)).orderBy(asc(salesNoteLine.lineNo)))lines.push(await lineOf({...l.original,...l.l,itemId:l.original.itemId}));
 }else{
  const [entry]=await tx.select().from(stockEntry).where(and(eq(stockEntry.id,input.sourceId),eq(stockEntry.tenantId,s.tenantId),eq(stockEntry.entityId,s.entityId)));if(!entry)throw new NotFoundException('Purchase return dispatch not found');if(entry.status!=='submitted'||entry.purpose!=='purchase_return')throw new ConflictException('Choose actual submitted purchase-return dispatch');if(!ctx.tenant.permissions.has('compliance.sandbox_valuation.approve'))throw new ForbiddenException('Finance must review purchase-return statutory valuation');number=entry.number!;date=entry.postingDate;customerId=entry.partyId!;
  const effects=await tx.select({r:supplierReturnEffect,l:purchaseInvoiceLine,inv:purchaseInvoice}).from(supplierReturnEffect).innerJoin(purchaseInvoiceLine,eq(purchaseInvoiceLine.id,supplierReturnEffect.invoiceLineId)).innerJoin(purchaseInvoice,eq(purchaseInvoice.id,purchaseInvoiceLine.invoiceId)).where(and(eq(supplierReturnEffect.stockEntryId,entry.id),eq(supplierReturnEffect.tenantId,s.tenantId),eq(supplierReturnEffect.entityId,s.entityId),isNull(supplierReturnEffect.reversalOf)));
  if(!effects.length)throw new ConflictException('Original purchase evidence unavailable');for(const x of effects){if(x.inv.gstRegistrationId!==reg.id)throw new ConflictException('Purchase source differs from selected registration');const amounts=Object.fromEntries((['taxableValue','cgst','sgst','igst','cess'] as const).map(k=>[k,proportionalInrAmount(x.l[k]??'0',x.r.qty,x.l.qty,x.inv.exchangeRate)]));lines.push(await lineOf({...x.l,...amounts,qty:x.r.qty}))}total=lines.reduce((t,l)=>t.add(l.taxable).add(l.cgst).add(l.sgst).add(l.igst).add(l.cess),Dec.ZERO).toFixed(2);
 }
 const [buyerParty]=await tx.select().from(party).where(and(eq(party.id,customerId),eq(party.tenantId,s.tenantId)));if(!buyerParty)throw new NotFoundException('Source party unavailable');const address=buyerParty.addresses[0];const buyer=capturedAddress(storedBuyer??{name:buyerParty.name,gstin:buyerParty.gstin,stateCode:buyerParty.stateCode??'',address:address?.line1??'',city:address?.city??'',pincode:address?.pincode??''},input.buyerAddress),seller=capturedAddress(sellerBase,input.sellerAddress);
 let documentType:'INV'|'CRN'|'DBN'='INV';if(input.sourceKind==='sales_note'){const [n]=await tx.select().from(salesNote).where(eq(salesNote.id,input.sourceId));documentType=n!.kind==='credit'?'CRN':'DBN'}
 const candidate={documentType,number,date,fy:fy(date),supplyType,currency,exchangeRate:rate,seller,buyer,lines,total,provenance:{kind:input.sourceKind,sourceId:input.sourceId,reason:input.reason}};const issues=validateSnapshot(candidate);if(issues.length)throw new BadRequestException({message:'Source needs complete sandbox fields',issues});return toInrSnapshot(snapshotSchema.parse(candidate));
 }
}
