import { sql } from 'drizzle-orm';
import { check, date, foreignKey, integer, jsonb, numeric, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';
import { user } from './auth.js';
import { glAccount, glEntry, journalVoucher } from './accounting.js';
import { bankChargeDocument } from './bank-charges.js';
import { legalEntity, tenant } from './platform.js';
import { docStatus } from './inventory.js';
const money = (name: string) => numeric(name, { precision: 24, scale: 6 });
const identity = () => ({ id: uuid('id').primaryKey().defaultRandom(), tenantId: uuid('tenant_id').notNull().references(() => tenant.id), entityId: uuid('entity_id').notNull().references(() => legalEntity.id) });
const authored = () => ({ createdBy: text('created_by').notNull().references(() => user.id), createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow() });
export const bankReconciliationProfile = pgTable('bank_reconciliation_profile', {
 ...identity(), accountId: uuid('account_id').notNull(), currency: text('currency').notNull().default('INR'), maskedIdentifier: text('masked_identifier').notNull(), dateWindow: integer('date_window').notNull().default(7), ...authored(),
}, t => [uniqueIndex('br_profile_scope_uq').on(t.id,t.tenantId,t.entityId),uniqueIndex('br_profile_account_uq').on(t.entityId,t.accountId),
 foreignKey({name:'br_profile_entity_fk',columns:[t.entityId,t.tenantId],foreignColumns:[legalEntity.id,legalEntity.tenantId]}),
 foreignKey({name:'br_profile_account_fk',columns:[t.accountId,t.tenantId,t.entityId],foreignColumns:[glAccount.id,glAccount.tenantId,glAccount.entityId]}),
 check('br_profile_settings_ck',sql`${t.currency}='INR' and ${t.dateWindow} between 0 and 30`)]);
export const bankMappingRevision = pgTable('bank_mapping_revision', {
 ...identity(), profileId: uuid('profile_id').notNull(), revision:integer('revision').notNull(),mapping:jsonb('mapping').$type<Record<string,unknown>>().notNull(), ...authored(),
}, t => [uniqueIndex('bank_mapping_revision_scope_uq').on(t.id,t.tenantId,t.entityId,t.profileId),foreignKey({name:'bank_mapping_revision_profile_fk',columns:[t.profileId,t.tenantId,t.entityId],foreignColumns:[bankReconciliationProfile.id,bankReconciliationProfile.tenantId,bankReconciliationProfile.entityId]}),uniqueIndex('br_mapping_revision_uq').on(t.profileId,t.revision),check('br_mapping_revision_ck',sql`${t.revision}>0`)]);
export const bankReconciliationBaseline = pgTable('bank_reconciliation_baseline', {
 ...identity(), profileId: uuid('profile_id').notNull(), baselineDate:date('baseline_date').notNull(),bookBalance:money('book_balance').notNull(),bankBalance:money('bank_balance').notNull(),reference:text('reference').notNull(),evidence:jsonb('evidence').notNull(),previewHash:text('preview_hash').notNull(), ...authored(),
}, t => [uniqueIndex('bank_reconciliation_baseline_scope_uq').on(t.id,t.tenantId,t.entityId,t.profileId),foreignKey({name:'bank_reconciliation_baseline_profile_fk',columns:[t.profileId,t.tenantId,t.entityId],foreignColumns:[bankReconciliationProfile.id,bankReconciliationProfile.tenantId,bankReconciliationProfile.entityId]})]);
export const bankOpeningItem = pgTable('bank_opening_item', {
 ...identity(), profileId: uuid('profile_id').notNull(), baselineId:uuid('baseline_id').notNull(),glEntryId:uuid('gl_entry_id'),postingDate:date('posting_date').notNull(),signedAmount:money('signed_amount').notNull(),reference:text('reference').notNull(),reason:text('reason').notNull(),evidence:jsonb('evidence').notNull(), ...authored(),
}, t => [uniqueIndex('bank_opening_item_scope_uq').on(t.id,t.tenantId,t.entityId,t.profileId),foreignKey({name:'bank_opening_item_profile_fk',columns:[t.profileId,t.tenantId,t.entityId],foreignColumns:[bankReconciliationProfile.id,bankReconciliationProfile.tenantId,bankReconciliationProfile.entityId]}),foreignKey({name:'br_opening_baseline_fk',columns:[t.baselineId,t.tenantId,t.entityId,t.profileId],foreignColumns:[bankReconciliationBaseline.id,bankReconciliationBaseline.tenantId,bankReconciliationBaseline.entityId,bankReconciliationBaseline.profileId]}),foreignKey({name:'br_opening_gl_fk',columns:[t.glEntryId,t.tenantId,t.entityId],foreignColumns:[glEntry.id,glEntry.tenantId,glEntry.entityId]}),uniqueIndex('br_opening_gl_uq').on(t.baselineId,t.glEntryId),check('br_opening_amount_ck',sql`${t.signedAmount}<>0`)]);
export const bankStatementImport = pgTable('bank_statement_import', {
 ...identity(), profileId: uuid('profile_id').notNull(), mappingId:uuid('mapping_id').notNull(),status:docStatus('status').notNull().default('draft'),startDate:date('start_date').notNull(),endDate:date('end_date').notNull(),openingBalance:money('opening_balance').notNull(),closingBalance:money('closing_balance').notNull(),fileHash:text('file_hash').notNull(),rawCsv:text('raw_csv').notNull(),parsed:jsonb('parsed').notNull(),previewHash:text('preview_hash').notNull(),submittedAt:timestamp('submitted_at',{withTimezone:true}), ...authored(),
}, t => [uniqueIndex('bank_statement_import_scope_uq').on(t.id,t.tenantId,t.entityId,t.profileId),foreignKey({name:'bank_statement_import_profile_fk',columns:[t.profileId,t.tenantId,t.entityId],foreignColumns:[bankReconciliationProfile.id,bankReconciliationProfile.tenantId,bankReconciliationProfile.entityId]}),foreignKey({name:'br_import_mapping_fk',columns:[t.mappingId,t.tenantId,t.entityId,t.profileId],foreignColumns:[bankMappingRevision.id,bankMappingRevision.tenantId,bankMappingRevision.entityId,bankMappingRevision.profileId]}),uniqueIndex('br_import_file_uq').on(t.profileId,t.fileHash,t.mappingId,t.startDate,t.endDate,t.openingBalance,t.closingBalance),check('br_import_interval_ck',sql`${t.startDate}<=${t.endDate}`)]);
export const bankStatementMovement = pgTable('bank_statement_movement', {
 ...identity(), profileId: uuid('profile_id').notNull(), originalImportId:uuid('original_import_id').notNull(),ordinal:integer('ordinal').notNull(),transactionId:text('transaction_id'),transactionDate:date('transaction_date').notNull(),signedAmount:money('signed_amount').notNull(),reference:text('reference').notNull(),description:text('description').notNull(),signature:text('signature').notNull(),rawEvidence:jsonb('raw_evidence').notNull().default({}), ...authored(),
}, t => [uniqueIndex('bank_statement_movement_scope_uq').on(t.id,t.tenantId,t.entityId,t.profileId),foreignKey({name:'bank_statement_movement_profile_fk',columns:[t.profileId,t.tenantId,t.entityId],foreignColumns:[bankReconciliationProfile.id,bankReconciliationProfile.tenantId,bankReconciliationProfile.entityId]}),foreignKey({name:'br_movement_import_fk',columns:[t.originalImportId,t.tenantId,t.entityId,t.profileId],foreignColumns:[bankStatementImport.id,bankStatementImport.tenantId,bankStatementImport.entityId,bankStatementImport.profileId]}),uniqueIndex('br_movement_transaction_uq').on(t.profileId,t.transactionId),uniqueIndex('br_movement_ordinal_uq').on(t.originalImportId,t.ordinal),check('br_movement_ck',sql`${t.signedAmount}<>0 and ${t.ordinal}>0`)]);
export const bankStatementMembership = pgTable('bank_statement_membership', {
 ...identity(), profileId: uuid('profile_id').notNull(), importId:uuid('import_id').notNull(),movementId:uuid('movement_id').notNull(),ordinal:integer('ordinal').notNull(), ...authored(),
}, t => [uniqueIndex('bank_statement_membership_scope_uq').on(t.id,t.tenantId,t.entityId,t.profileId),foreignKey({name:'bank_statement_membership_profile_fk',columns:[t.profileId,t.tenantId,t.entityId],foreignColumns:[bankReconciliationProfile.id,bankReconciliationProfile.tenantId,bankReconciliationProfile.entityId]}),foreignKey({name:'br_membership_import_fk',columns:[t.importId,t.tenantId,t.entityId,t.profileId],foreignColumns:[bankStatementImport.id,bankStatementImport.tenantId,bankStatementImport.entityId,bankStatementImport.profileId]}),foreignKey({name:'br_membership_movement_fk',columns:[t.movementId,t.tenantId,t.entityId,t.profileId],foreignColumns:[bankStatementMovement.id,bankStatementMovement.tenantId,bankStatementMovement.entityId,bankStatementMovement.profileId]}),uniqueIndex('br_membership_ordinal_uq').on(t.importId,t.ordinal),uniqueIndex('br_membership_movement_uq').on(t.importId,t.movementId)]);
export const bankDuplicateDecision = pgTable('bank_duplicate_decision', {
 ...identity(), profileId: uuid('profile_id').notNull(), importId:uuid('import_id').notNull(),ordinal:integer('ordinal').notNull(),decision:text('decision').notNull(),movementId:uuid('movement_id'),reason:text('reason').notNull(),snapshot:jsonb('snapshot').notNull(), ...authored(),
}, t => [uniqueIndex('bank_duplicate_decision_scope_uq').on(t.id,t.tenantId,t.entityId,t.profileId),foreignKey({name:'bank_duplicate_decision_profile_fk',columns:[t.profileId,t.tenantId,t.entityId],foreignColumns:[bankReconciliationProfile.id,bankReconciliationProfile.tenantId,bankReconciliationProfile.entityId]}),foreignKey({name:'br_duplicate_import_fk',columns:[t.importId,t.tenantId,t.entityId,t.profileId],foreignColumns:[bankStatementImport.id,bankStatementImport.tenantId,bankStatementImport.entityId,bankStatementImport.profileId]}),foreignKey({name:'br_duplicate_movement_fk',columns:[t.movementId,t.tenantId,t.entityId,t.profileId],foreignColumns:[bankStatementMovement.id,bankStatementMovement.tenantId,bankStatementMovement.entityId,bankStatementMovement.profileId]}),uniqueIndex('br_duplicate_ordinal_uq').on(t.importId,t.ordinal),check('br_duplicate_decision_ck',sql`${t.decision} in ('link','distinct') and length(trim(${t.reason}))>0 and ((${t.decision}='link')=(${t.movementId} is not null))`)]);
export const bankMatchGroup = pgTable('bank_match_group', {
 ...identity(), profileId: uuid('profile_id').notNull(), kind:text('kind').notNull(),evidence:jsonb('evidence').notNull(),previewHash:text('preview_hash').notNull(),reason:text('reason'), ...authored(),
}, t => [uniqueIndex('bank_match_group_scope_uq').on(t.id,t.tenantId,t.entityId,t.profileId),foreignKey({name:'bank_match_group_profile_fk',columns:[t.profileId,t.tenantId,t.entityId],foreignColumns:[bankReconciliationProfile.id,bankReconciliationProfile.tenantId,bankReconciliationProfile.entityId]}),check('br_match_kind_ck',sql`${t.kind} in ('ordinary','net') and (${t.kind}<>'net' or length(trim(${t.reason}))>0)` )]);
export const bankMatchEdge = pgTable('bank_match_edge', {
 ...identity(), profileId: uuid('profile_id').notNull(), matchId:uuid('match_id').notNull(),movementId:uuid('movement_id').notNull(),glEntryId:uuid('gl_entry_id'),openingItemId:uuid('opening_item_id'),amount:money('amount').notNull(),effectiveDate:date('effective_date').notNull(),snapshot:jsonb('snapshot').notNull(), ...authored(),
}, t => [uniqueIndex('bank_match_edge_scope_uq').on(t.id,t.tenantId,t.entityId,t.profileId),foreignKey({name:'bank_match_edge_profile_fk',columns:[t.profileId,t.tenantId,t.entityId],foreignColumns:[bankReconciliationProfile.id,bankReconciliationProfile.tenantId,bankReconciliationProfile.entityId]}),foreignKey({name:'br_edge_match_fk',columns:[t.matchId,t.tenantId,t.entityId,t.profileId],foreignColumns:[bankMatchGroup.id,bankMatchGroup.tenantId,bankMatchGroup.entityId,bankMatchGroup.profileId]}),foreignKey({name:'br_edge_movement_fk',columns:[t.movementId,t.tenantId,t.entityId,t.profileId],foreignColumns:[bankStatementMovement.id,bankStatementMovement.tenantId,bankStatementMovement.entityId,bankStatementMovement.profileId]}),foreignKey({name:'br_edge_opening_fk',columns:[t.openingItemId,t.tenantId,t.entityId,t.profileId],foreignColumns:[bankOpeningItem.id,bankOpeningItem.tenantId,bankOpeningItem.entityId,bankOpeningItem.profileId]}),foreignKey({name:'br_edge_gl_fk',columns:[t.glEntryId,t.tenantId,t.entityId],foreignColumns:[glEntry.id,glEntry.tenantId,glEntry.entityId]}),check('br_edge_ck',sql`${t.amount}>0 and ((${t.glEntryId} is null)<>(${t.openingItemId} is null))`)]);
export const bankNetVector = pgTable('bank_net_vector', {
 ...identity(), profileId: uuid('profile_id').notNull(), matchId:uuid('match_id').notNull(),side:text('side').notNull(),movementId:uuid('movement_id'),glEntryId:uuid('gl_entry_id'),signedAmount:money('signed_amount').notNull(),effectiveDate:date('effective_date').notNull(),snapshot:jsonb('snapshot').notNull(), ...authored(),
}, t => [uniqueIndex('bank_net_vector_scope_uq').on(t.id,t.tenantId,t.entityId,t.profileId),foreignKey({name:'bank_net_vector_profile_fk',columns:[t.profileId,t.tenantId,t.entityId],foreignColumns:[bankReconciliationProfile.id,bankReconciliationProfile.tenantId,bankReconciliationProfile.entityId]}),foreignKey({name:'br_net_match_fk',columns:[t.matchId,t.tenantId,t.entityId,t.profileId],foreignColumns:[bankMatchGroup.id,bankMatchGroup.tenantId,bankMatchGroup.entityId,bankMatchGroup.profileId]}),foreignKey({name:'br_net_movement_fk',columns:[t.movementId,t.tenantId,t.entityId,t.profileId],foreignColumns:[bankStatementMovement.id,bankStatementMovement.tenantId,bankStatementMovement.entityId,bankStatementMovement.profileId]}),foreignKey({name:'br_net_gl_fk',columns:[t.glEntryId,t.tenantId,t.entityId],foreignColumns:[glEntry.id,glEntry.tenantId,glEntry.entityId]}),check('br_net_ck',sql`${t.signedAmount}<>0 and ((${t.side}='bank' and ${t.movementId} is not null and ${t.glEntryId} is null) or (${t.side}='book' and ${t.glEntryId} is not null and ${t.movementId} is null))`)]);
export const bankReconciliationPeriod = pgTable('bank_reconciliation_period', {
 ...identity(), profileId: uuid('profile_id').notNull(), baselineId:uuid('baseline_id').notNull(),startDate:date('start_date').notNull(),endDate:date('end_date').notNull(),snapshot:jsonb('snapshot').notNull(),previewHash:text('preview_hash').notNull(), ...authored(),
}, t => [uniqueIndex('bank_reconciliation_period_scope_uq').on(t.id,t.tenantId,t.entityId,t.profileId),foreignKey({name:'bank_reconciliation_period_profile_fk',columns:[t.profileId,t.tenantId,t.entityId],foreignColumns:[bankReconciliationProfile.id,bankReconciliationProfile.tenantId,bankReconciliationProfile.entityId]}),foreignKey({name:'br_period_baseline_fk',columns:[t.baselineId,t.tenantId,t.entityId,t.profileId],foreignColumns:[bankReconciliationBaseline.id,bankReconciliationBaseline.tenantId,bankReconciliationBaseline.entityId,bankReconciliationBaseline.profileId]}),check('br_period_interval_ck',sql`${t.startDate}<=${t.endDate}`)]);
export const bankAdjustmentLink = pgTable('bank_adjustment_link', {
 ...identity(), profileId: uuid('profile_id').notNull(), movementId:uuid('movement_id').notNull(),kind:text('kind').notNull(),chargeId:uuid('charge_id'),voucherId:uuid('voucher_id'),snapshot:jsonb('snapshot').notNull(),releasedAt:timestamp('released_at',{withTimezone:true}),releaseReason:text('release_reason'), ...authored(),
}, t => [uniqueIndex('bank_adjustment_link_scope_uq').on(t.id,t.tenantId,t.entityId,t.profileId),foreignKey({name:'bank_adjustment_link_profile_fk',columns:[t.profileId,t.tenantId,t.entityId],foreignColumns:[bankReconciliationProfile.id,bankReconciliationProfile.tenantId,bankReconciliationProfile.entityId]}),foreignKey({name:'br_adjustment_movement_fk',columns:[t.movementId,t.tenantId,t.entityId,t.profileId],foreignColumns:[bankStatementMovement.id,bankStatementMovement.tenantId,bankStatementMovement.entityId,bankStatementMovement.profileId]}),foreignKey({name:'br_adjustment_charge_fk',columns:[t.chargeId,t.tenantId,t.entityId],foreignColumns:[bankChargeDocument.id,bankChargeDocument.tenantId,bankChargeDocument.entityId]}),foreignKey({name:'br_adjustment_voucher_fk',columns:[t.voucherId,t.tenantId,t.entityId],foreignColumns:[journalVoucher.id,journalVoucher.tenantId,journalVoucher.entityId]}),uniqueIndex('br_adjustment_active_uq').on(t.movementId).where(sql`${t.releasedAt} is null`),check('br_adjustment_kind_ck',sql`(${t.kind}='charge' and ${t.chargeId} is not null and ${t.voucherId} is null) or (${t.kind}='journal' and ${t.voucherId} is not null and ${t.chargeId} is null)`)]);
export const bankReconciliationEvent = pgTable('bank_reconciliation_event', {
 ...identity(), profileId: uuid('profile_id').notNull(), kind:text('kind').notNull(),baselineId:uuid('baseline_id'),importId:uuid('import_id'),matchId:uuid('match_id'),periodId:uuid('period_id'),reason:text('reason').notNull(),evidence:jsonb('evidence').notNull().default({}), ...authored(),
}, t => [uniqueIndex('bank_reconciliation_event_scope_uq').on(t.id,t.tenantId,t.entityId,t.profileId),foreignKey({name:'bank_reconciliation_event_profile_fk',columns:[t.profileId,t.tenantId,t.entityId],foreignColumns:[bankReconciliationProfile.id,bankReconciliationProfile.tenantId,bankReconciliationProfile.entityId]}),foreignKey({name:'br_event_baseline_fk',columns:[t.baselineId,t.tenantId,t.entityId,t.profileId],foreignColumns:[bankReconciliationBaseline.id,bankReconciliationBaseline.tenantId,bankReconciliationBaseline.entityId,bankReconciliationBaseline.profileId]}),foreignKey({name:'br_event_import_fk',columns:[t.importId,t.tenantId,t.entityId,t.profileId],foreignColumns:[bankStatementImport.id,bankStatementImport.tenantId,bankStatementImport.entityId,bankStatementImport.profileId]}),foreignKey({name:'br_event_match_fk',columns:[t.matchId,t.tenantId,t.entityId,t.profileId],foreignColumns:[bankMatchGroup.id,bankMatchGroup.tenantId,bankMatchGroup.entityId,bankMatchGroup.profileId]}),foreignKey({name:'br_event_period_fk',columns:[t.periodId,t.tenantId,t.entityId,t.profileId],foreignColumns:[bankReconciliationPeriod.id,bankReconciliationPeriod.tenantId,bankReconciliationPeriod.entityId,bankReconciliationPeriod.profileId]}),uniqueIndex('br_event_baseline_uq').on(t.baselineId),uniqueIndex('br_event_import_uq').on(t.importId),uniqueIndex('br_event_match_uq').on(t.matchId),uniqueIndex('br_event_period_uq').on(t.periodId),check('br_event_kind_ck',sql`length(trim(${t.reason}))>0 and ((${t.kind}='baseline_reset' and ${t.baselineId} is not null and ${t.importId} is null and ${t.matchId} is null and ${t.periodId} is null) or (${t.kind}='import_reversal' and ${t.importId} is not null and ${t.baselineId} is null and ${t.matchId} is null and ${t.periodId} is null) or (${t.kind}='match_reversal' and ${t.matchId} is not null and ${t.baselineId} is null and ${t.importId} is null and ${t.periodId} is null) or (${t.kind}='period_reopen' and ${t.periodId} is not null and ${t.baselineId} is null and ${t.importId} is null and ${t.matchId} is null))`)]);
