// Email operational evidence is independent of audit and accounting ledgers.
import {sql} from 'drizzle-orm';
import {check,foreignKey,index,integer,jsonb,pgTable,text,timestamp,uniqueIndex,uuid} from 'drizzle-orm/pg-core';
import {invitation} from './access.js';
const time=(name:string)=>timestamp(name,{withTimezone:true});
export const emailDelivery=pgTable('email_delivery',{
 id:uuid('id').primaryKey().defaultRandom(),tenantId:uuid('tenant_id'),scopeKey:text('scope_key').notNull(),purpose:text('purpose').notNull(),source:jsonb('source').$type<Record<string,string>>().notNull(),invitationId:uuid('invitation_id'),sourceUserId:text('source_user_id'),sourceExpiresAt:time('source_expires_at').notNull(),dedupeKey:text('dedupe_key').notNull(),templateVersion:text('template_version').notNull(),recipientMasked:text('recipient_masked').notNull(),envelope:jsonb('envelope').$type<{keyVersion:'v1';iv:string;tag:string;ciphertext:string}>(),status:text('status').notNull(),retryCount:integer('retry_count').notNull().default(0),nextAttemptAt:time('next_attempt_at'),leaseToken:uuid('lease_token'),leaseExpiresAt:time('lease_expires_at'),workerId:text('worker_id'),dispatchStartedAt:time('dispatch_started_at'),lastAttemptAt:time('last_attempt_at'),errorCode:text('error_code'),createdAt:time('created_at').notNull().defaultNow(),updatedAt:time('updated_at').notNull().defaultNow(),
},t=>[
 uniqueIndex('email_delivery_scope_uq').on(t.id,t.scopeKey),uniqueIndex('email_delivery_replay_uq').on(t.purpose,t.scopeKey,t.dedupeKey),index('email_delivery_due_idx').on(t.status,t.nextAttemptAt),
 foreignKey({name:'email_invitation_scope_fk',columns:[t.invitationId,t.tenantId],foreignColumns:[invitation.id,invitation.tenantId]}),
 check('email_scope_ck',sql`${t.scopeKey}=coalesce(${t.tenantId}::text,'account') and ((${t.purpose} in ('member_invitation','owner_invitation') and ${t.tenantId} is not null and ${t.invitationId} is not null and ${t.sourceUserId} is null and ${t.source}->>'kind'='invitation' and ${t.source}->>'tenantId'=${t.tenantId}::text and ${t.source}->>'invitationId'=${t.invitationId}::text) or (${t.purpose} in ('password_reset','email_verification') and ${t.tenantId} is null and ${t.invitationId} is null and ${t.sourceUserId} is not null and ${t.source}->>'kind'=${t.purpose} and ${t.source}->>'userId'=${t.sourceUserId}))`),
 check('email_source_shape_ck',sql`(case when ${t.purpose} in ('member_invitation','owner_invitation') then ${t.source}=jsonb_build_object('kind','invitation','tenantId',${t.tenantId}::text,'invitationId',${t.invitationId}::text) when ${t.purpose}='password_reset' then ${t.source}=jsonb_build_object('kind','password_reset','userId',${t.sourceUserId},'verificationId',${t.source}->>'verificationId') and length(${t.source}->>'verificationId') between 1 and 256 when ${t.purpose}='email_verification' then ${t.source}=jsonb_build_object('kind','email_verification','userId',${t.sourceUserId},'tokenDigest',${t.source}->>'tokenDigest') and ${t.source}->>'tokenDigest' ~ '^[a-f0-9]{64}$' else false end) is true`),
 check('email_state_ck',sql`${t.status} in ('unconfigured','queued','dispatching','retry_scheduled','accepted','failed','unknown','expired','cancelled','superseded') and ${t.retryCount} between 0 and 5 and ${t.templateVersion}='v1' and ((${t.status}='dispatching')=(${t.leaseToken} is not null and ${t.leaseExpiresAt} is not null)) and (${t.status} not in ('unconfigured','accepted','expired','cancelled','superseded') or ${t.envelope} is null) and (${t.status} not in ('queued','dispatching','retry_scheduled','unknown') or ${t.envelope} is not null) and (${t.status} not in ('unconfigured','accepted','failed','unknown','expired','cancelled','superseded') or ${t.nextAttemptAt} is null)`),
]);
export const emailAttempt=pgTable('email_attempt',{
 id:uuid('id').primaryKey().defaultRandom(),deliveryId:uuid('delivery_id').notNull(),tenantId:uuid('tenant_id'),scopeKey:text('scope_key').notNull(),leaseToken:uuid('lease_token').notNull(),workerId:text('worker_id').notNull(),outcome:text('outcome'),createdAt:time('created_at').notNull().defaultNow(),
},t=>[uniqueIndex('email_attempt_scope_uq').on(t.id,t.deliveryId,t.scopeKey),foreignKey({name:'email_attempt_parent_fk',columns:[t.deliveryId,t.scopeKey],foreignColumns:[emailDelivery.id,emailDelivery.scopeKey]}),check('email_attempt_tenant_ck',sql`${t.scopeKey}=coalesce(${t.tenantId}::text,'account')`)]);
export const emailEvent=pgTable('email_event',{
 id:uuid('id').primaryKey().defaultRandom(),deliveryId:uuid('delivery_id').notNull(),attemptId:uuid('attempt_id'),tenantId:uuid('tenant_id'),scopeKey:text('scope_key').notNull(),kind:text('kind').notNull(),code:text('code'),createdAt:time('created_at').notNull().defaultNow(),
},t=>[foreignKey({name:'email_event_parent_fk',columns:[t.deliveryId,t.scopeKey],foreignColumns:[emailDelivery.id,emailDelivery.scopeKey]}),foreignKey({name:'email_event_attempt_fk',columns:[t.attemptId,t.deliveryId,t.scopeKey],foreignColumns:[emailAttempt.id,emailAttempt.deliveryId,emailAttempt.scopeKey]}),check('email_event_tenant_ck',sql`${t.scopeKey}=coalesce(${t.tenantId}::text,'account')`)]);
export const emailRateLimit=pgTable('email_rate_limit',{
 id:uuid('id').primaryKey().defaultRandom(),tenantId:uuid('tenant_id'),identityHash:text('identity_hash').notNull(),kind:text('kind').notNull(),windowStartedAt:time('window_started_at').notNull(),count:integer('count').notNull().default(1),expiresAt:time('expires_at').notNull(),
},t=>[uniqueIndex('email_rate_window_uq').on(t.kind,t.identityHash,t.windowStartedAt),check('email_rate_ck',sql`${t.identityHash} ~ '^[a-f0-9]{64}$' and ${t.kind} in ('recipient','origin') and ${t.count}>0`)]);
export const emailWorkerHeartbeat=pgTable('email_worker_heartbeat',{
 id:text('id').primaryKey(),tenantId:uuid('tenant_id'),lastSeenAt:time('last_seen_at').notNull(),configurationState:text('configuration_state').notNull(),
},t=>[check('email_heartbeat_ck',sql`${t.tenantId} is null and ${t.configurationState} in ('disabled','ready','unavailable')`)]);
