import {sql} from 'drizzle-orm';
import {pgTable,uuid,text,integer,jsonb,timestamp,uniqueIndex,index,foreignKey,check} from 'drizzle-orm/pg-core';
import {gstRegistration} from './platform.js';
import {user} from './auth.js';
const scope={tenantId:uuid('tenant_id').notNull(),entityId:uuid('entity_id').notNull(),registrationId:uuid('registration_id').notNull()};
const time={createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow()};
export const gstSandboxConnection=pgTable('gst_sandbox_connection',{
 id:uuid('id').primaryKey().defaultRandom(),...scope,capability:text('capability').notNull(),environment:text('environment').notNull().default('sandbox'),provider:text('provider').notNull(),revision:integer('revision').notNull().default(1),credentialRevision:integer('credential_revision').notNull().default(0),scenario:text('scenario').notNull().default('normal'),createdBy:text('created_by').notNull().references(()=>user.id),...time,
},t=>[uniqueIndex('gst_sandbox_conn_scope_uq').on(t.id,t.tenantId,t.entityId,t.registrationId),uniqueIndex('gst_sandbox_conn_cap_uq').on(t.registrationId,t.environment,t.capability),foreignKey({name:'gst_sandbox_conn_reg_fk',columns:[t.registrationId,t.tenantId,t.entityId],foreignColumns:[gstRegistration.id,gstRegistration.tenantId,gstRegistration.entityId]}),check('gst_sandbox_conn_sandbox',sql`${t.environment}='sandbox' and ${t.provider} in ('mock','nic_direct') and ${t.capability} in ('irn','ewb') and ${t.scenario} in ('normal','timeout_after_success','rejected','unsupported_lookup','mismatched_lookup')`)]);
export const gstSandboxCredentialRevision=pgTable('gst_sandbox_credential_revision',{
 id:uuid('id').primaryKey().defaultRandom(),...scope,connectionId:uuid('connection_id').notNull(),revision:integer('revision').notNull(),envelope:jsonb('envelope').$type<Record<string,string>>().notNull(),createdBy:text('created_by').notNull().references(()=>user.id),...time,
},t=>[uniqueIndex('gst_sandbox_cred_rev_uq').on(t.connectionId,t.revision),foreignKey({name:'gst_sandbox_cred_conn_fk',columns:[t.connectionId,t.tenantId,t.entityId,t.registrationId],foreignColumns:[gstSandboxConnection.id,gstSandboxConnection.tenantId,gstSandboxConnection.entityId,gstSandboxConnection.registrationId]})]);
export const gstSandboxSnapshot=pgTable('gst_sandbox_snapshot',{
 id:uuid('id').primaryKey().defaultRandom(),...scope,sourceKind:text('source_kind').notNull(),sourceId:uuid('source_id'),documentType:text('document_type').notNull(),documentNumber:text('document_number').notNull(),fy:text('fy').notNull(),payload:jsonb('payload').$type<Record<string,unknown>>().notNull(),hash:text('hash').notNull(),createdBy:text('created_by').notNull().references(()=>user.id),...time,
},t=>[uniqueIndex('gst_sandbox_snapshot_scope_uq').on(t.id,t.tenantId,t.entityId,t.registrationId),index('gst_sandbox_snapshot_source').on(t.entityId,t.sourceKind,t.sourceId),foreignKey({name:'gst_sandbox_snapshot_reg_fk',columns:[t.registrationId,t.tenantId,t.entityId],foreignColumns:[gstRegistration.id,gstRegistration.tenantId,gstRegistration.entityId]})]);
export const gstSandboxOperation=pgTable('gst_sandbox_operation',{
 id:uuid('id').primaryKey().defaultRandom(),...scope,connectionId:uuid('connection_id').notNull(),snapshotId:uuid('snapshot_id').notNull(),environment:text('environment').notNull().default('sandbox'),action:text('action').notNull(),status:text('status').notNull().default('queued'),generationKey:text('generation_key'),idempotencyKey:text('idempotency_key').notNull(),command:jsonb('command').$type<Record<string,unknown>>().notNull(),commandHash:text('command_hash').notNull(),connectionRevision:integer('connection_revision').notNull(),provider:text('provider').notNull(),scenario:text('scenario').notNull(),parentId:uuid('parent_id'),result:jsonb('result').$type<Record<string,unknown>>(),detachedAt:timestamp('detached_at',{withTimezone:true}),leaseToken:uuid('lease_token'),leaseExpiresAt:timestamp('lease_expires_at',{withTimezone:true}),attemptSequence:integer('attempt_sequence').notNull().default(0),createdBy:text('created_by').notNull().references(()=>user.id),...time,
},t=>[uniqueIndex('gst_sandbox_operation_scope_uq').on(t.id,t.tenantId,t.entityId,t.registrationId),uniqueIndex('gst_sandbox_generation_uq').on(t.tenantId,t.registrationId,t.environment,t.generationKey),uniqueIndex('gst_sandbox_idempotency_uq').on(t.tenantId,t.entityId,t.idempotencyKey),index('gst_sandbox_queue').on(t.status,t.createdAt),foreignKey({name:'gst_sandbox_op_conn_fk',columns:[t.connectionId,t.tenantId,t.entityId,t.registrationId],foreignColumns:[gstSandboxConnection.id,gstSandboxConnection.tenantId,gstSandboxConnection.entityId,gstSandboxConnection.registrationId]}),foreignKey({name:'gst_sandbox_op_snap_fk',columns:[t.snapshotId,t.tenantId,t.entityId,t.registrationId],foreignColumns:[gstSandboxSnapshot.id,gstSandboxSnapshot.tenantId,gstSandboxSnapshot.entityId,gstSandboxSnapshot.registrationId]}),check('gst_sandbox_op_sandbox',sql`${t.environment}='sandbox' and ${t.provider} in ('mock','nic_direct')`),check('gst_sandbox_op_status',sql`${t.status} in ('prepared','queued','sending','succeeded','rejected','unknown','cancelled')`)]);
export const gstSandboxAttempt=pgTable('gst_sandbox_attempt',{
 id:uuid('id').primaryKey().defaultRandom(),...scope,operationId:uuid('operation_id').notNull(),sequence:integer('sequence').notNull(),leaseToken:uuid('lease_token').notNull(),credentialRevision:integer('credential_revision').notNull(),...time,
},t=>[uniqueIndex('gst_sandbox_attempt_seq').on(t.operationId,t.sequence),foreignKey({name:'gst_sandbox_attempt_op_fk',columns:[t.operationId,t.tenantId,t.entityId,t.registrationId],foreignColumns:[gstSandboxOperation.id,gstSandboxOperation.tenantId,gstSandboxOperation.entityId,gstSandboxOperation.registrationId]})]);
export const gstSandboxEvent=pgTable('gst_sandbox_event',{
 id:uuid('id').primaryKey().defaultRandom(),...scope,operationId:uuid('operation_id').notNull(),kind:text('kind').notNull(),actorId:text('actor_id'),evidence:jsonb('evidence').$type<Record<string,unknown>>().notNull().default({}),...time,
},t=>[foreignKey({name:'gst_sandbox_event_op_fk',columns:[t.operationId,t.tenantId,t.entityId,t.registrationId],foreignColumns:[gstSandboxOperation.id,gstSandboxOperation.tenantId,gstSandboxOperation.entityId,gstSandboxOperation.registrationId]})]);
// Simulated remote state, not a statutory ledger. Injected by the mock worker so acceptance survives crashes.
export const gstSandboxMockRemote=pgTable('gst_sandbox_mock_remote',{key:text('key').primaryKey(),tenantId:uuid('tenant_id').notNull(),entityId:uuid('entity_id').notNull(),evidence:jsonb('evidence').$type<Record<string,unknown>>().notNull(),...time});
