import { sql } from 'drizzle-orm';
import { bigint, boolean, check, date, foreignKey, index, integer, jsonb, numeric, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';
import { user } from './auth.js';
import { purchaseInvoice, purchaseInvoiceLine } from './buying.js';
import { receiptInvoiceAllocation } from './accounting.js';
import { docStatus, stockEntry, stockEntryLine, stockLedgerEntry, warehouse } from './inventory.js';
import { party } from './masters.js';
import { legalEntity, tenant } from './platform.js';
const amount=(name:string)=>numeric(name,{precision:24,scale:6});
const scope={tenantId:uuid('tenant_id').notNull().references(()=>tenant.id),entityId:uuid('entity_id').notNull().references(()=>legalEntity.id)};
const lifecycle={createdBy:text('created_by').notNull().references(()=>user.id),createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow(),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow(),submittedBy:text('submitted_by').references(()=>user.id),submittedAt:timestamp('submitted_at',{withTimezone:true}),cancelledBy:text('cancelled_by').references(()=>user.id),cancelledAt:timestamp('cancelled_at',{withTimezone:true}),cancelReason:text('cancel_reason')};
export interface SupplierPolicy {
 dispatchApproval:'pending_allowed'|'acceptance_required'; claimApproval:'every'|'above_threshold'; approvalThresholdInr:string; creditApplication:'automatic'|'manual'; rejectedAction:'keep_open'|'request_back'|'propose_write_off';
}
export const supplierReturnPolicy=pgTable('supplier_return_policy',{
 ...scope,dispatchApproval:text('dispatch_approval').notNull().default('pending_allowed'),claimApproval:text('claim_approval').notNull().default('every'),approvalThresholdInr:amount('approval_threshold_inr').notNull().default('0'),creditApplication:text('credit_application').notNull().default('automatic'),rejectedAction:text('rejected_action').notNull().default('keep_open'),updatedBy:text('updated_by').notNull().references(()=>user.id),updatedAt:timestamp('updated_at',{withTimezone:true}).notNull().defaultNow(),
},t=>[uniqueIndex('supplier_return_policy_entity_uq').on(t.entityId),check('supplier_policy_values',sql`${t.dispatchApproval} in ('pending_allowed','acceptance_required') and ${t.claimApproval} in ('every','above_threshold') and ${t.approvalThresholdInr}>=0 and ${t.creditApplication} in ('automatic','manual') and ${t.rejectedAction} in ('keep_open','request_back','propose_write_off')`)]);
export const supplierReturnClaim=pgTable('supplier_return_claim',{
 id:uuid('id').primaryKey().defaultRandom(),...scope,originalInvoiceId:uuid('original_invoice_id').notNull(),supplierId:uuid('supplier_id').notNull().references(()=>party.id),number:text('number'),status:docStatus('status').notNull().default('draft'),postingDate:date('posting_date').notNull(),reason:text('reason').notNull(),currency:text('currency').notNull(),exchangeRate:amount('exchange_rate').notNull(),policySnapshot:jsonb('policy_snapshot').$type<SupplierPolicy>(),approvedBy:text('approved_by').references(()=>user.id),approvedAt:timestamp('approved_at',{withTimezone:true}),approvalReason:text('approval_reason'),snapshots:jsonb('snapshots').$type<Record<string,unknown>>().notNull().default({}),...lifecycle,
},t=>[uniqueIndex('supplier_claim_scope_uq').on(t.id,t.tenantId,t.entityId,t.originalInvoiceId),uniqueIndex('supplier_claim_number_uq').on(t.entityId,t.number),foreignKey({name:'supplier_claim_invoice_scope_fk',columns:[t.originalInvoiceId,t.tenantId,t.entityId],foreignColumns:[purchaseInvoice.id,purchaseInvoice.tenantId,purchaseInvoice.entityId]}),check('supplier_claim_rate',sql`${t.exchangeRate}>0`)]);
export const supplierReturnClaimLine=pgTable('supplier_return_claim_line',{
 id:uuid('id').primaryKey().defaultRandom(),...scope,claimId:uuid('claim_id').notNull(),originalInvoiceId:uuid('original_invoice_id').notNull(),invoiceLineId:uuid('invoice_line_id').notNull(),lineNo:integer('line_no').notNull(),qty:amount('qty').notNull().default('0'),taxableAmount:amount('taxable_amount').notNull(),
},t=>[uniqueIndex('supplier_claim_line_scope_uq').on(t.id,t.tenantId,t.entityId),uniqueIndex('supplier_claim_line_source_uq').on(t.claimId,t.invoiceLineId),foreignKey({name:'supplier_claim_line_claim_fk',columns:[t.claimId,t.tenantId,t.entityId,t.originalInvoiceId],foreignColumns:[supplierReturnClaim.id,supplierReturnClaim.tenantId,supplierReturnClaim.entityId,supplierReturnClaim.originalInvoiceId]}).onDelete('cascade'),foreignKey({name:'supplier_claim_line_invoice_line_fk',columns:[t.invoiceLineId,t.originalInvoiceId],foreignColumns:[purchaseInvoiceLine.id,purchaseInvoiceLine.invoiceId]}),check('supplier_claim_line_amount',sql`${t.qty}>=0 and ${t.taxableAmount}>=0 and (${t.qty}>0 or ${t.taxableAmount}>0)`)]);
export const supplierNote=pgTable('supplier_note',{
 id:uuid('id').primaryKey().defaultRandom(),...scope,originalInvoiceId:uuid('original_invoice_id').notNull(),supplierId:uuid('supplier_id').notNull().references(()=>party.id),number:text('number'),status:docStatus('status').notNull().default('draft'),kind:text('kind').notNull(),taxTreatment:text('tax_treatment').notNull(),supplierNoteNo:text('supplier_note_no').notNull(),supplierNoteDate:date('supplier_note_date').notNull(),supplierFy:text('supplier_fy').notNull(),postingDate:date('posting_date').notNull(),reason:text('reason').notNull(),currency:text('currency').notNull(),exchangeRate:amount('exchange_rate').notNull(),taxEligibilityConfirmed:boolean('tax_eligibility_confirmed').notNull().default(false),snapshots:jsonb('snapshots').$type<Record<string,unknown>>().notNull().default({}),policySnapshot:jsonb('policy_snapshot').$type<SupplierPolicy>(),taxableValue:amount('taxable_value').notNull().default('0'),cgst:amount('cgst').notNull().default('0'),sgst:amount('sgst').notNull().default('0'),igst:amount('igst').notNull().default('0'),cess:amount('cess').notNull().default('0'),grandTotal:amount('grand_total').notNull().default('0'),billId:uuid('bill_id'),voucherId:uuid('voucher_id'),...lifecycle,
},t=>[uniqueIndex('supplier_note_scope_uq').on(t.id,t.tenantId,t.entityId,t.originalInvoiceId),uniqueIndex('supplier_note_reference_uq').on(t.entityId,t.supplierId,t.kind,t.supplierFy,sql`upper(${t.supplierNoteNo})`).where(sql`${t.status}='submitted'`),foreignKey({name:'supplier_note_invoice_scope_fk',columns:[t.originalInvoiceId,t.tenantId,t.entityId],foreignColumns:[purchaseInvoice.id,purchaseInvoice.tenantId,purchaseInvoice.entityId]}),check('supplier_note_values',sql`${t.kind} in ('credit','debit') and ${t.taxTreatment} in ('gst','commercial') and ${t.exchangeRate}>0`)]);
export const supplierNoteLine=pgTable('supplier_note_line',{
 id:uuid('id').primaryKey().defaultRandom(),...scope,noteId:uuid('note_id').notNull(),originalInvoiceId:uuid('original_invoice_id').notNull(),invoiceLineId:uuid('invoice_line_id').notNull(),claimLineId:uuid('claim_line_id'),lineNo:integer('line_no').notNull(),mode:text('mode').notNull(),qty:amount('qty').notNull().default('0'),taxableAmount:amount('taxable_amount').notNull(),cgst:amount('cgst').notNull().default('0'),sgst:amount('sgst').notNull().default('0'),igst:amount('igst').notNull().default('0'),cess:amount('cess').notNull().default('0'),
},t=>[uniqueIndex('supplier_note_line_scope_uq').on(t.id,t.tenantId,t.entityId),uniqueIndex('supplier_note_line_source_uq').on(t.noteId,t.invoiceLineId),foreignKey({name:'supplier_note_line_note_fk',columns:[t.noteId,t.tenantId,t.entityId,t.originalInvoiceId],foreignColumns:[supplierNote.id,supplierNote.tenantId,supplierNote.entityId,supplierNote.originalInvoiceId]}).onDelete('cascade'),foreignKey({name:'supplier_note_line_original_fk',columns:[t.invoiceLineId,t.originalInvoiceId],foreignColumns:[purchaseInvoiceLine.id,purchaseInvoiceLine.invoiceId]}),foreignKey({name:'supplier_note_line_claim_fk',columns:[t.claimLineId,t.tenantId,t.entityId],foreignColumns:[supplierReturnClaimLine.id,supplierReturnClaimLine.tenantId,supplierReturnClaimLine.entityId]}),check('supplier_note_line_values',sql`${t.mode} in ('quantity','value') and ${t.qty}>=0 and ${t.taxableAmount}>0`)]);
export const supplierReturnEffect=pgTable('supplier_return_effect',{
 id:uuid('id').primaryKey().defaultRandom(),...scope,claimLineId:uuid('claim_line_id').notNull(),invoiceLineId:uuid('invoice_line_id').notNull(),receiptAllocationId:uuid('receipt_allocation_id').notNull().references(()=>receiptInvoiceAllocation.id),receiptLineId:uuid('receipt_line_id').notNull().references(()=>stockEntryLine.id),stockEntryId:uuid('stock_entry_id').notNull().references(()=>stockEntry.id),ledgerSeq:bigint('ledger_seq',{mode:'number'}).notNull().references(()=>stockLedgerEntry.seq),warehouseId:uuid('warehouse_id').notNull().references(()=>warehouse.id),qty:amount('qty').notNull(),valueInr:amount('value_inr').notNull(),consumptions:jsonb('consumptions').$type<{layerId:string;qty:string;rate:string}[]>().notNull(),reversalOf:uuid('reversal_of'),createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow(),
},t=>[uniqueIndex('supplier_return_effect_scope_uq').on(t.id,t.tenantId,t.entityId),uniqueIndex('supplier_return_reversal_uq').on(t.reversalOf),index('supplier_return_claim_idx').on(t.entityId,t.claimLineId),foreignKey({name:'supplier_return_claim_line_fk',columns:[t.claimLineId,t.tenantId,t.entityId],foreignColumns:[supplierReturnClaimLine.id,supplierReturnClaimLine.tenantId,supplierReturnClaimLine.entityId]})]);
export const supplierAcceptanceEffect=pgTable('supplier_acceptance_effect',{
 id:uuid('id').primaryKey().defaultRandom(),...scope,claimLineId:uuid('claim_line_id').notNull(),noteLineId:uuid('note_line_id').notNull(),qty:amount('qty').notNull(),taxableAmount:amount('taxable_amount').notNull(),pendingValueInr:amount('pending_value_inr').notNull().default('0'),reversalOf:uuid('reversal_of'),createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow(),
},t=>[uniqueIndex('supplier_acceptance_reversal_uq').on(t.reversalOf),foreignKey({name:'supplier_acceptance_claim_fk',columns:[t.claimLineId,t.tenantId,t.entityId],foreignColumns:[supplierReturnClaimLine.id,supplierReturnClaimLine.tenantId,supplierReturnClaimLine.entityId]}),foreignKey({name:'supplier_acceptance_note_fk',columns:[t.noteLineId,t.tenantId,t.entityId],foreignColumns:[supplierNoteLine.id,supplierNoteLine.tenantId,supplierNoteLine.entityId]})]);
export const supplierResolutionEffect=pgTable('supplier_resolution_effect',{
 id:uuid('id').primaryKey().defaultRandom(),...scope,claimLineId:uuid('claim_line_id').notNull(),returnEffectId:uuid('return_effect_id').notNull(),kind:text('kind').notNull(),qty:amount('qty').notNull(),valueInr:amount('value_inr').notNull(),postingDate:date('posting_date').notNull(),reason:text('reason').notNull(),stockEntryId:uuid('stock_entry_id').references(()=>stockEntry.id),voucherId:uuid('voucher_id'),createdBy:text('created_by').notNull().references(()=>user.id),reversalOf:uuid('reversal_of'),createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow(),
},t=>[uniqueIndex('supplier_resolution_reversal_uq').on(t.reversalOf),foreignKey({name:'supplier_resolution_claim_fk',columns:[t.claimLineId,t.tenantId,t.entityId],foreignColumns:[supplierReturnClaimLine.id,supplierReturnClaimLine.tenantId,supplierReturnClaimLine.entityId]}),foreignKey({name:'supplier_resolution_return_fk',columns:[t.returnEffectId,t.tenantId,t.entityId],foreignColumns:[supplierReturnEffect.id,supplierReturnEffect.tenantId,supplierReturnEffect.entityId]}),check('supplier_resolution_kind',sql`${t.kind} in ('write_off','receive_back','acceptance_reversal')`)]);
