import { Dec,requiresClaimApproval } from '@factoryos/core';
import { accountingSettings,journalVoucher,purchaseInvoice,purchaseInvoiceLine,supplierReturnClaim,supplierReturnClaimLine,supplierReturnEffect,supplierAcceptanceEffect,receiptInvoiceAllocation,stockEntryLine,stockEntry,item,batch,supplierResolutionEffect,auditEvent,party,legalEntity,gstRegistration } from '@factoryos/db';
import { Injectable,NotFoundException,ConflictException,BadRequestException } from '@nestjs/common';
import { and,eq,desc,asc,sql } from 'drizzle-orm';
import { AuditService } from '../../common/audit.service.js';
import type { TenantRequestContext } from '../../common/access.js';
import {businessDate,lockAccounting,type Tx} from '../accounting/accounting-lock.js';
import {StockPostingService} from '../stock-posting.service.js';
import {SupplierReturnPolicyService} from './policy.service.js';
import type {ClaimInput} from './contracts.js';
@Injectable()
export class SupplierReturnClaimService {
 constructor(private readonly policy:SupplierReturnPolicyService,private readonly audit:AuditService,private readonly stock:StockPostingService){}
 async sourceIn(tx:Tx,ctx:TenantRequestContext,entityId:string,id:string){
 const [invoice]=await tx.select().from(purchaseInvoice).where(and(eq(purchaseInvoice.id,id),eq(purchaseInvoice.tenantId,ctx.tenant.tenantId),eq(purchaseInvoice.entityId,entityId)));
 if(!invoice)throw new NotFoundException('Purchase invoice not found');
 const [settings]=await tx.select().from(accountingSettings).where(and(eq(accountingSettings.entityId,entityId),eq(accountingSettings.tenantId,ctx.tenant.tenantId)));
 if(!settings?.active||!settings.cutoverDate||invoice.status!=='submitted'||invoice.postingDate<settings.cutoverDate||!invoice.submittedAt||invoice.submittedAt<=settings.activatedAt!)throw new ConflictException('Returns require a submitted active-era invoice in active books');
 const [voucher]=await tx.select().from(journalVoucher).where(and(eq(journalVoucher.entityId,entityId),eq(journalVoucher.tenantId,ctx.tenant.tenantId),eq(journalVoucher.sourceType,'purchase_invoice'),eq(journalVoucher.sourceId,id),sql`${journalVoucher.reversalOf} is null`));
 if(!voucher)throw new ConflictException('Original purchase posting evidence is missing');
 const lines=await tx.select().from(purchaseInvoiceLine).where(eq(purchaseInvoiceLine.invoiceId,id));return {invoice,lines,settings,voucher};
 }
 async claimIn(tx:Tx,ctx:TenantRequestContext,e:string,id:string,lock=false){const q=tx.select().from(supplierReturnClaim).where(and(eq(supplierReturnClaim.id,id),eq(supplierReturnClaim.tenantId,ctx.tenant.tenantId),eq(supplierReturnClaim.entityId,e)));const [row]=await(lock?q.for('update'):q);if(!row)throw new NotFoundException('Supplier return claim not found');return row;}
 async listIn(tx:Tx,ctx:TenantRequestContext,e:string){return tx.select().from(supplierReturnClaim).where(and(eq(supplierReturnClaim.entityId,e),eq(supplierReturnClaim.tenantId,ctx.tenant.tenantId))).orderBy(desc(supplierReturnClaim.createdAt));}
 async getIn(tx:Tx,ctx:TenantRequestContext,e:string,id:string){const claim=await this.claimIn(tx,ctx,e,id);const lines=await tx.select().from(supplierReturnClaimLine).where(and(eq(supplierReturnClaimLine.claimId,id),eq(supplierReturnClaimLine.entityId,e))).orderBy(asc(supplierReturnClaimLine.lineNo));const enriched=[];for(const l of lines){const [source]=await tx.select({l:purchaseInvoiceLine,i:item}).from(purchaseInvoiceLine).innerJoin(item,eq(item.id,purchaseInvoiceLine.itemId)).where(eq(purchaseInvoiceLine.id,l.invoiceLineId));const receipts=await tx.select({receiptAllocationId:receiptInvoiceAllocation.id,receiptLineId:stockEntryLine.id,receiptNumber:stockEntry.number,batchId:stockEntryLine.batchId,batchNo:batch.batchNo,warehouseId:stockEntryLine.toWarehouseId,qty:receiptInvoiceAllocation.qty}).from(receiptInvoiceAllocation).innerJoin(stockEntryLine,eq(stockEntryLine.id,receiptInvoiceAllocation.receiptLineId)).innerJoin(stockEntry,eq(stockEntry.id,stockEntryLine.entryId)).leftJoin(batch,eq(batch.id,stockEntryLine.batchId)).where(and(eq(receiptInvoiceAllocation.entityId,e),eq(receiptInvoiceAllocation.tenantId,ctx.tenant.tenantId),eq(receiptInvoiceAllocation.invoiceId,claim.originalInvoiceId),source?.l.poLineId?eq(stockEntryLine.poLineId,source.l.poLineId):sql`false`,sql`${receiptInvoiceAllocation.reversalOf} is null`,eq(stockEntry.status,'submitted')));
 const moves=await tx.select().from(supplierReturnEffect).where(and(eq(supplierReturnEffect.entityId,e),eq(supplierReturnEffect.claimLineId,l.id)));const accepted=await tx.select().from(supplierAcceptanceEffect).where(and(eq(supplierAcceptanceEffect.entityId,e),eq(supplierAcceptanceEffect.claimLineId,l.id)));const resolved=await tx.select().from(supplierResolutionEffect).where(and(eq(supplierResolutionEffect.entityId,e),eq(supplierResolutionEffect.claimLineId,l.id)));const dispatchedQty=moves.reduce((s,x)=>s.add(x.qty),Dec.ZERO),acceptedQty=accepted.reduce((s,x)=>s.add(x.qty),Dec.ZERO),resolvedQty=resolved.filter(x=>x.kind!=='acceptance_reversal').reduce((s,x)=>s.add(x.qty),Dec.ZERO),pendingValue=moves.reduce((s,x)=>s.add(x.valueInr).sub(x.preAcceptedValueInr),Dec.ZERO).sub(accepted.reduce((s,x)=>s.add(x.pendingValueInr),Dec.ZERO)).sub(resolved.reduce((s,x)=>s.add(x.valueInr),Dec.ZERO));enriched.push({...l,itemName:source?.i.name??'Original invoice line',isStockItem:source?.i.isStockItem??false,receipts,dispatchedQty:dispatchedQty.toFixed(6),acceptedQty:acceptedQty.toFixed(6),resolvedQty:resolvedQty.toFixed(6),pendingValueInr:pendingValue.toFixed(6),movements:moves.filter(x=>!x.reversalOf).map(x=>({...x,reversed:moves.some(r=>r.reversalOf===x.id)})),resolutions:resolved.filter(x=>!x.reversalOf).map(x=>({...x,reversed:resolved.some(r=>r.reversalOf===x.id)}))});}
 const responses=await tx.select().from(auditEvent).where(and(eq(auditEvent.tenantId,ctx.tenant.tenantId),eq(auditEvent.entityId,e),eq(auditEvent.targetId,id),eq(auditEvent.action,'supplier_return_claim.reject'))).orderBy(asc(auditEvent.seq));return {...claim,lines:enriched,responses};}
 async saveIn(tx:Tx,ctx:TenantRequestContext,e:string,input:ClaimInput,id?:string){
 await lockAccounting(tx,e);const prior=id?await this.claimIn(tx,ctx,e,id,true):null;
 if(prior&&(prior.status!=='draft'||prior.originalInvoiceId!==input.invoiceId))throw new ConflictException('Only original-invoice draft claims may be edited');
 const {invoice,lines,settings}=await this.sourceIn(tx,ctx,e,input.invoiceId);
 if(input.postingDate<invoice.postingDate||input.postingDate<settings.cutoverDate!||input.postingDate>businessDate())throw new BadRequestException('Claim date must be from source/cut-over through today');
 const seen=new Set<string>();for(const l of input.lines){const original=lines.find(x=>x.id===l.invoiceLineId);if(!original||seen.has(l.invoiceLineId))throw new BadRequestException('Choose unique original invoice lines');seen.add(l.invoiceLineId);if(Dec.of(l.qty).gt(original.qty)||Dec.of(l.taxableAmount).gt(original.taxableValue??'0')||(!Dec.of(l.qty).gt('0')&&!Dec.of(l.taxableAmount).gt('0')))throw new BadRequestException('Claim exceeds original line or has no quantity/value');}
 const [supplier]=await tx.select().from(party).where(eq(party.id,invoice.supplierId));const [entity]=await tx.select().from(legalEntity).where(eq(legalEntity.id,e));const [reg]=invoice.gstRegistrationId?await tx.select().from(gstRegistration).where(eq(gstRegistration.id,invoice.gstRegistrationId)):[];
 const values={snapshots:{supplierName:supplier!.name,supplierGstin:supplier!.gstin,supplierAddress:supplier!.addresses,buyerName:entity!.legalName,buyerGstin:reg?.gstin,buyerAddress:reg?.address,originalInvoiceNumber:invoice.supplierInvoiceNo,originalInvoiceDate:invoice.supplierInvoiceDate},originalInvoiceId:invoice.id,supplierId:invoice.supplierId,postingDate:input.postingDate,reason:input.reason,currency:invoice.currency,exchangeRate:invoice.exchangeRate,updatedAt:new Date()};
 const [claim]=id?await tx.update(supplierReturnClaim).set(values).where(eq(supplierReturnClaim.id,id)).returning():await tx.insert(supplierReturnClaim).values({...values,tenantId:ctx.tenant.tenantId,entityId:e,createdBy:ctx.user.id}).returning();
 if(prior)await tx.delete(supplierReturnClaimLine).where(eq(supplierReturnClaimLine.claimId,id!));await tx.insert(supplierReturnClaimLine).values(input.lines.map((l,i)=>({...l,tenantId:ctx.tenant.tenantId,entityId:e,claimId:claim!.id,originalInvoiceId:invoice.id,lineNo:i+1})));
 await this.audit.record(ctx,{tenantId:ctx.tenant.tenantId,entityId:e,action:prior?'supplier_return_claim.update':'supplier_return_claim.create',targetType:'supplier_return_claim',targetId:claim!.id,after:input},tx);return this.getIn(tx,ctx,e,claim!.id);
 }
 async submitIn(tx:Tx,ctx:TenantRequestContext,e:string,id:string){await lockAccounting(tx,e);const claim=await this.getIn(tx,ctx,e,id);if(claim.status!=='draft')throw new ConflictException('Only draft claims can submit');await this.sourceIn(tx,ctx,e,claim.originalInvoiceId);const policy=await this.policy.getIn(tx,ctx,e);const requested=claim.lines.reduce((sum,l)=>sum.add(l.taxableAmount),Dec.ZERO);const needed=requiresClaimApproval(policy,requested.toString(),claim.exchangeRate);const number=await this.stock.allocateNumber(tx,ctx.tenant.tenantId,e,'supplier_return_claim',claim.postingDate);await tx.update(supplierReturnClaim).set({status:'submitted',number,policySnapshot:policy,submittedBy:ctx.user.id,submittedAt:new Date(),approvedBy:needed?null:ctx.user.id,approvedAt:needed?null:new Date(),updatedAt:new Date()}).where(eq(supplierReturnClaim.id,id));await this.audit.record(ctx,{tenantId:ctx.tenant.tenantId,entityId:e,action:'supplier_return_claim.submit',targetType:'supplier_return_claim',targetId:id,after:{number,approvalRequired:needed,policy}},tx);return this.getIn(tx,ctx,e,id);}
 async approveIn(tx:Tx,ctx:TenantRequestContext,e:string,id:string,reason:string){await lockAccounting(tx,e);const claim=await this.claimIn(tx,ctx,e,id,true);if(claim.status!=='submitted')throw new ConflictException('Only submitted claims can be approved');await this.sourceIn(tx,ctx,e,claim.originalInvoiceId);await tx.update(supplierReturnClaim).set({approvedBy:ctx.user.id,approvedAt:new Date(),approvalReason:reason,updatedAt:new Date()}).where(eq(supplierReturnClaim.id,id));await this.audit.record(ctx,{tenantId:ctx.tenant.tenantId,entityId:e,action:'supplier_return_claim.approve',targetType:'supplier_return_claim',targetId:id,reason},tx);return this.getIn(tx,ctx,e,id);}
 async rejectIn(tx:Tx,ctx:TenantRequestContext,e:string,id:string,input:{reason:string;lines:{claimLineId:string;qty:string;taxableAmount:string}[]}){await lockAccounting(tx,e);const claim=await this.getIn(tx,ctx,e,id);if(claim.status!=='submitted'||!claim.approvedBy)throw new ConflictException('Only approved submitted claims can record a supplier response');const seen=new Set<string>();for(const l of input.lines){const original=claim.lines.find(x=>x.id===l.claimLineId);if(!original||seen.has(l.claimLineId))throw new BadRequestException('Choose unique claim lines');seen.add(l.claimLineId);if(Dec.of(l.qty).gt(Dec.of(original.qty).sub(original.acceptedQty))||Dec.of(l.taxableAmount).gt(original.taxableAmount)||(!Dec.of(l.qty).gt('0')&&!Dec.of(l.taxableAmount).gt('0')))throw new ConflictException('Rejection exceeds unaccepted claim balance');}await this.audit.record(ctx,{tenantId:ctx.tenant.tenantId,entityId:e,action:'supplier_return_claim.reject',targetType:'supplier_return_claim',targetId:id,reason:input.reason,after:{lines:input.lines,suggestedAction:claim.policySnapshot?.rejectedAction??'keep_open'}},tx);return this.getIn(tx,ctx,e,id);}
 async deleteIn(tx:Tx,ctx:TenantRequestContext,e:string,id:string){const claim=await this.claimIn(tx,ctx,e,id,true);if(claim.status!=='draft')throw new ConflictException('Only draft claims can be deleted');await tx.delete(supplierReturnClaim).where(eq(supplierReturnClaim.id,id));}
 async cancelIn(tx:Tx,ctx:TenantRequestContext,e:string,id:string,reason:string){await lockAccounting(tx,e);const claim=await this.getIn(tx,ctx,e,id);if(claim.status!=='submitted')throw new ConflictException('Only submitted claims may cancel');for(const l of claim.lines){const movements=await tx.select().from(supplierReturnEffect).where(and(eq(supplierReturnEffect.entityId,e),eq(supplierReturnEffect.claimLineId,l.id)));const accepts=await tx.select().from(supplierAcceptanceEffect).where(and(eq(supplierAcceptanceEffect.entityId,e),eq(supplierAcceptanceEffect.claimLineId,l.id)));if(movements.reduce((s,x)=>s.add(x.qty),Dec.ZERO).gt('0')||accepts.reduce((s,x)=>s.add(x.qty).add(x.taxableAmount),Dec.ZERO).gt('0'))throw new ConflictException('Reverse dependent dispatches and supplier notes before cancelling the claim');}await tx.update(supplierReturnClaim).set({status:'cancelled',cancelledBy:ctx.user.id,cancelledAt:new Date(),cancelReason:reason,updatedAt:new Date()}).where(eq(supplierReturnClaim.id,id));await this.audit.record(ctx,{tenantId:ctx.tenant.tenantId,entityId:e,action:'supplier_return_claim.cancel',targetType:'supplier_return_claim',targetId:id,reason},tx);return {ok:true};}
}
