import {returnAccountsIn} from './return-accounts.js';
import {GlPostingService} from '../accounting/gl-posting.service.js';
import {Dec,fyCode} from '@factoryos/core';
import {supplierNote,supplierNoteLine,supplierAcceptanceEffect,supplierReturnEffect,supplierResolutionEffect,glAccount,purchaseInvoiceLine,item,settlementAllocationDocument,party,gstRegistration,legalEntity} from '@factoryos/db';
import {Injectable,ConflictException,NotFoundException} from '@nestjs/common';
import {and,eq,desc,asc,sql} from 'drizzle-orm';
import type {TenantRequestContext} from '../../common/access.js';
import {AuditService} from '../../common/audit.service.js';
import {businessDate,lockAccounting,type Tx} from '../accounting/accounting-lock.js';
import {BillService} from '../accounting/bill.service.js';
import {StockPostingService} from '../stock-posting.service.js';
import {SupplierNotePreviewService} from './preview.service.js';
import {SupplierNotePostingService} from './note-posting.service.js';
import {SupplierReturnClaimService} from './claim.service.js';
import {SupplierReturnPolicyService} from './policy.service.js';
import {SupplierCreditApplicationService} from './credit-application.service.js';
import type {SupplierNoteInput} from './contracts.js';
@Injectable()
export class SupplierNoteService {
 constructor(private readonly preview:SupplierNotePreviewService,private readonly posting:SupplierNotePostingService,private readonly claims:SupplierReturnClaimService,private readonly policy:SupplierReturnPolicyService,private readonly credits:SupplierCreditApplicationService,private readonly stock:StockPostingService,private readonly bills:BillService,private readonly audit:AuditService,private readonly gl:GlPostingService){}
 async noteIn(tx:Tx,ctx:TenantRequestContext,e:string,id:string,lock=false){const q=tx.select().from(supplierNote).where(and(eq(supplierNote.id,id),eq(supplierNote.entityId,e),eq(supplierNote.tenantId,ctx.tenant.tenantId)));const [note]=await(lock?q.for('update'):q);if(!note)throw new NotFoundException('Supplier note not found');return note;}
 async listIn(tx:Tx,ctx:TenantRequestContext,e:string){return tx.select().from(supplierNote).where(and(eq(supplierNote.entityId,e),eq(supplierNote.tenantId,ctx.tenant.tenantId))).orderBy(desc(supplierNote.createdAt));}
 async getIn(tx:Tx,ctx:TenantRequestContext,e:string,id:string){const note=await this.noteIn(tx,ctx,e,id),lines=await tx.select().from(supplierNoteLine).where(and(eq(supplierNoteLine.noteId,id),eq(supplierNoteLine.entityId,e))).orderBy(asc(supplierNoteLine.lineNo));const [creditBalance]=note.billId?await this.bills.list(tx,e,{billIds:[note.billId]}):[];const applications=await tx.select().from(settlementAllocationDocument).where(and(eq(settlementAllocationDocument.entityId,e),eq(settlementAllocationDocument.supplierNoteId,id)));const enriched=[];for(const l of lines){const [source]=await tx.select({i:item,l:purchaseInvoiceLine}).from(purchaseInvoiceLine).innerJoin(item,eq(item.id,purchaseInvoiceLine.itemId)).where(eq(purchaseInvoiceLine.id,l.invoiceLineId));enriched.push({...l,itemName:source?.i.name??'Original invoice line',originalQty:source?.l.qty,originalRate:source?.l.rate});}return {...note,lines:enriched,creditBalance:creditBalance??null,applications};}
 async inputIn(tx:Tx,n:typeof supplierNote.$inferSelect):Promise<SupplierNoteInput>{const lines=await tx.select().from(supplierNoteLine).where(eq(supplierNoteLine.noteId,n.id));return {invoiceId:n.originalInvoiceId,kind:n.kind as 'credit'|'debit',taxTreatment:n.taxTreatment as 'gst'|'commercial',supplierNoteNo:n.supplierNoteNo,supplierNoteDate:n.supplierNoteDate,postingDate:n.postingDate,reason:n.reason,taxEligibilityConfirmed:n.taxEligibilityConfirmed,lines:lines.map(l=>({invoiceLineId:l.invoiceLineId,claimLineId:l.claimLineId??undefined,mode:l.mode as 'quantity'|'value',qty:l.qty,taxableAmount:l.taxableAmount}))};}
 async saveIn(tx:Tx,ctx:TenantRequestContext,e:string,input:SupplierNoteInput,id?:string){await lockAccounting(tx,e);const prior=id?await this.noteIn(tx,ctx,e,id,true):null;if(prior&&(prior.status!=='draft'||prior.originalInvoiceId!==input.invoiceId))throw new ConflictException('Only original-invoice draft notes may change');
 const p=await this.preview.calculateIn(tx,ctx,e,input,id),{invoice}=await this.claims.sourceIn(tx,ctx,e,input.invoiceId);
 const [supplier]=await tx.select().from(party).where(eq(party.id,invoice.supplierId));const [entity]=await tx.select().from(legalEntity).where(eq(legalEntity.id,e));const [reg]=invoice.gstRegistrationId?await tx.select().from(gstRegistration).where(eq(gstRegistration.id,invoice.gstRegistrationId)):[];
 const data={originalInvoiceId:invoice.id,supplierId:invoice.supplierId,kind:input.kind,taxTreatment:input.taxTreatment,supplierNoteNo:input.supplierNoteNo,supplierNoteDate:input.supplierNoteDate,supplierFy:fyCode(new Date(`${input.supplierNoteDate}T00:00:00Z`)),postingDate:input.postingDate,reason:input.reason,taxEligibilityConfirmed:input.taxEligibilityConfirmed,currency:invoice.currency,exchangeRate:invoice.exchangeRate,taxableValue:p.taxableValue,cgst:p.cgst,sgst:p.sgst,igst:p.igst,cess:p.cess,grandTotal:p.grandTotal,snapshots:{supplierName:supplier!.name,supplierGstin:supplier!.gstin,supplierAddress:supplier!.addresses,buyerName:entity!.legalName,buyerGstin:reg?.gstin,buyerAddress:reg?.address,originalInvoiceNumber:invoice.supplierInvoiceNo,originalInvoiceDate:invoice.supplierInvoiceDate},updatedAt:new Date()};
 const [note]=id?await tx.update(supplierNote).set(data).where(eq(supplierNote.id,id)).returning():await tx.insert(supplierNote).values({...data,tenantId:ctx.tenant.tenantId,entityId:e,createdBy:ctx.user.id}).returning();
 if(prior)await tx.delete(supplierNoteLine).where(eq(supplierNoteLine.noteId,id!));await tx.insert(supplierNoteLine).values(p.lines.map((l,i)=>({tenantId:ctx.tenant.tenantId,entityId:e,noteId:note!.id,originalInvoiceId:invoice.id,invoiceLineId:l.invoiceLineId,claimLineId:l.claimLineId,lineNo:i+1,mode:input.lines[i]!.mode,qty:l.qty,taxableAmount:l.taxableAmount,cgst:l.cgst,sgst:l.sgst,igst:l.igst,cess:l.cess})));
 await this.audit.record(ctx,{tenantId:ctx.tenant.tenantId,entityId:e,action:prior?'supplier_note.update':'supplier_note.create',targetType:'supplier_note',targetId:note!.id,after:{kind:input.kind,grandTotal:p.grandTotal}},tx);return this.getIn(tx,ctx,e,note!.id);
 }
 async submitIn(tx:Tx,ctx:TenantRequestContext,e:string,id:string){await lockAccounting(tx,e);const prior=await this.noteIn(tx,ctx,e,id,true);if(prior.status!=='draft')throw new ConflictException('Only draft supplier notes can submit');
 const [duplicate]=await tx.select().from(supplierNote).where(and(eq(supplierNote.entityId,e),eq(supplierNote.supplierId,prior.supplierId),eq(supplierNote.kind,prior.kind),eq(supplierNote.supplierFy,prior.supplierFy),eq(supplierNote.status,'submitted'),sql`upper(${supplierNote.supplierNoteNo})=upper(${prior.supplierNoteNo})`));if(duplicate)throw new ConflictException('Supplier note reference is already booked');
 const input=await this.inputIn(tx,prior);await this.saveIn(tx,ctx,e,input,id);const p=await this.preview.calculateIn(tx,ctx,e,input,id),policy=await this.policy.getIn(tx,ctx,e);
 await this.bills.assertReconciledIn(tx,e);const number=await this.stock.allocateNumber(tx,ctx.tenant.tenantId,e,'supplier_note',prior.postingDate);
 const [note]=await tx.update(supplierNote).set({status:'submitted',number,policySnapshot:policy,submittedBy:ctx.user.id,submittedAt:new Date(),updatedAt:new Date()}).where(eq(supplierNote.id,id)).returning();
 const recognition=await this.posting.recognizeIn(tx,ctx,e,note!,p);await tx.update(supplierNote).set(recognition).where(eq(supplierNote.id,id));
 const rows=await tx.select().from(supplierNoteLine).where(eq(supplierNoteLine.noteId,id));for(const l of p.lines){if(!l.claimLineId)continue;const nl=rows.find(x=>x.invoiceLineId===l.invoiceLineId)!;await tx.insert(supplierAcceptanceEffect).values({tenantId:ctx.tenant.tenantId,entityId:e,claimLineId:l.claimLineId,noteLineId:nl.id,qty:l.qty,taxableAmount:l.taxableAmount,pendingValueInr:l.pendingValueInr,pendingReturns:l.pendingReturns});}
 if(prior.kind==='credit'&&policy.creditApplication==='automatic'){const [target]=await this.bills.list(tx,e,{billIds:[p.sourceBillId]});if(target&&Dec.of(target.openAmount).gt('0')){const amount=Dec.min(Dec.of(target.openAmount),Dec.of(p.grandTotal));await this.credits.applyIn(tx,ctx,e,{supplierNoteId:id,postingDate:prior.postingDate,allocations:[{billId:target.id,amount:amount.toFixed(2)}],sourceId:id,automatic:true});}}
 await this.bills.assertReconciledIn(tx,e);await this.audit.record(ctx,{tenantId:ctx.tenant.tenantId,entityId:e,action:'supplier_note.submit',targetType:'supplier_note',targetId:id,after:{number,grandTotal:p.grandTotal}},tx);return this.getIn(tx,ctx,e,id);
 }
 async deleteIn(tx:Tx,ctx:TenantRequestContext,e:string,id:string){const n=await this.noteIn(tx,ctx,e,id,true);if(n.status!=='draft')throw new ConflictException('Only draft supplier notes may be deleted');await tx.delete(supplierNote).where(eq(supplierNote.id,id));}
 async cancelIn(tx:Tx,ctx:TenantRequestContext,e:string,id:string,reason:string){
 await lockAccounting(tx,e);const n=await this.noteIn(tx,ctx,e,id,true);if(n.status!=='submitted')throw new ConflictException('Only submitted supplier notes may cancel');
 const dependencies=await tx.select().from(settlementAllocationDocument).where(and(eq(settlementAllocationDocument.entityId,e),eq(settlementAllocationDocument.supplierNoteId,id),eq(settlementAllocationDocument.status,'submitted')));if(dependencies.length)throw new ConflictException('Reverse later supplier credit applications first');
 if(n.kind==='debit'){
 const input=await this.inputIn(tx,n);const siblings=await tx.select({n:supplierNote,l:supplierNoteLine}).from(supplierNoteLine).innerJoin(supplierNote,eq(supplierNote.id,supplierNoteLine.noteId)).where(and(eq(supplierNote.originalInvoiceId,n.originalInvoiceId),eq(supplierNote.entityId,e),eq(supplierNote.status,'submitted'),sql`${supplierNote.id}<>${id}`));const source=await this.claims.sourceIn(tx,ctx,e,n.originalInvoiceId);
 for(const l of source.lines){const rows=siblings.filter(x=>x.l.invoiceLineId===l.id);const sum=(kind:string,key:'taxableAmount'|'cgst'|'sgst'|'igst'|'cess',gst=false)=>rows.filter(x=>x.n.kind===kind&&(!gst||x.n.taxTreatment==='gst')).reduce((s,x)=>s.add(x.l[key]),Dec.ZERO);if(sum('credit','taxableAmount').gt(Dec.of(l.taxableValue??'0').add(sum('debit','taxableAmount')))||sum('credit','taxableAmount',true).gt(Dec.of(l.taxableValue??'0').add(sum('debit','taxableAmount',true)))||(['cgst','sgst','igst','cess'] as const).some(k=>sum('credit',k,true).gt(Dec.of(l[k]??'0').add(sum('debit',k,true)))))throw new ConflictException('Supplier credits depend on this debit ceiling');}
 }
 await this.credits.reverseIn(tx,ctx,e,id,reason);await this.gl.reverseIn(tx,ctx,e,{type:'supplier_note',id,purpose:'main'},reason);await this.bills.reverseSourceEffects(tx,ctx,e,'supplier_note',id,businessDate());
 const lines=await tx.select().from(supplierNoteLine).where(eq(supplierNoteLine.noteId,id));
 for(const nl of lines){const accepts=await tx.select().from(supplierAcceptanceEffect).where(and(eq(supplierAcceptanceEffect.entityId,e),eq(supplierAcceptanceEffect.noteLineId,nl.id),sql`${supplierAcceptanceEffect.reversalOf} is null`));for(const a of accepts){
 const returns=await tx.select().from(supplierReturnEffect).where(and(eq(supplierReturnEffect.entityId,e),eq(supplierReturnEffect.claimLineId,a.claimLineId),sql`${supplierReturnEffect.reversalOf} is null`));
 for(const r of returns.filter(x=>x.createdAt>=a.createdAt&&Dec.of(x.preAcceptedQty).gt('0'))){
 const linked=r.preAcceptances.find(x=>x.acceptanceEffectId===a.id);if(!linked)continue;const restored=Dec.of(linked.valueInr),restoredQty=Dec.of(linked.qty);
 if(restoredQty.gt('0')){
 const [effect]=await tx.insert(supplierResolutionEffect).values({tenantId:ctx.tenant.tenantId,entityId:e,claimLineId:a.claimLineId,returnEffectId:r.id,kind:'acceptance_reversal',qty:restoredQty.neg().toString(),valueInr:restored.neg().toString(),postingDate:businessDate(),reason,createdBy:ctx.user.id}).returning();const selected=await returnAccountsIn(tx,ctx,e,a.claimLineId,r.stockEntryId);const pending={id:selected.pending},variance={id:selected.variance};await this.gl.postIn(tx,ctx,e,{type:'supplier_return_resolution',id:effect!.id,purpose:'main',evidenceVoucherIds:selected.evidenceVoucherIds},businessDate(),{disposition:restored.isZero()?'no_value_change':'posted',lines:restored.isZero()?[]:[{accountId:pending.id,debit:restored.toFixed(6),credit:'0'},{accountId:variance.id,debit:'0',credit:restored.toFixed(6)}]});
 }
 }
 await tx.insert(supplierAcceptanceEffect).values({...a,id:undefined,qty:Dec.of(a.qty).neg().toString(),taxableAmount:Dec.of(a.taxableAmount).neg().toString(),pendingValueInr:Dec.of(a.pendingValueInr).neg().toString(),reversalOf:a.id,createdAt:new Date()});
 }}
 await tx.update(supplierNote).set({status:'cancelled',cancelledBy:ctx.user.id,cancelledAt:new Date(),cancelReason:reason,updatedAt:new Date()}).where(eq(supplierNote.id,id));await this.bills.assertReconciledIn(tx,e);await this.audit.record(ctx,{tenantId:ctx.tenant.tenantId,entityId:e,action:'supplier_note.cancel',targetType:'supplier_note',targetId:id,reason},tx);return {ok:true};
 }
}
