import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {startSsoFixture} from './sso-test-helpers.mjs';
const f=await startSsoFixture();let n=0;const test=async(name,fn)=>{await fn();n++;console.log('PASS '+name);};
try{
 const owner=await f.localUser();
 for(const provider of ['google','microsoft']){const start=await f.start(provider,owner),code=f.provider.authorize(start.data.url,{subject:provider+'-mfa'});assert.equal(new URL((await f.request(code.callback,null,start.cookies)).location).pathname,'/sso/complete');}
 const enabled=await f.request('/two-factor/enable',{password:'Synthetic-password-123'},owner.cookies);assert.equal(enabled.status,200);const secret=new URL(enabled.data.totpURI).searchParams.get('secret'),backup=enabled.data.backupCodes;
 const code=async()=>{const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits='';for(const char of secret.replace(/=+$/,''))bits+=alphabet.indexOf(char).toString(2).padStart(5,'0');const key=Buffer.from(bits.match(/.{8}/g).map(b=>parseInt(b,2))),counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const digest=createHmac('sha1',key).update(counter).digest(),offset=digest.at(-1)&15;return ((digest.readUInt32BE(offset)&0x7fffffff)%1000000).toString().padStart(6,'0');};
 assert.equal((await f.request('/two-factor/verify-totp',{code:await code()},owner.cookies)).status,200);
 async function pending(provider='google'){
  const start=await f.start(provider),consent=f.provider.authorize(start.data.url,{subject:provider+'-mfa'}),response=await f.request(consent.callback,null,start.cookies);
  assert.equal(response.status,302);assert.equal(new URL(response.location).pathname,'/sign-in/two-factor',JSON.stringify({diagnostics:f.diagnostics.slice(-2),challenges:(await f.db.$client.query("select identifier,sso_account_id is not null as bound from verification where identifier like '2fa-%'")).rows}));return start.cookies;
 }
 for(const provider of ['google','microsoft'])await test(provider+' callback grants no authority before actual TOTP',async()=>{const cookies=await pending(provider);assert.equal((await f.request('/get-session',null,cookies)).data,null);assert.equal((await f.request('/list-sessions',null,cookies)).status,401);assert.equal((await f.db.$client.query('select count(*)::int n from session where sso_pending')).rows[0].n,0);assert((await f.request('/two-factor/verify-totp',{code:'invalid'},cookies)).status>=400);assert.equal((await f.request('/get-session',null,cookies)).data,null);{const result=await f.request('/two-factor/verify-totp',{code:await code()},cookies);assert.equal(result.status,200,JSON.stringify({error:result.data?.code,message:result.data?.message}));}const current=await f.request('/get-session',null,cookies);assert.equal(current.data.user.id,owner.id);const row=(await f.db.$client.query('select * from session where id=$1',[current.data.session.id])).rows[0];assert(row.sso_account_id);assert.equal(row.sso_pending,false);assert.equal((await f.db.$client.query("select count(*)::int n from auth_sso_event where session_id=$1 and kind='signed_in'",[row.id])).rows[0].n,1);await f.request('/sign-out',{},cookies);assert((await f.request('/two-factor/verify-totp',{code:await code()},cookies)).status>=400);});
 await test('native backup code creates one complete bound session',async()=>{const cookies=await pending();assert.equal((await f.request('/two-factor/verify-backup-code',{code:backup[0]},cookies)).status,200);assert.equal((await f.request('/get-session',null,cookies)).data.user.id,owner.id);await f.request('/sign-out',{},cookies);const again=await pending();assert((await f.request('/two-factor/verify-backup-code',{code:backup[0]},again)).status>=400);});
 await test('expired framework challenge refused',async()=>{const cookies=await pending();await f.db.$client.query("update verification set expires_at=clock_timestamp()-interval '1 second' where identifier like '2fa-%'");assert((await f.request('/two-factor/verify-totp',{code:await code()},cookies)).status>=400);assert.equal((await f.request('/get-session',null,cookies)).data,null);});
 await test('valid native trusted device remains allowed',async()=>{const cookies=await pending();assert.equal((await f.request('/two-factor/verify-totp',{code:await code(),trustDevice:true},cookies)).status,200);const trust=[...cookies].filter(([key])=>key.includes('trust_device'));assert.equal(trust.length,1);await f.request('/sign-out',{},cookies);const start=await f.start('google');for(const entry of trust)start.cookies.set(...entry);const consent=f.provider.authorize(start.data.url,{subject:'google-mfa'}),response=await f.request(consent.callback,null,start.cookies);assert.equal(new URL(response.location).pathname,'/sso/complete');assert.equal((await f.request('/get-session',null,start.cookies)).data.user.id,owner.id);});
 await test('provider disabled during pending challenge refuses new session',async()=>{const cookies=await pending();const config=f.config.sso.google;f.config.sso.google=null;try{assert((await f.request('/two-factor/verify-totp',{code:await code()},cookies)).status>=400);assert.equal((await f.request('/get-session',null,cookies)).data,null);}finally{f.config.sso.google=config;}});
 for(const field of ['issuer','clientId'])await test(field+' changed while MFA pending refuses session',async()=>{const cookies=await pending('microsoft'),original=f.config.sso.microsoft[field];f.config.sso.microsoft[field]='changed-config';try{assert((await f.request('/two-factor/verify-totp',{code:await code()},cookies)).status>=400);assert.equal((await f.request('/get-session',null,cookies)).data,null);}finally{f.config.sso.microsoft[field]=original;}});
 await test('original password TOTP challenge remains native and unbound',async()=>{const cookies=f.jar(),signin=await f.request('/sign-in/email',{email:owner.email,password:'Synthetic-password-123'},cookies);assert.equal(signin.data.twoFactorRedirect,true);assert.equal((await f.request('/get-session',null,cookies)).data,null);assert.equal((await f.request('/two-factor/verify-totp',{code:await code()},cookies)).status,200);const current=await f.request('/get-session',null,cookies);assert.equal((await f.db.$client.query('select sso_account_id from session where id=$1',[current.data.session.id])).rows[0].sso_account_id,null);});
 await test('native revoke-other-sessions invalidates owned pending SSO challenges',async()=>{const cookies=await pending();assert.equal((await f.request('/revoke-other-sessions',{},owner.cookies)).status,200);assert((await f.request('/two-factor/verify-totp',{code:await code()},cookies)).status>=400);assert.equal((await f.request('/get-session',null,cookies)).data,null);});
 await test('forced sign-in evidence failure leaves no usable session',async()=>{const cookies=await pending();await f.db.$client.query("create function fixture_mfa_evidence() returns trigger language plpgsql as $$begin if NEW.kind='signed_in' then raise exception 'synthetic evidence unavailable';end if;return NEW;end$$;create trigger fixture_mfa_evidence before insert on auth_sso_event for each row execute function fixture_mfa_evidence()");const logs=[],original=console.error;console.error=(...args)=>logs.push(String(args[0]));try{assert((await f.request('/two-factor/verify-totp',{code:await code()},cookies)).status>=400);assert.equal((await f.request('/get-session',null,cookies)).data,null);assert.equal(logs.length,0,'no raw SQL/token failure logging');}finally{console.error=original;await f.db.$client.query('drop trigger fixture_mfa_evidence on auth_sso_event;drop function fixture_mfa_evidence()');}});
 await test('disconnected binding during pending challenge refuses new session',async()=>{const cookies=await pending(),local=await f.request('/get-session',null,owner.cookies);owner.ctx.sessionId=local.data.session.id;const binding=(await f.db.$client.query("select id from account where user_id=$1 and provider_id='google'",[owner.id])).rows[0].id;const proof=await f.service.issueAction(owner.ctx,{provider:'google',kind:'unlink',targetAccountId:binding},async()=>true);await f.service.disconnectAction(owner.ctx,binding,proof.nonce);await f.auth.api.unlinkAccount({body:{accountId:binding},headers:new Headers({cookie:[...owner.cookies].map(([k,v])=>k+'='+v).join('; '),'x-factoryos-sso-action':proof.nonce})});assert((await f.request('/two-factor/verify-totp',{code:await code()},cookies)).status>=400);assert.equal((await f.request('/get-session',null,cookies)).data,null);});
 console.log(`SSO MFA ${n} cases PASS; real native TOTP/backup/trusted-device lifecycle`);
}finally{await f.close();}
