'use client';
import { useEffect, useRef } from 'react';
import { ApiError, type Scope } from './api';
export const bankPath=(id:string)=>`/accounts/bank-reconciliation/profiles/${id}`;
export interface Mapping {delimiter:string;skipRows:number;dateFormat:'DD/MM/YYYY'|'MM/DD/YYYY'|'YYYY-MM-DD';dateColumn:string;referenceColumn?:string;descriptionColumn?:string;transactionIdColumn?:string;amount:{mode:'split';debitColumn:string;creditColumn:string}|{mode:'signed';column:string;polarity:'credit-positive'|'debit-positive'};decimalSeparator:'.'|',';groupSeparator:'.'|','|' '|null;order:'ascending'|'descending';runningBalanceColumn?:string;balanceRow?:{column:string;value:string}}
export const defaultMapping:Mapping={delimiter:',',skipRows:0,dateFormat:'DD/MM/YYYY',dateColumn:'Date',referenceColumn:'Ref',descriptionColumn:'Description',amount:{mode:'split',debitColumn:'Debit',creditColumn:'Credit'},decimalSeparator:'.',groupSeparator:null,order:'ascending'};
export interface Profile {id:string;accountId:string;currency:'INR';maskedIdentifier:string;dateWindow:number}
export interface Context {openingItems?:{id:string;postingDate:string;signedAmount:string;reference:string;reason:string;evidence:{document:string;source:string|{id:string;date:string;signedAmount:string;reference:string}};glEntryId:string|null;sourceVoucherId:string|null}[];profile:Profile;mapping:{id:string;revision:number;mapping:Mapping}|null;baseline:{id:string;baselineDate:string;bookBalance:string;bankBalance:string;reference:string;evidence:{document:string;ledger:Omit<BookItem,'remaining'>[]}}|null;revision:string}
export interface BookItem {id:string;kind:'gl'|'opening';date:string;signedAmount:string;reference:string;remaining:string}
export interface StatementItem {id:string;date:string;signedAmount:string;reference:string;remaining:string}
export interface MatchState {book:BookItem[];statement:StatementItem[];groups:{id:string;kind:string;reversed:boolean;reason?:string}[];revision:string;sources:{id:string;voucherId:string;sourceType:string;sourceId:string;status:string}[]}
export interface Report {profileId:string;baselineId:string;asOf:string;B:string;U:string;E:string;S:string;difference:string;coverageComplete:boolean;coverage:{complete:boolean;through:string;conflicts:string[];intervals:{id:string;startDate:string;endDate:string}[]};bookResiduals:BookItem[];statementResiduals:StatementItem[];previewHash:string}
export interface Period {id:string;startDate:string;endDate:string;createdBy:string;createdAt:string;previewHash:string;reopened?:boolean;reopening?:{reason:string;createdBy:string;createdAt:string}|null;snapshot:{report:Report;outstanding:BookItem[];reviewerId:string}}
export interface Adjustment {previewHash:string;row:StatementItem;bankAccountId:string;links:{id:string;kind:string;chargeId:string|null;voucherId:string|null;releasedAt:string|null;releaseReason:string|null}[]}
export const isZero=(value:string)=>/^-?0+(?:\.0+)?$/.test(value);
/** Reject late results after input changes or scope unmounts, including navigation side effects. */
export function useCurrentReview(key:string){const current=useRef(key),alive=useRef(true);current.current=key;useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);return (captured:string)=>alive.current&&current.current===captured;}
export async function uploadBankCsv(id:string,file:File,metadata:unknown,scope:Scope){const form=new FormData();form.set('file',file);form.set('metadata',JSON.stringify(metadata));const response=await fetch(`/api${bankPath(id)}/imports`,{method:'POST',credentials:'include',headers:{'x-tenant-id':scope.tenantId??'','x-entity-id':scope.entityId??''},body:form});const value=await response.json();if(!response.ok)throw new ApiError(response.status,typeof value.message==='string'?value.message:'Statement upload failed');return value as {id:string};}
export async function downloadBank(path:string,scope:Scope,name:string){const response=await fetch(`/api${path}`,{credentials:'include',headers:{'x-tenant-id':scope.tenantId??'','x-entity-id':scope.entityId??''}});if(!response.ok)throw new ApiError(response.status,'Download refused for this scope');const url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
