export interface SupplierPolicy {dispatchApproval:'pending_allowed'|'acceptance_required';claimApproval:'every'|'above_threshold';approvalThresholdInr:string;creditApplication:'automatic'|'manual';rejectedAction:'keep_open'|'request_back'|'propose_write_off'}
export interface SupplierLineInput {invoiceLineId:string;claimLineId?:string;mode:'quantity'|'value';qty:string;taxableAmount:string}
export interface SupplierNoteInput {invoiceId:string;kind:'credit'|'debit';taxTreatment:'gst'|'commercial';supplierNoteNo:string;supplierNoteDate:string;postingDate:string;reason:string;taxEligibilityConfirmed:boolean;lines:SupplierLineInput[]}
export interface SupplierTotals {taxableValue:string;cgst:string;sgst:string;igst:string;cess:string;grandTotal:string}
export interface SupplierPreview extends SupplierTotals {currency:string;exchangeRate:string;lines:{pendingValueInr:string;varianceInr:string}[]}
export interface SupplierNote extends SupplierTotals {id:string;originalInvoiceId:string;supplierId:string;number:string|null;status:'draft'|'submitted'|'cancelled';kind:'credit'|'debit';taxTreatment:'gst'|'commercial';supplierNoteNo:string;supplierNoteDate:string;postingDate:string;reason:string;taxEligibilityConfirmed:boolean;currency:string;exchangeRate:string;voucherId:string|null;billId:string|null;lines:(SupplierLineInput&{id:string;itemName:string;cgst:string;sgst:string;igst:string;cess:string})[];creditBalance:{openAmount:string;carryingInr:string}|null;applications:{id:string;number:string;status:string}[];snapshots:{supplierName?:string;supplierGstin?:string;supplierAddress?:{line1:string;line2?:string;city:string;stateCode:string;pincode:string;country?:string}[];buyerAddress?:{line1:string;line2?:string;city:string;stateCode:string;pincode:string;country?:string};buyerName?:string;buyerGstin?:string;originalInvoiceNumber?:string;originalInvoiceDate?:string}}
export interface PurchaseSource {id:string;number:string;supplierInvoiceNo:string;supplierInvoiceDate:string;postingDate:string;currency:string;status:string;lines:{id:string;itemId:string;itemName:string;qty:string;rate:string;taxableValue:string;gstRate:string}[]}
export interface ReturnClaimInput {invoiceId:string;postingDate:string;reason:string;lines:{invoiceLineId:string;qty:string;taxableAmount:string}[]}
export interface ReturnClaim {id:string;originalInvoiceId:string;number:string|null;status:'draft'|'submitted'|'cancelled';postingDate:string;reason:string;currency:string;exchangeRate:string;approvedBy:string|null;policySnapshot:SupplierPolicy|null;snapshots:SupplierNote['snapshots'];responses:{seq:string;reason:string;after:{suggestedAction:string}}[];lines:{id:string;invoiceLineId:string;itemName:string;isStockItem:boolean;qty:string;taxableAmount:string;dispatchedQty:string;acceptedQty:string;resolvedQty:string;pendingValueInr:string;receipts:{receiptAllocationId:string;receiptLineId:string;receiptNumber:string;batchId:string|null;batchNo:string|null;warehouseId:string;qty:string}[];movements:{id:string;stockEntryId:string;qty:string;valueInr:string;reversed:boolean}[];resolutions:{id:string;kind:string;qty:string;valueInr:string;stockEntryId:string|null;reversed:boolean}[]}[]}
